#!/usr/bin/env python3
"""Create the eleventh quality-checked 100-skill batch on Apple-platform engineering."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from skill_categories import category_for_skill
from skill_taxonomy import relative_skill_path, skill_path

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "skills"
README = ROOT / "README.md"
INDEX = ROOT / "INDEX.md"
README_MARKER = "| Skill | Use it for |"
INDEX_MARKER = "| If the task is about… | Load |"

SOURCES = {
    "catalog": ("steipete agent-scripts topic catalog", "https://github.com/steipete/agent-scripts"),
    "skills_index": ("agent-scripts skills grouping index", "https://github.com/steipete/agent-scripts/blob/main/skills.sh.json"),
    "swift_book": ("The Swift Programming Language: Concurrency", "https://docs.swift.org/latest/documentation/the-swift-programming-language/concurrency/"),
    "apple_swiftui": ("Apple SwiftUI performance documentation", "https://developer.apple.com/documentation/xcode/understanding-and-improving-swiftui-performance"),
    "apple_perf": ("Apple Xcode performance and metrics documentation", "https://developer.apple.com/documentation/xcode/performance-and-metrics"),
    "apple_tests": ("Apple Xcode performance testing documentation", "https://developer.apple.com/documentation/xcode/writing-and-running-performance-tests"),
    "apple_distribution": ("Apple Xcode app distribution workflow", "https://developer.apple.com/documentation/xcode/creating-a-workflow-that-builds-your-app-for-distribution"),
    "apple_codesign": ("Apple distribution-signed code documentation", "https://developer.apple.com/documentation/xcode/creating-distribution-signed-code-for-the-mac"),
    "apple_notarize": ("Apple macOS notarization documentation", "https://developer.apple.com/documentation/security/notarizing-macos-software-before-distribution"),
}

# slug | title | focus | method | evidence checks | domain guardrail | source key
RAW = r"""swift-actor-isolation-boundary-audit|Swift Actor Isolation Boundary Audit|mapping actor-isolated mutable state and its callers in a Swift codebase|Inventory shared mutable state, actor declarations, isolated protocol conformances, global actors, and call sites. Draw a compact state-ownership map, then test the narrowest boundary that protects each invariant.|Check synchronous access assumptions, cross-actor hops, reentrancy across await, nonisolated escape hatches, and deployment/compiler settings.|Do not add blanket actor annotations or change public isolation semantics without API-owner review.|swift_book
swift-sendable-conformance-safety-review|Swift Sendable Conformance Safety Review|reviewing whether Swift values can safely cross concurrency domains|Trace stored properties, captured references, mutation, locks, and actor isolation. Separate compiler-satisfied conformance from the semantic proof that shared access is safe.|Check generic constraints, closures, reference-type mutability, nested values, imported types, and any unchecked conformance.|Do not add unchecked Sendable merely to silence diagnostics; require a documented synchronization proof.|swift_book
swift-task-lifecycle-ownership-audit|Swift Task Lifecycle Ownership Audit|finding Swift tasks whose lifetime is not owned by a view, service, or operation|For each task creation site, identify its owner, expected lifetime, result consumer, cancellation path, and cleanup behavior. Prefer scoped child tasks where they fit the required lifetime.|Check stored task handles, discarded handles, view disappearance, repeated starts, errors, and service shutdown.|Do not cancel unrelated work or replace a required long-lived task with a short-lived scope without owner approval.|swift_book
swift-cancellation-propagation-test-plan|Swift Cancellation Propagation Test Plan|testing cooperative cancellation across async functions and child tasks|Map parent-child relationships and cancellation checkpoints, then build tests that cancel at controlled suspension points and verify cleanup and result policy.|Check network or file operations, task groups, callbacks, partial results, resource release, and cancellation races.|Do not treat calling cancel as proof that work stopped; avoid tests that assume immediate preemption.|swift_book
swift-task-group-fanout-budget-review|Swift Task Group Fanout Budget Review|setting a bounded concurrency policy for dynamically sized Swift task groups|Define input limits, maximum in-flight work, backpressure, cancellation, and partial-failure behavior before choosing a scheduling pattern. Measure peak memory and request rate on a representative fixture.|Check unbounded child creation, nested groups, retries, downstream quotas, and cancellation while producers are adding work.|Do not fan out an unbounded number of tasks or use a benchmark as permission to overload a service.|swift_book
swift-task-priority-inversion-investigation|Swift Task Priority Inversion Investigation|investigating latency caused by task priorities, actor queues, or synchronous waits|Record the user-visible operation and trace task creation, priority inheritance, actor hops, blocking calls, and dependency waits. Compare a repeatable baseline before changing priority.|Check priority escalation, detached tasks, locks, main-actor work, executor contention, and starvation under load.|Do not assume task priority guarantees execution order or a fixed latency improvement.|apple_perf
swift-main-actor-hop-responsiveness-review|Swift MainActor Hop Responsiveness Review|reviewing main-actor work and hops that may delay UI responsiveness|Map UI-bound state and call paths crossing MainActor. Profile the slow interaction, separate CPU work from actor scheduling, and move work only when data ownership remains safe.|Check expensive synchronous work, excessive hop chains, callbacks, isolated protocol requirements, and reentrancy after await.|Do not move UI state off MainActor or annotate entire modules without confirming thread-safety and API effects.|swift_book
swift-actor-reentrancy-invariant-analysis|Swift Actor Reentrancy Invariant Analysis|checking state invariants when an actor method suspends and later resumes|Mark each await in actor methods, list mutable assumptions made before and after it, and identify other actor messages that can run during suspension. Add a focused invariant test or version check.|Check stale reads, duplicate requests, partially updated state, cancellation, and error exits between awaits.|Do not assume actor isolation makes a multi-await operation atomic.|swift_book
swift-global-actor-api-boundary-check|Swift Global Actor API Boundary Check|reviewing global-actor annotations on public types, protocols, and callbacks|Compare API declarations, intended callers, source compatibility, and executor assumptions. Document whether isolation is part of the supported contract and compile representative downstream usage.|Check protocol witness isolation, static members, nonisolated declarations, imported callbacks, and older compiler modes.|Do not broaden or weaken public actor isolation as an incidental refactor.|swift_book
swift-continuation-single-resume-audit|Swift Continuation Single-Resume Audit|checking exactly-once completion when bridging callback APIs with continuations|Trace success, failure, cancellation, timeout, and duplicate callback paths. Use a small fake callback provider to verify one resume at most and deterministic cleanup.|Check synchronous callback-before-return, retained continuation state, races between cancellation and completion, and missing terminal paths.|Do not use a continuation bridge until its callback completion contract and ownership are understood.|swift_book
swift-async-stream-termination-review|Swift AsyncStream Termination Review|reviewing producer ownership, finish behavior, and cleanup for an AsyncStream|Document who owns the continuation, when the stream finishes, how termination reaches the producer, and whether events may be dropped. Test normal completion, consumer cancellation, and producer failure.|Check multiple finish calls, retained continuations, event-after-finish, and resource cleanup.|Do not leave an event source running after its consumer has terminated unless that lifetime is explicitly owned elsewhere.|swift_book
swift-async-sequence-buffer-backpressure-plan|Swift AsyncSequence Buffer and Backpressure Plan|choosing buffering and producer behavior for a high-volume asynchronous sequence|Estimate event rate, consumer service rate, memory budget, ordering needs, and acceptable loss before choosing buffering semantics. Verify with a burst fixture and slow consumer.|Check unbounded queues, duplicate delivery, late subscribers, producer cancellation, and overload behavior.|Do not silently drop events or grow memory without a stated policy and downstream owner approval.|swift_book
swift-callback-to-async-interop-migration-review|Swift Callback-to-Async Interop Migration Review|reviewing an incremental migration from completion handlers to async APIs|Inventory callback signatures, cancellation tokens, queue guarantees, error semantics, and caller compatibility. Migrate one boundary at a time and compare behavior under success, failure, and cancellation.|Check callback queue assumptions, double completion, reentrancy, legacy callers, and source/deployment compatibility.|Do not change a callback's threading or completion contract as a side effect of syntax modernization.|swift_book
swift-await-suspension-point-state-audit|Swift Await Suspension-Point State Audit|checking whether local state remains valid across Swift await suspension points|For every await, identify mutable objects, actor changes, external state, and assumptions that may become stale before resumption. Add revalidation or stable snapshots where needed.|Check collection mutation, view disappearance, task cancellation, actor reentrancy, and identity changes across suspension.|Do not treat code between two awaits as an atomic transaction.|swift_book
swift-detached-task-justification-review|Swift Detached Task Justification Review|reviewing whether Task.detached is necessary for a specific Swift operation|Record the context, actor, priority, task-local values, cancellation owner, and error/result route that the detached task will not inherit. Compare a regular task or structured child alternative.|Check loss of actor isolation, lost task-local context, discarded handles, and unowned cleanup.|Do not introduce detached work merely to move code off the main actor or to silence a concurrency warning.|swift_book
swift-task-group-partial-failure-policy|Swift Task Group Partial Failure Policy|defining results and cancellation semantics when one child in a Swift task group fails|Specify whether the operation is all-or-nothing, first-success, or partial-results; then test success, multiple failures, early exit, and cancellation with deterministic children.|Check unconsumed child errors, cleanup timing, nondeterministic completion order, and whether partial output can be mistaken for complete output.|Do not silently discard failures or change partial-result semantics without caller review.|swift_book
swift-concurrency-diagnostics-triage|Swift Concurrency Diagnostics Triage|classifying compiler diagnostics related to isolation, Sendable, and concurrency mode|Capture the exact compiler version, language mode, target settings, diagnostic, and smallest reproducer. Group related errors by root boundary before proposing minimal fixes.|Check warnings versus errors, imported modules, default actor isolation, protocol conformance, and availability constraints.|Do not claim a warning is harmless or make broad unsafe changes without a reproducible reason.|swift_book
swift-strict-concurrency-migration-cohort-plan|Swift Strict Concurrency Migration Cohort Plan|planning a staged move toward stricter Swift concurrency checking|Baseline current diagnostics, select a module or target cohort, define allowed temporary exceptions, and set exit criteria for each stage. Run tests and compatibility checks at each boundary.|Check dependency readiness, generated code, mixed language targets, public API exposure, and warning-count drift.|Do not flip project-wide settings or waive all diagnostics before assessing affected targets and build configurations.|swift_book
swift-unsafe-sendable-exception-record|Swift Unsafe Sendable Exception Record|documenting a narrowly justified unchecked Sendable conformance|Identify the exact mutable state, synchronization primitive, ownership invariant, callers, and independent review required. Keep the conformance local and include a stress-test or race-detection plan.|Check lock coverage, escaping references, initialization, destruction, callback reentrancy, and future mutation paths.|Do not treat a passing test as a substitute for a complete thread-safety argument.|swift_book
swift-concurrency-sanitizer-evidence-review|Swift Concurrency Sanitizer Evidence Review|interpreting race-detector and concurrency-checking evidence for a Swift target|Record compiler mode, sanitizer configuration, target, workload, and reproduced paths. Separate static checking, dynamic sanitizer observations, and untested execution paths.|Check excluded targets, runtime instrumentation limits, nondeterministic races, and sanitizer overhead.|Do not claim that a clean sanitizer run proves absence of all data races.|apple_tests
swift-async-test-determinism-review|Swift Async Test Determinism Review|reducing timing-dependent flakiness in tests of Swift asynchronous behavior|Replace arbitrary sleeps with explicit gates, continuations, controllable clocks, or observable completion conditions. Run the test repeatedly under varied scheduling and document remaining nondeterminism.|Check shared test state, actor isolation, task leakage, timeout assumptions, and order-dependent fixtures.|Do not add longer sleeps as the only response to a flaky asynchronous test.|apple_tests
swift-actor-test-isolation-design|Swift Actor Test Isolation Design|designing tests that verify an actor's state ownership without masking races|Define the actor's observable contract, use independent actors per test where practical, and test interleavings through controlled suspension points rather than unsynchronized internal access.|Check test concurrency, global actor requirements, shared fixtures, cancellation, and hidden cross-test state.|Do not weaken production actor isolation solely to simplify a test.|swift_book
swift-async-timeout-cancellation-design|Swift Async Timeout and Cancellation Design|designing timeout behavior that cancels and joins asynchronous work safely|Specify timeout ownership, cancellation propagation, late-result handling, cleanup, and error semantics. Compare the chosen implementation with current Swift APIs and test races at the timeout boundary.|Check child tasks that ignore cancellation, resources held after timeout, duplicate completion, and platform availability.|Do not assume a timeout wrapper forcibly stops non-cooperative work or use undocumented deadline behavior.|swift_book
swift-task-local-context-sensitivity-audit|Swift Task-Local Context Sensitivity Audit|reviewing what task-local metadata propagates into asynchronous child work|Inventory task-local values that carry tracing, locale, request IDs, or sensitive context. Check propagation across child, unstructured, and detached work and redact values at logging boundaries.|Check credential-like values, user identifiers, unstructured task creation, propagation defaults, and telemetry exports.|Do not put secrets or unnecessary personal data into task-local storage or logs.|swift_book
swift-concurrency-runtime-compatibility-matrix|Swift Concurrency Runtime Compatibility Matrix|checking concurrency language and runtime assumptions across supported build targets|Record compiler, Swift language mode, SDK, deployment target, runtime, and dependency versions. Compile and test a small representative API surface on every supported configuration.|Check newly introduced syntax, availability, library evolution, package tools versions, and simulator/device differences.|Do not infer compatibility from the newest local toolchain alone.|swift_book
swiftui-view-update-cause-trace-analysis|SwiftUI View Update Cause Trace Analysis|finding which state or environment change triggers an unexpected SwiftUI update|Capture a trace for a reproducible interaction, identify update groups and changed dependencies, and map causal events to the smallest owning view or model. Compare before and after one targeted change.|Check broad environment dependencies, observable property reads, transaction sources, repeated updates, and release-build behavior.|Do not remove a required state dependency merely to reduce update counts.|apple_swiftui
swiftui-body-computation-cost-audit|SwiftUI Body Computation Cost Audit|finding expensive synchronous work performed while SwiftUI computes view bodies|Inspect the affected body and call path, then profile the exact interaction to locate repeated formatting, sorting, decoding, or calculation. Move work only with clear input invalidation and cache semantics.|Check body recomputation count, data volume, allocation spikes, stale cache risk, and actor hops.|Do not optimize by caching values without defining when inputs invalidate the cache.|apple_swiftui
swiftui-observable-dependency-fanout-review|SwiftUI Observable Dependency Fanout Review|reducing unnecessary view updates caused by broad observable-model dependencies|Map which views read each observed property and group updates by user operation. Consider narrower state ownership or projections, then verify the dependency graph and visible behavior.|Check accidental reads, broad shared models, derived properties, environment injection, and mutation fanout.|Do not split state into speculative abstractions without evidence that dependency scope is the cause.|apple_swiftui
swiftui-list-identity-stability-check|SwiftUI List Identity Stability Check|checking stable identity for repeated SwiftUI rows and collection updates|Trace identifiers from source model through sorting, filtering, and rendering. Exercise insertion, deletion, reordering, and refresh with a fixture that detects row-state migration.|Check regenerated UUIDs, duplicate IDs, mutable identity, filtered indexes, and asynchronous updates.|Do not use array position or per-render random IDs when item identity must survive collection changes.|apple_swiftui
swiftui-large-collection-stack-profile-plan|SwiftUI Large Collection Stack Profile Plan|profiling a SwiftUI screen that renders a large number of repeated views|Define a representative collection size and interaction, capture initial render and scroll behavior, and compare memory and update cost under equivalent conditions.|Check eager child construction, nested view cost, image loading, geometry work, and first-render latency.|Do not switch to lazy containers based solely on intuition; measure layout and rendering trade-offs.|apple_swiftui
swiftui-lazy-stack-benefit-gate|SwiftUI Lazy Stack Benefit Gate|deciding whether a SwiftUI lazy stack improves a measured workload|Start from the current container, record initial render, scrolling, memory, and layout behavior, then compare the lazy alternative against the same dataset and device conditions.|Check view realization count, estimated versus resolved geometry, scroll jumps, accessibility traversal, and memory.|Do not assume lazy stacks are universally faster or preserve identical layout behavior for every view.|apple_swiftui
swiftui-layout-feedback-loop-diagnosis|SwiftUI Layout Feedback Loop Diagnosis|investigating repeated layout passes or unstable geometry in a SwiftUI view tree|Reproduce the layout change, trace geometry and preference updates, and identify a feedback path where a measurement changes the layout that produces the next measurement.|Check GeometryReader use, state mutation during layout, preference churn, animation, and device-size variation.|Do not patch a layout loop with arbitrary delays or fixed dimensions that break supported sizes.|apple_swiftui
swiftui-geometry-proxy-dependency-minimization|SwiftUI Geometry Proxy Dependency Minimization|reviewing broad geometry dependencies that cause avoidable SwiftUI recalculation|Identify which geometry values are consumed and where they flow. Narrow the dependency to the smallest view and compare update traces at relevant window sizes.|Check global size reads, preference propagation, nested geometry readers, dynamic type, and split-view resizing.|Do not remove geometry-driven behavior that is required for a supported responsive layout.|apple_swiftui
swiftui-preference-key-update-propagation|SwiftUI Preference Key Update Propagation Review|checking preference-key flows that cause repeated layout or state updates|Trace preference production, aggregation, observation, and any state mutation that follows. Build a minimal reproduction and verify that unchanged values do not trigger redundant work.|Check value equality, nested containers, coordinate spaces, animation transactions, and feedback into layout.|Do not rely on undocumented update ordering or silence a loop by dropping meaningful preferences.|apple_swiftui
swiftui-expensive-formatting-cache-review|SwiftUI Expensive Formatting Cache Review|reviewing repeated formatter or derived-value work during SwiftUI rendering|Profile formatting and derivation calls, identify stable inputs and locale dependencies, and compare a bounded cache or precomputed value with current behavior.|Check locale changes, time-zone changes, input invalidation, thread-safety, and memory retention.|Do not cache localized output without responding to locale and format-setting changes.|apple_swiftui
swiftui-image-decode-memory-budget|SwiftUI Image Decode and Memory Budget|controlling image decode size and peak memory on a SwiftUI screen|Measure source dimensions, decoded bitmap size, in-flight images, cache policy, and target display scale. Test a representative scroll and navigation sequence with memory instrumentation.|Check repeated decode, oversized source assets, cancellation on cell reuse, cache eviction, and peak concurrent loads.|Do not retain full-resolution images in long-lived view state when only a thumbnail is needed.|apple_perf
swiftui-scroll-hitch-reproduction-plan|SwiftUI Scroll Hitch Reproduction Plan|creating a repeatable reproduction for a scroll hitch in a SwiftUI interface|Pin device, OS, build, content, gesture, and initial state; collect a trace that spans the hitch and annotate user actions. Repeat runs to distinguish a stable issue from noise.|Check frame timeline, view updates, image decode, layout, main-thread work, and thermal or background conditions.|Do not infer a root cause from a single screenshot or a non-representative simulator run.|apple_swiftui
swiftui-animation-frame-budget-analysis|SwiftUI Animation Frame Budget Analysis|investigating dropped frames during a SwiftUI animation or transition|Record the target refresh conditions and animation timeline, then correlate frame hitches with view updates, layout, rendering, and expensive effects.|Check large animated hierarchies, implicit animation scope, image effects, device refresh rate, and background work.|Do not remove meaningful motion or accessibility settings without product and accessibility review.|apple_perf
swiftui-main-thread-hang-trace-review|SwiftUI Main Thread Hang Trace Review|triaging a frozen or unresponsive SwiftUI interaction using a trace|Capture the interaction and hang window, identify the main-thread stack and synchronous dependencies, and separate blocked I/O from CPU, lock, or actor-wait behavior.|Check nested sync calls, lock contention, expensive body work, synchronous file access, and deadlock evidence.|Do not label an actor hop as a deadlock without confirming the actual wait chain.|apple_perf
swiftui-state-owner-and-lifetime-review|SwiftUI State Owner and Lifetime Review|checking that SwiftUI state is owned by a view or model with the correct lifetime|Trace each state value from initialization to destruction, identify which view owns it, and test recreation, navigation, and scene changes against expected persistence.|Check accidental view recreation, duplicated sources of truth, environment ownership, and state surviving longer than intended.|Do not move state to global storage merely to preserve it across a navigation transition.|apple_swiftui
swiftui-view-model-introduction-decision|SwiftUI View Model Introduction Decision|deciding whether a complex SwiftUI view needs a separate model or can remain view-driven|List the state transitions, side effects, reusable logic, test seams, and ownership boundaries. Compare a minimal view-driven design with a model extraction using existing project conventions.|Check testability, dependency lifetime, duplicated derived state, initialization cycles, and unnecessary indirection.|Do not impose a single MV or MVVM pattern when the project's behavior and architecture do not require it.|skills_index
swiftui-view-extraction-regression-check|SwiftUI View Extraction Regression Check|verifying behavior after extracting or splitting a large SwiftUI view|Freeze the target interactions and state paths, make a narrow extraction, and compare screenshots, accessibility tree, navigation, and update behavior before and after.|Check environment propagation, bindings, identity, animation scope, preview setup, and modifier ordering.|Do not treat a smaller body or file as proof that behavior is preserved.|apple_swiftui
swiftui-navigation-state-restoration-test|SwiftUI Navigation State Restoration Test|testing navigation path and restoration behavior across view and scene lifecycle changes|Define the route model, supported restoration boundary, and expected state after relaunch, scene recreation, deep link, and invalid route. Verify serialization and recovery with a minimal fixture.|Check duplicate routes, stale identifiers, schema changes, split-view adaptation, and privacy-sensitive route payloads.|Do not persist sensitive navigation parameters or claim restoration support that is not implemented.|apple_swiftui
swiftui-multiplatform-layout-adaptation-review|SwiftUI Multiplatform Layout Adaptation Review|reviewing a SwiftUI layout across iPhone, iPad, and macOS window conditions|List supported platforms, window sizes, input modes, and navigation patterns. Test resize, split view, keyboard, pointer, and compact/regular presentations with representative content.|Check minimum and maximum window size, toolbar overflow, safe areas, focus, and platform-specific controls.|Do not assume a layout that works on one device class is usable on every Apple platform.|apple_swiftui
swiftui-dynamic-type-text-truncation-audit|SwiftUI Dynamic Type and Text Truncation Audit|checking text readability and truncation at supported accessibility text sizes|Exercise key screens at dynamic type sizes, inspect line limits and layout priorities, and confirm critical actions remain visible and understandable.|Check long localized strings, minimum window sizes, nested stacks, buttons, and content compression.|Do not solve truncation by shrinking text below the user's selected accessibility size.|apple_swiftui
swiftui-accessibility-focus-order-test|SwiftUI Accessibility Focus Order Test|testing accessible focus, labels, and action order in a SwiftUI view|Define important tasks and expected focus sequence, inspect the accessibility tree with approved tooling, and exercise keyboard or assistive-technology navigation.|Check duplicate labels, hidden decorative elements, custom controls, modal focus return, and dynamic content announcements.|Do not treat visual order or automated lint output as a complete accessibility evaluation.|apple_swiftui
swiftui-multiwindow-scene-state-isolation-test|SwiftUI Multiwindow Scene State Isolation Test|testing whether independent SwiftUI windows retain or share state according to the product design|Open multiple windows for the same and different documents, mutate state in one window, switch focus, and close or reopen scenes. Compare state ownership with the documented shared-versus-per-window contract.|Check accidental global state, duplicated document models, scene identity, window commands, and restoration collisions.|Do not assume windows are isolated or shared; verify the app's intended ownership model.|apple_swiftui
swiftui-view-task-cancellation-reload-review|SwiftUI View Task Cancellation and Reload Review|reviewing asynchronous work started by SwiftUI view lifecycle modifiers|Trace the task identity, input dependencies, cancellation behavior, and output application. Test rapid navigation or input changes and confirm stale results cannot overwrite newer state.|Check repeated task starts, cancellation-insensitive APIs, actor isolation, error display, and view identity changes.|Do not rely on cancellation alone to reject stale results; validate the request identity when needed.|swift_book
swiftui-preview-fixture-determinism-review|SwiftUI Preview Fixture Determinism Review|making SwiftUI previews reproducible without live services or user data|Replace network, clock, random, and device-dependent inputs with explicit preview fixtures. Confirm preview setup cannot write to production services or real account state.|Check fixture reset, locale, appearance, dynamic type, missing assets, and accidental credential lookup.|Do not place real credentials, customer records, or private API endpoints in preview data.|skills_index
swiftui-ui-test-flakiness-analysis|SwiftUI UI Test Flakiness Analysis|diagnosing a UI test that intermittently fails in a SwiftUI navigation or rendering flow|Capture test logs, screenshots, accessibility tree, app state, and animation or network timing at failure. Replace blind waits with explicit user-visible conditions where possible.|Check unstable identifiers, asynchronous content, animation, focus, locale, simulator load, and stale test state.|Do not mask a regression by increasing a timeout without identifying the missing condition.|apple_tests
xcode-build-configuration-parity-review|Xcode Build Configuration Parity Review|checking differences between Debug, Release, and CI build settings for an Apple target|Compare resolved build settings for the exact scheme, configuration, SDK, and destination. Identify settings that change optimization, signing, entitlements, resources, or conditional compilation.|Check user-defined overrides, xcconfig layering, environment variables, generated settings, and archive-specific values.|Do not change signing or release settings as a workaround without artifact-owner approval.|apple_distribution
xcode-scheme-test-action-audit|Xcode Scheme Test Action Audit|reviewing which targets and configurations an Xcode scheme actually builds and tests|Inspect the shared scheme and its build, test, launch, profile, analyze, and archive actions. Compare the actions with the intended local and CI acceptance gates.|Check scheme sharing, test target inclusion, pre-actions, post-actions, configuration selection, and environment variables.|Do not assume a passing scheme runs every test target or uses the same settings as an archive.|apple_tests
xcode-test-plan-coverage-matrix|Xcode Test Plan Coverage Matrix|designing test configurations across Apple platforms, locales, devices, and runtime options|List supported axes, select risk-based combinations, and record the test plan configuration that covers each required behavior. Keep expensive exhaustive combinations separate from smoke coverage.|Check device family, OS version, language, accessibility settings, sanitizer configuration, and duplicated configurations.|Do not claim full matrix coverage from a single simulator configuration.|apple_tests
xcodebuild-destination-pinning-review|Xcodebuild Destination Pinning Review|making an Xcode test or build select the intended destination reproducibly|Record available destinations, selected device or simulator, OS runtime, architecture, and scheme. Make selection explicit and verify the effective destination from the build result.|Check ambiguous device names, unavailable runtimes, generic destinations, connected devices, and CI image changes.|Do not assume a destination string selects the same runtime across machines or Xcode versions.|apple_tests
xcode-simulator-runtime-compatibility-check|Xcode Simulator Runtime Compatibility Check|checking that a required simulator runtime is installed and compatible with a test target|Record Xcode version, installed simulator runtimes, supported deployment targets, and device family. Run a small non-destructive boot and test preflight on an owned simulator.|Check runtime downloads, duplicate devices, architecture, unavailable status, and CI image drift.|Do not install runtimes or modify developer-machine state without explicit authorization.|apple_tests
xcode-derived-data-cache-isolation|Xcode Derived Data Cache Isolation|diagnosing stale or cross-target build artifacts in DerivedData|Record workspace, scheme, configuration, Xcode version, and DerivedData path. Compare an isolated clean build with the normal cache path and identify which artifact changes the result.|Check shared CI cache keys, generated sources, module caches, concurrent builds, and symlinked workspaces.|Do not delete another user's or a shared build cache without ownership and recovery approval.|apple_tests
xcode-result-bundle-diagnostic-triage|Xcode Result Bundle Diagnostic Triage|extracting actionable evidence from an Xcode xcresult bundle|Identify the exact result bundle and Xcode version, inspect test failures, attachments, diagnostics, and performance records, and summarize only the relevant redacted evidence.|Check multiple test attempts, retry status, screenshots with private content, missing attachments, and result-bundle schema changes.|Do not upload raw result bundles to an external service without privacy and data-owner approval.|apple_tests
xcode-build-log-failure-phase-isolation|Xcode Build Log Failure Phase Isolation|finding the first causal failure in a long Xcode build or archive log|Separate build phases and target invocations, locate the first substantive error, and trace later failures to their dependency. Preserve a minimal excerpt with command and tool versions.|Check parallel target interleaving, warnings promoted to errors, script phases, signing, and errors hidden by truncated logs.|Do not treat the final generic build-failed line as the root cause or share unredacted environment values.|apple_tests
xcode-archive-reproducibility-check|Xcode Archive Reproducibility Check|checking whether repeated Xcode archives differ for a controlled source revision|Pin source revision, toolchain, scheme, configuration, signing inputs, and environment. Compare archive contents and metadata while identifying expected nondeterministic fields.|Check timestamps, UUIDs, generated assets, build numbers, signing, entitlements, and dependency resolution.|Do not claim bit-for-bit reproducibility unless the comparison accounts for signatures and documented nondeterminism.|apple_distribution
xcode-export-options-profile-validation|Xcode Export Options and Profile Validation|checking export settings and provisioning profile compatibility for an Apple archive|Compare archive entitlements, bundle identifiers, distribution method, profile, certificate, and export options using a non-production artifact. Verify with the current Xcode export interface.|Check extension identifiers, team selection, profile expiration, capability changes, and per-configuration overrides.|Do not modify or disclose signing identities, private keys, or provisioning secrets during diagnosis.|apple_codesign
xcode-ci-signing-secret-boundary-review|Xcode CI Signing Secret Boundary Review|reviewing where Apple signing credentials enter a build pipeline and how they are protected|Map secret source, identity, scope, injection point, runner lifetime, log redaction, and cleanup. Test a synthetic credential path in an isolated CI environment.|Check forked pull requests, artifact retention, shell tracing, environment dumps, keychain persistence, and runner reuse.|Do not print, export, upload, or rotate real signing secrets without explicit authorization from the credential owner.|apple_codesign
apple-code-signing-entitlement-minimization|Apple Code-Signing Entitlement Minimization|reviewing whether an Apple app target requests only the entitlements needed for its approved behavior|Map each entitlement to a code target, feature, user-facing permission, and current platform documentation. Compare signed output with the source entitlement file.|Check inherited entitlements, extensions, helper executables, debug-only values, and distribution-profile mismatches.|Do not add broad entitlements to bypass platform restrictions or make a release decision without the signing owner.|apple_codesign
macos-nested-code-signature-order-audit|macOS Nested Code Signature Order Audit|checking signing order and signature integrity for a macOS app with embedded code|Inventory nested frameworks, extensions, helper tools, and main executables. Verify signatures from inner components outward and confirm the outer bundle validates after packaging.|Check changed resources after signing, wrong identity, nested helper entitlements, ad hoc signatures, and package transformations.|Do not modify or resign a distributed product without release-owner approval and preserved source artifacts.|apple_codesign
macos-gatekeeper-first-launch-check|macOS Gatekeeper First Launch Check|testing the first-launch experience of an authorized macOS distribution artifact|Use a clean, task-owned test account or VM to verify quarantine, signature display, notarization ticket availability, and documented user prompts. Record OS version and artifact hash.|Check online versus stapled ticket behavior, app translocation, installer packaging, and expected warnings.|Do not bypass Gatekeeper or ask users to disable platform security as a release workaround.|apple_notarize
macos-notarization-submission-evidence-audit|macOS Notarization Submission Evidence Audit|preparing a traceable evidence record for a notarization submission|Record artifact hash, signing identity type, entitlements, hardened-runtime configuration, submission identifier, tool versions, and returned status. Redact credentials and retain only approved logs.|Check nested code, invalid signatures, timestamp configuration, package format, and submission ownership.|Do not treat notarization as App Review, security certification, or a guarantee of software safety.|apple_notarize
macos-notarization-ticket-stapling-verification|macOS Notarization Ticket Stapling Verification|verifying that a notarization ticket is attached to the intended macOS artifact|Compare artifact identity and hash before and after stapling, inspect ticket status with current Apple tools, and test the offline first-launch path on an owned clean system.|Check nested apps, disk images, installer packages, post-stapling modifications, and online ticket availability.|Do not staple or distribute a release artifact unless the release owner explicitly authorizes that action.|apple_notarize
macos-privacy-manifest-consistency-check|macOS Privacy Manifest Consistency Check|checking consistency among an app's privacy manifest, included SDKs, and collected-data claims|Inventory bundled privacy manifests and SDK declarations, map them to documented app behavior and the current Apple requirements, and record unresolved ownership questions.|Check duplicate manifests, transitive SDKs, accessed API declarations, data-use wording, and release configuration differences.|Do not invent privacy disclosures or submit a product declaration without the responsible privacy owner's approval.|apple_distribution
app-store-privacy-label-evidence-reconciliation|App Store Privacy Label Evidence Reconciliation|reconciling App Store privacy statements with documented app and SDK data flows|Map each proposed disclosure to a data flow, purpose, collection behavior, linked identifier, and responsible owner. Compare against current platform policy and the submitted build's dependencies.|Check third-party SDK updates, optional features, account state, analytics, diagnostics, and retention behavior.|Do not certify compliance or submit a privacy label based on an incomplete code or vendor review.|apple_distribution
apple-testflight-beta-cohort-change-control|Apple TestFlight Beta Cohort Change Control|planning a controlled change to internal or external beta tester groups|Record build identity, cohort, invitation scope, test purpose, feedback channel, review needs, and start/stop conditions. Use a test account and obtain owner approval before changing access.|Check external review requirements, tester data exposure, expiration, build replacement, and feedback privacy.|Do not invite users, expand a beta cohort, or publish a build without explicit release authorization.|apple_distribution
app-store-connect-build-train-readiness|App Store Connect Build Train Readiness|checking version and build-number state before an authorized App Store Connect submission|Reconcile source version, archived binary, build number, release notes, platform, and existing build-train status with the release owner's plan.|Check duplicate build numbers, phased release settings, localization, pending review state, and metadata mismatch.|Do not submit, release, or change phased-release settings without explicit authorization.|apple_distribution
macos-update-feed-integrity-review|macOS App Update Feed Integrity Review|reviewing an app update feed for version, channel, and artifact consistency|Compare feed entries with approved release artifacts, version ordering, channel, download URL, and expected signature metadata. Validate the feed using a parser or staging client.|Check stale entries, duplicate versions, mismatched hashes, redirected URLs, and private signing data exposure.|Do not edit a public update feed or publish an appcast without release-owner authorization.|apple_distribution
macos-update-payload-signature-negative-test|macOS Update Payload Signature Negative Test|testing that a macOS app update client rejects altered or incorrectly signed update payloads|Use a disposable test installation and synthetic release artifacts. Verify the expected payload signature, then exercise controlled tampered-payload, wrong-key, and mismatched-metadata cases and record whether the client fails closed.|Check partial downloads, key rotation, stale metadata, archive replacement after signing, and user-visible recovery behavior.|Do not disable signature verification or point real users at a test update feed.|apple_codesign
macos-installer-package-content-inventory|macOS Installer Package Content Inventory|checking the files and scripts included in a macOS installer package|Extract or inspect a built package in a safe workspace and reconcile payload files, install scripts, permissions, launch items, and signatures against a reviewed manifest.|Check hidden files, absolute paths, unexpected executables, symlinks, postinstall side effects, and stale build artifacts.|Do not install the package on a production machine or execute installer scripts without explicit approval.|apple_distribution
macos-universal-binary-slice-validation|macOS Universal Binary Slice Validation|checking architecture slices and minimum OS metadata in a macOS release binary|Inspect each relevant executable and library in the packaged artifact, compare architecture slices and load commands with supported targets, and run a bounded smoke test per architecture.|Check nested frameworks, helper tools, plugins, simulator-only artifacts, and architecture-specific dependencies.|Do not infer full compatibility from the main executable alone or remove a slice without product approval.|apple_distribution
apple-release-symbol-artifact-retention|Apple Release Symbol Artifact Retention|planning retention and access controls for dSYM and symbol artifacts across Apple releases|Map each archive and dSYM to source revision, build UUID, release channel, storage location, access owner, and retention period. Verify retrieval using a non-sensitive test crash.|Check archive-to-symbol UUID match, private source maps, access logging, lifecycle expiration, and backup restore.|Do not publish symbol bundles or crash data that expose internal paths or user information.|apple_distribution
instruments-trace-capture-scope-plan|Instruments Trace Capture Scope Plan|planning a bounded Instruments capture for a native Apple app performance question|Choose the target operation, app build, device, template, capture duration, interaction script, and sensitive-data controls before recording. Capture enough warm-up and workload to explain the observed behavior.|Check startup versus steady state, background activity, target process identity, permissions, trace size, and repeatability.|Do not profile a third-party or production process without authorization; avoid capturing private user content.|apple_perf
xctrace-target-process-identity-validation|Xctrace Target Process Identity Validation|verifying that an xctrace recording attaches to or launches the intended app binary|Record PID, process path, bundle identifier, build hash, and launch context immediately before capture. Confirm the trace contains frames from the expected build.|Check duplicate app installations, launch services resolution, helper processes, stale PIDs, and simulator/device target.|Do not interpret a trace until target identity and binary version are verified.|apple_perf
instruments-time-profiler-hotspot-ranking-audit|Instruments Time Profiler Hotspot Ranking Audit|ranking CPU hotspots from a native app trace without overstating sample precision|Verify trace workload and symbols, aggregate relevant frames, distinguish inclusive from self time, and report sample count and capture limitations.|Check idle samples, missing symbols, system frames, recursion, short captures, and build mismatch.|Do not equate sampled CPU time with wall-clock latency or claim causality from ranking alone.|apple_perf
macos-dsym-build-identity-match|macOS dSYM Build Identity Match|checking that debug symbols correspond to the exact macOS binary being analyzed|Compare the executable UUID with dSYM UUIDs for every architecture and preserve the build and archive identifiers in the analysis record.|Check stale dSYMs, universal slices, stripped binaries, regenerated archives, and symbol maps from another build.|Do not symbolicate or publish a report as exact when the binary-symbol identity does not match.|apple_perf
instruments-memory-allocation-retention-analysis|Instruments Memory Allocation and Retention Analysis|separating transient allocation volume from persistent object retention in a native app|Capture the workload from a known starting state, compare allocation and live-object timelines, and inspect ownership paths for objects that remain after the feature completes.|Check autorelease pools, image buffers, caches, cycles, repeated navigation, and process memory pressure.|Do not label high allocation volume a leak without evidence of unbounded retention.|apple_perf
ios-memory-pressure-termination-investigation|iOS Memory Pressure Termination Investigation|triaging an iOS app termination associated with memory pressure|Correlate device logs, app memory footprint, reproduction steps, OS version, and workload. Distinguish jetsam or memory termination from crash, watchdog, and user force-quit evidence.|Check device model, background state, peak allocations, large assets, scene restoration, and system memory pressure.|Do not infer a root cause from a generic termination report or request full private device logs unnecessarily.|apple_perf
instruments-leak-cycle-evidence-check|Instruments Leak Cycle Evidence Check|testing whether an object graph remains retained after a feature's expected lifecycle ends|Create and dismiss the feature under a controlled test, inspect allocation and reference-cycle evidence, and compare counts across repeated cycles.|Check delegates, closures, tasks, notifications, timers, caches, and framework-owned references.|Do not break a necessary ownership relationship based solely on a leak instrument warning.|apple_perf
xcode-organizer-crash-trend-triage|Xcode Organizer Crash Trend Triage|prioritizing crash and hang trends from Xcode Organizer for an authorized app|Define release range, affected versions, user impact measure, and grouping rule. Separate crash clusters, hangs, and termination signals, then map each finding to a build and responsible owner.|Check small samples, symbolication state, duplicate signatures, rollout exposure, and changes in reporting volume.|Do not claim population incidence from an incomplete or selection-biased report set.|apple_perf
macos-crash-report-symbolication-readiness|macOS Crash Report Symbolication Readiness|checking whether a macOS crash report can be symbolicated safely and accurately|Collect the minimum authorized report fields, confirm binary and dSYM UUIDs, record architecture and OS version, and test symbolication locally with matching artifacts.|Check missing image list, stripped symbols, stale dSYMs, helper process crashes, and private paths or user data in logs.|Do not upload raw crash reports or dSYMs to external services without approval and redaction review.|apple_perf
swift-signpost-hitch-correlation|Swift Signpost and UI Hitch Correlation|correlating app-defined signposts with UI hitches and user actions in an Instruments trace|Place bounded signpost intervals around a representative operation, record the same workflow, and correlate intervals with frame or view-update stalls.|Check signpost naming stability, concurrent intervals, release-build availability, privacy of payloads, and clock alignment.|Do not include user-entered text, account IDs, or secrets in signpost metadata.|apple_swiftui
xcode-app-launch-phase-budget|Xcode App Launch Phase Budget|breaking app launch time into attributable stages for an Apple application|Define cold and warm launch, target device and build, first useful screen, and stage boundaries. Capture repeated launch traces and separate OS work from application-controlled work.|Check static initializers, synchronous disk or network work, dependency startup, image decode, and launch environment.|Do not optimize a launch metric by skipping required security checks or essential state recovery.|apple_perf
swiftui-hitch-vs-app-hang-classification|SwiftUI Hitch Versus App Hang Classification|distinguishing dropped frames from a blocked main thread in a SwiftUI report|Align user actions with trace timestamps and classify frame hitches, long view updates, main-thread hangs, and blocked dependencies separately.|Check render-loop evidence, event handling, CPU saturation, synchronous waits, and reporting thresholds.|Do not conflate a visual hitch with a deadlock or an application crash.|apple_swiftui
instruments-network-traffic-privacy-review|Instruments Network Traffic Privacy Review|reviewing which network activity occurs during a bounded native app test|Capture only an authorized test account and controlled workload, inventory domains and request timing, and distinguish app behavior from third-party SDK traffic.|Check consent, authentication headers, request bodies, user identifiers, redirects, and telemetry data in trace exports.|Do not export or share traces containing tokens, payloads, or personal data without redaction and approval.|apple_perf
apple-app-energy-impact-measurement-plan|Apple App Energy Impact Measurement Plan|planning a repeatable energy-use measurement for an Apple app feature|Define device state, battery and thermal conditions, app build, user journey, duration, and measurement tool. Separate controlled lab results from field observations.|Check screen brightness, radio state, background activity, measurement variance, and repeated-run order.|Do not infer battery life for all devices from a short or single-device test.|apple_perf
apple-app-storage-footprint-regression-check|Apple App Storage Footprint Regression Check|checking whether an Apple app release increases installed or user-data storage unexpectedly|Measure application bundle, support files, caches, and user-generated data before and after a controlled scenario. Reconcile large file deltas with the build manifest.|Check app thinning, universal assets, downloaded content, logs, cache cleanup, and upgrade migration.|Do not inspect or copy user documents beyond the approved test fixture.|apple_perf
apple-background-task-expiration-audit|Apple Background Task Expiration Audit|checking how app work responds when an Apple platform ends background execution time|Map background entry points, task registration, expiration callbacks, cancellation, and persisted progress. Simulate expiration and relaunch on supported OS versions.|Check duplicate scheduling, partial writes, long-running tasks, user-visible status, and resource cleanup.|Do not assume background execution is guaranteed or bypass platform scheduling limits.|apple_perf
macos-tcc-permission-attribution-test|macOS TCC Permission Attribution Test|testing which process receives a macOS privacy permission prompt for an approved app workflow|Use an owned test account and app, document the launching process chain, request only the needed permission, and verify the prompt and resulting access under current OS settings.|Check terminal versus GUI launch, helper process identity, bundle signing, reset state, and user consent.|Do not reset or grant permissions on a user's machine without explicit permission, and never bypass TCC controls.|apple_codesign
macos-app-sandbox-file-access-boundary-test|macOS App Sandbox File Access Boundary Test|checking sandboxed file access for a defined macOS app feature|Define allowed directories and user-selected files, exercise granted and denied paths, and inspect entitlements and bookmark handling with synthetic data.|Check stale security-scoped bookmarks, path traversal, extension helpers, file coordination, and denied-access behavior.|Do not expand sandbox entitlements or read files outside the approved test fixture to make a test pass.|apple_codesign
macos-keychain-access-group-review|macOS Keychain Access Group Review|reviewing which signed Apple targets can read or write a keychain access group|Map each target's identifier, entitlement, team, access group, item accessibility, and intended owner. Test with synthetic credentials and verify deny as well as allow cases.|Check helper apps, extensions, changed team IDs, migration behavior, and broad access-group wildcards.|Do not print, retrieve, export, or rotate real credentials during a configuration review.|apple_codesign
macos-login-item-launch-agent-lifecycle-audit|macOS Login Item and Launch Agent Lifecycle Audit|reviewing a macOS app's background start, update, and uninstall behavior|Inventory login items, launch agents, helper executables, user consent, update behavior, and clean removal steps. Validate state transitions in a disposable account.|Check duplicate registrations, stale jobs after uninstall, privileged helpers, signature identity changes, and upgrade rollback.|Do not install or enable persistent background components on a shared or production machine without authorization.|apple_codesign
remote-mac-build-agent-isolation-review|Remote Mac Build Agent Isolation Review|reviewing isolation and credential exposure on a remote macOS build worker|Map runner identity, repository access, signing context, network, cache, workspace cleanup, and job lifetime. Use a synthetic project to test boundaries and post-job cleanup.|Check concurrent jobs, persistent keychains, artifacts, device pairing, SSH access, and logs.|Do not connect to or alter a remote build host without explicit owner approval.|apple_codesign
macos-virtual-machine-snapshot-governance|macOS Virtual Machine Snapshot Governance|governing snapshot creation and rollback for a task-owned macOS test virtual machine|Identify the VM owner, snapshot provenance, intended test state, disposable clones, and recovery path before taking action. Record what a revert would discard.|Check linked clones, encryption, inherited credentials, test data, other task ownership, and snapshot age.|Do not revert, reset, delete, or clone a VM you do not own or that contains another task's state.|catalog
macos-virtual-machine-guest-host-evidence-check|macOS Virtual Machine Guest-Host Evidence Check|cross-checking a GUI test result inside a macOS VM with independent host-side evidence|Define the guest action, host observation, timestamp relationship, expected artifact, and privacy boundary. Confirm the VM identity and use separate evidence channels where authorized.|Check stale screenshots, guest clock skew, display scaling, inaccessible guest state, and mismatch between command result and visible outcome.|Do not use host-side control to bypass guest authentication, platform security, or user consent.|catalog
macos-screen-capture-consent-and-attribution-check|macOS Screen Capture Consent and Attribution Check|checking screen-recording permission and responsible-process attribution for a macOS automation test|Use a task-owned test app and account, request screen capture only after user authorization, and verify which signed process receives the permission state.|Check terminal or GUI launch chain, helper identity, TCC resets, captured windows, and screenshot retention.|Do not capture another person's screen, circumvent a permission prompt, or retain unrelated screen content.|apple_codesign
macos-crash-diagnostic-log-redaction|macOS Crash Diagnostic Log Redaction|redacting sensitive information from crash and diagnostic logs before sharing|Classify paths, usernames, bundle identifiers, request values, device identifiers, and embedded content. Produce a minimal excerpt with a reversible local redaction map only if approved.|Check crash arguments, environment variables, file paths, memory excerpts, URLs, and attached screenshots.|Do not send raw diagnostics to an external service or include secrets and personal data in a public issue.|apple_perf
"""


def parse_specs() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for line_number, line in enumerate(RAW.splitlines(), 1):
        if not line.strip():
            continue
        fields = line.split("|")
        if len(fields) != 7:
            raise ValueError(f"spec line {line_number}: expected 7 fields, got {len(fields)}")
        slug, title, focus, method, checks, guardrail, source = (item.strip() for item in fields)
        rows.append({"slug": slug, "title": title, "focus": focus, "method": method,
                     "checks": checks, "guardrail": guardrail, "source": source})
    return rows


def content_for(spec: dict[str, str]) -> tuple[str, str]:
    description = (
        f"Use when a task involves {spec['focus']}. Record Swift, Xcode, operating-system, build, and target versions; "
        "reproduction steps; data sensitivity; and the permission boundary before acting. Check current Apple or Swift "
        "documentation, preserve source and trace provenance, and verify on an owned test target. Do not change signing "
        "credentials, publish, notarize, or operate production systems without explicit approval."
    )
    source_name, source_url = SOURCES[spec["source"]]
    body = f'''# {spec['title']}

## When to Use
Use this skill when {spec['focus']}. It is a focused engineering workflow for an authorized Apple-platform codebase or test environment; it does not itself authorize access to devices, credentials, accounts, signing infrastructure, or production systems.

## Inputs and Boundaries
Record repository and source revision, Swift and Xcode versions, OS and SDK, target and build configuration, device or simulator, reproduction steps, expected behavior, data sensitivity, and the accountable owner. Identify whether the work is analysis, a local change, CI configuration, or a release-facing action. Use test accounts and synthetic fixtures when possible.

## Workflow
1. **Set the boundary.** State the technical question, affected target, intended output, source revision, environment, permission scope, and stop condition. Separate an engineering assessment from an authorized code or release change.
2. **Establish evidence.** Capture the relevant build settings, diagnostics, trace, test result, or signed artifact identity. Pin toolchain and target versions; redact credentials, user content, and private paths from shared artifacts.
3. **Apply the focused method.** {spec['method']}
4. **Verify a bounded result.** {spec['checks']} Compare against a reproducible baseline or an independent test when feasible; report what the evidence does and does not show.
5. **Hand off safely.** Record findings, versions, artifacts, uncertainties, remaining tests, and decision owner. Keep proposed changes separate from applied changes and preserve a recovery path.

## Apple-Platform Checks
- Verify the exact Swift compiler, language mode, SDK, OS, target, architecture, and build configuration when behavior depends on them.
- Distinguish source-level reasoning, static compiler checks, simulator behavior, physical-device measurements, and production observations.
- Treat traces, crash reports, test bundles, screenshots, archives, and symbols as potentially sensitive; minimize and redact before sharing.
- Recheck current Apple or Swift primary documentation for tool flags, platform requirements, entitlements, and distribution policy.

## Guardrails
{spec['guardrail']}
- Never expose signing keys, authentication tokens, private crash data, or user content in logs, prompts, or external services.
- Do not publish, notarize, submit, sign, install persistent helpers, change security permissions, or alter remote build infrastructure without explicit authorization from the owner.
- Do not bypass Gatekeeper, TCC, App Sandbox, code-signing validation, or user consent to make a test pass.
- Stop and ask when ownership, license, data handling, deployment target, or release authority is unclear.

## Acceptance
The result answers the stated engineering question, identifies source and tool versions, includes reproducible evidence and limitations, and names any required owner approval. It makes no unsupported claim of platform compatibility, security, performance, or release readiness.

## Topic Provenance
This skill is independently authored for this repository. The linked public catalog was used only as a topic-discovery seed; its root LICENSE was reviewed as MIT, but no upstream prose, code, commands, examples, prompts, scripts, or assets were copied. Some entries in that repository are symlinks or carry separate attributions, so no license permission is inferred for those targets. The linked Apple or Swift documentation is a version-sensitive reference, not a substitute for current project policy or independent testing.

Topic source: [steipete agent-scripts topic catalog](https://github.com/steipete/agent-scripts)
Technical reference: [{source_name}]({source_url})
'''
    return description, body


def tokens(value: str) -> set[str]:
    words = set(re.findall(r"[a-z0-9]+", value.casefold()))
    stop = {
        "and", "for", "with", "from", "into", "review", "audit", "analysis", "planning", "plan",
        "design", "assessment", "verification", "validation", "check", "checking", "workflow", "data",
        "model", "system", "systems", "skill", "use", "when", "task", "in", "of", "to", "the",
        "a", "an", "by", "on", "at", "as", "or", "against", "result", "reviewing", "security",
        "apple", "swift", "xcode", "macos", "ios", "app", "application", "performance", "code",
        "build", "test", "testing", "process", "boundary", "target", "version", "native", "platform",
    }
    return words - stop


def overlap_pairs(specs: list[dict[str, str]], names: list[str]) -> list[tuple[float, str, str]]:
    result: list[tuple[float, str, str]] = []
    candidate_tokens = [(s["slug"], tokens(s["slug"].replace("-", " ") + " " + s["focus"])) for s in specs]
    for i, (left, lt) in enumerate(candidate_tokens):
        for right, rt in candidate_tokens[i + 1:]:
            union = lt | rt
            score = len(lt & rt) / len(union) if union else 0.0
            if score >= 0.4:
                result.append((score, left, right))
        for old in names:
            ot = tokens(old.replace("-", " "))
            union = lt | ot
            score = len(lt & ot) / len(union) if union else 0.0
            if score >= 0.25:
                result.append((score, left, old))
    return sorted(result, reverse=True)


def preflight(specs: list[dict[str, str]]) -> tuple[str, str, list[str]]:
    if len(specs) != 100:
        raise ValueError(f"expected exactly 100 skills, got {len(specs)}")
    proposed = [item["slug"] for item in specs]
    if len(proposed) != len(set(proposed)):
        raise ValueError("duplicate proposed skill names")
    for spec in specs:
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", spec["slug"]):
            raise ValueError(f"invalid skill slug: {spec['slug']}")
        if spec["source"] not in SOURCES:
            raise ValueError(f"unknown source key: {spec['source']}")
    existing = {p.parent.name for p in SKILLS.rglob("SKILL.md")}
    collisions = sorted(set(proposed) & existing)
    occupied = sorted(name for name in proposed if skill_path(SKILLS, category_for_skill(name), name).exists())
    if collisions or occupied:
        raise FileExistsError(f"refusing to overwrite skills; exact={collisions}, occupied={occupied}")

    readme = README.read_text(encoding="utf-8")
    index = INDEX.read_text(encoding="utf-8")
    if readme.count(README_MARKER) != 1:
        raise ValueError("README catalog marker missing or ambiguous")
    if index.count(INDEX_MARKER) != 1:
        raise ValueError("INDEX router marker missing or ambiguous")
    readme_rows: list[str] = []
    index_rows: list[str] = []
    for spec in specs:
        description, body = content_for(spec)
        if len(description) > 1024 or len(description.split()) < 40:
            raise ValueError(f"{spec['slug']}: invalid description length")
        if not (400 <= len(body.encode("utf-8")) <= 60000):
            raise ValueError(f"{spec['slug']}: body size outside repository bounds")
        focus = spec["focus"][0].upper() + spec["focus"][1:]
        readme_rows.append(f"| [{spec['slug']}]({relative_skill_path(category_for_skill(spec['slug'], spec.get('focus', spec.get('trigger', ''))), spec['slug'], spec.get('focus', spec.get('trigger', '')))}) | {focus}. |")
        index_rows.append(f"| {focus} | [{spec['slug']}]({relative_skill_path(category_for_skill(spec['slug'], spec.get('focus', spec.get('trigger', ''))), spec['slug'], spec.get('focus', spec.get('trigger', '')))}) |")
    readme_updated = readme.rstrip() + "\n" + "\n".join(readme_rows) + "\n"
    index_updated = index.rstrip() + "\n" + "\n".join(index_rows) + "\n"
    return readme_updated, index_updated, proposed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="preflight only; do not write files")
    args = parser.parse_args()
    specs = parse_specs()
    readme_updated, index_updated, proposed = preflight(specs)
    existing = {p.parent.name for p in SKILLS.rglob("SKILL.md")}
    pairs = overlap_pairs(specs, sorted(existing))
    print(f"Preflight passed: {len(proposed)} candidates, no exact collisions; README/INDEX markers checked before writes.")
    if pairs:
        print("Potential conceptual neighbors for manual review:")
        for score, left, right in pairs[:100]:
            print(f"  {score:.2f}  {left} <> {right}")
    else:
        print("No high-similarity names or within-batch candidate pairs found.")
    if args.check:
        print("Check-only mode: no files changed.")
        return 0

    for spec in specs:
        description, body = content_for(spec)
        content = f"---\nname: {spec['slug']}\ndescription: {json.dumps(description, ensure_ascii=False)}\n---\n\n{body}"
        directory = skill_path(SKILLS, category_for_skill(spec["slug"], spec.get("focus", spec.get("trigger", ""))), spec["slug"], spec.get("focus", spec.get("trigger", "")))
        directory.mkdir(parents=True, exist_ok=False)
        (directory / "SKILL.md").write_text(content, encoding="utf-8")
    README.write_text(readme_updated, encoding="utf-8")
    INDEX.write_text(index_updated, encoding="utf-8")
    print(f"Created {len(specs)} original skills; total now {len(existing) + len(specs)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
