#!/usr/bin/env python3
"""Define and build 11 original 100-skill packs (batches 34–44).

Public URLs are read-only topic-discovery references. This builder never
imports upstream skill text, examples, prompts, code, or assets.
"""
from __future__ import annotations

import re

import build_1000_skills_batches14_23 as core


def s(slug: str, label: str, artifact: str, context: str, evidence: str, signal: str, measure: str) -> tuple[str, ...]:
    # The core renderer inserts the article: "for the {object}".
    artifact = re.sub(r"^(?:a|an|the)\s+", "", artifact, flags=re.IGNORECASE)
    return (slug, label, artifact, context, evidence, signal, measure)


BATCHES = {
    34: {
        "prefix": "agent-telemetry", "label": "agent-run observability and trace governance",
        "guard": "Instrument only approved metadata and task-visible outputs; do not capture hidden chain-of-thought, credentials, private user content, or full payloads when a minimized signal suffices. Follow the host's retention, privacy, and access rules. Traces support diagnosis and evaluation, not proof of model intent or permission to expand tool access. Keep user-impacting or externally applied actions separately authorized.",
        "sources": [("GitHub Copilot SDK", "https://github.com/github/copilot-sdk"), ("Agent thinking skills catalog", "https://github.com/accelerate-data/agent-thinking-skills"), ("Microsoft Agent Skills catalog", "https://github.com/MicrosoftDocs/Agent-Skills"), ("Neo4j Agent Memory", "https://github.com/neo4j-labs/agent-memory")],
        "streams": [
            s("session-lineage", "agent session lineage", "a run-lineage record", "session identity, parent-child runs, task version, host, and permitted data scope", "run identifiers, approved configuration versions, timestamps, and handoff references", "each run can be linked to its task and configuration without exposing user secrets", "orphan-run rate and lineage-field completeness"),
            s("tool-event-schema", "agent tool-event schemas", "a tool-event contract", "tool name, call state, result class, duration, and redaction-safe correlation fields", "documented host event fields, sanitized examples, and consumer requirements", "events distinguish requested, attempted, completed, failed, and unverified actions", "event-state coverage and malformed-record rate"),
            s("message-correlation", "agent message-to-tool correlation", "a correlation map", "user-visible turn, assistant response, tool invocation, result, and final claim linkage", "approved event metadata, response IDs, and a small redacted trace sample", "each cited action maps to the correct call and no result is attributed to a neighboring turn", "correlation coverage and ambiguous-link count"),
            s("routing-trace", "agent model and route tracing", "a route-selection evidence note", "declared model route, fallback, policy version, and observable task outcome", "approved routing logs, provider identifiers, configuration history, and task class", "route changes are attributable to a versioned event without inferring hidden reasoning", "route attribution and unclassified fallback rate"),
            s("retry-timeline", "agent retry and timeout timelines", "a retry timeline", "initial call, timeout boundary, retry count, backoff, fallback, and final state", "sanitized timestamps, configured limits, and result status codes", "the timeline matches the configured budget and repeated calls are not mistaken for independent success", "retry-limit compliance and unresolved timeout share"),
            s("stream-termination", "streamed-response termination evidence", "a partial-output state ledger", "stream start, chunks observed, termination cause, cancellation, and consumer visibility", "event sequence, client cancellation signal, transport status, and output boundary", "partial output is explicitly distinguished from a complete response or successful action", "termination-classification coverage and orphaned-stream count"),
            s("usage-metering", "agent usage and cost attribution", "a usage reconciliation sheet", "run scope, model or tool units, billing interval, retry attribution, and budget owner", "approved aggregate usage events, provider statement, and pricing version", "totals reconcile within documented precision and sensitive payloads are not needed for cost attribution", "unmatched usage and cost-per-completed-task coverage"),
            s("trace-redaction", "agent trace redaction and retention", "a trace data-minimization review", "field inventory, sensitive-data risk, retention class, access group, and deletion path", "sample sanitized records, approved retention policy, and trace access log", "unnecessary payload fields are removed or justified and retention matches policy", "sensitive-field exposure count and overdue-deletion rate"),
            s("replay-fixture", "agent trace replay fixtures", "a minimized replay fixture", "non-production trace slice, deterministic inputs, tool stubs, and expected state transitions", "redacted event sequence, fixture provenance, and current host contract", "the fixture reproduces the declared failure without replaying external side effects or private content", "reproduction rate and fixture-minimization ratio"),
            s("outcome-taxonomy", "agent run outcome classification", "an outcome taxonomy and sample audit", "task acceptance, tool completion, user-visible result, partial completion, and escalation state", "approved outcome rubric, redacted run sample, and evaluator adjudication", "classes are mutually understandable and separate model output from verified task completion", "label agreement and unclassified-outcome share"),
        ],
    },
    35: {
        "prefix": "backend-ops", "label": "backend service and API engineering operations",
        "guard": "Use local test or staging evidence and preserve the current service contract. Do not apply production migrations, rotate credentials, publish endpoints, send customer traffic, or alter records without the service owner's authorization and a recovery plan. Verify framework and runtime versions against the project lockfiles and current official documentation. Keep authorization, privacy, and data-retention decisions with responsible owners.",
        "sources": [("Backend Pro Max Skill", "https://github.com/egeolta/Backend-Pro-Max-Skill"), ("Backend Pro Max topic catalog", "https://github.com/shashankswe2020-ux/backend-pro-max-skill"), ("Angular skills", "https://github.com/angular/skills"), ("Go coding skills", "https://github.com/samber/cc-skills-golang"), ("Rust agentic skills", "https://github.com/udapy/rust-agentic-skills")],
        "streams": [
            s("api-contract", "API contract evolution", "an API compatibility matrix", "request and response shapes, optionality, error classes, and consumer versions", "versioned schemas, consumer inventory, golden fixtures, and deprecation policy", "known consumers retain a supported path and breaking differences are explicit", "consumer coverage and unclassified breaking-change count"),
            s("authorization-boundary", "backend authorization boundaries", "an authorization decision table", "principal, resource, action, tenant, and policy decision across service endpoints", "route map, role definitions, authorization middleware, and approved test identities", "allow and deny cases are tested at each boundary without using real customer credentials", "endpoint coverage and unexpected-allow count"),
            s("idempotent-jobs", "idempotent background-job processing", "a replay-safety test plan", "job key, enqueue duplication, partial failure, retry, and completion record", "queue contract, handler behavior, test fixture, and transaction boundary", "duplicate delivery does not duplicate the declared side effect in an isolated test", "duplicate-side-effect rate and replay-case coverage"),
            s("pool-saturation", "backend connection pool saturation behavior", "a connection-pool saturation profile", "pool lease duration, queue wait, maximum connections, transaction scope, and dependency latency", "staging metrics, pool configuration, synthetic request load, and downstream response timing", "queue growth is visible before saturation and the test remains isolated from production", "pool-wait distribution and unbounded-queue count"),
            s("pagination-semantics", "API pagination and filtering semantics", "a pagination contract worksheet", "stable ordering, cursor scope, filter composition, and concurrent updates", "endpoint schema, representative fixtures, and documented ordering guarantees", "page boundaries neither skip nor duplicate stable test records under declared assumptions", "boundary-case coverage and duplicate-or-gap count"),
            s("event-delivery", "backend event delivery contracts", "an event-delivery acceptance matrix", "event identity, ordering, schema version, acknowledgement, and consumer retry", "event schema registry, producer behavior, consumer contract, and replay fixture", "delivery guarantees and compatibility assumptions are explicit and testable", "schema compatibility and unhandled-event rate"),
            s("cache-consistency", "service cache consistency behavior", "a cache invalidation test record", "source-of-truth update, cache key, stale window, invalidation event, and fallback", "cache configuration, update path, isolated test data, and observed TTL", "the measured stale interval stays within the approved contract or remains a documented risk", "staleness-window distribution and invalidation coverage"),
            s("error-retry-contract", "backend error and retry contracts", "an error-handling behavior table", "error class, retryability, retry owner, backoff, timeout, and client-visible response", "API error schema, dependency failure fixtures, and configured retry policy", "retryable and terminal cases produce bounded behavior without duplicate side effects", "retry-budget compliance and error-class coverage"),
            s("observability-redaction", "backend observability and log redaction", "a log-field review matrix", "request correlation, error context, personal data, credentials, and retention fields", "structured log schema, redaction configuration, and sampled test events", "diagnostic fields remain useful while restricted values are absent from the approved sample", "sensitive-value leakage count and correlation coverage"),
            s("release-compatibility", "backend release compatibility", "a staged-release evidence packet", "runtime version, database state, API compatibility, dependency health, and rollback point", "build manifest, migration plan, consumer matrix, staging checks, and owner approvals", "the release candidate meets predeclared gates and no live rollout is triggered by this workflow", "gate coverage and unresolved compatibility count"),
        ],
    },
    36: {
        "prefix": "container-assurance", "label": "container artifact provenance and runtime assurance",
        "guard": "Treat container artifacts, registries, attestations, and runtime policy as security-sensitive. Work from read-only metadata or isolated test environments; do not push images, mutate tags, change runtime privileges, scan unauthorized targets, or deploy without explicit owner approval. Bind every conclusion to an immutable digest, platform, tool version, and source date. Follow the organization's current trust and vulnerability-response policy.",
        "sources": [("Docker skills catalog", "https://github.com/docker/skills"), ("GitHub Agentic Workflows", "https://github.com/github/gh-aw"), ("GitHub Actions firewall", "https://github.com/github/gh-aw-firewall")],
        "streams": [
            s("base-digest", "container base-image identity", "a base-image provenance ledger", "base-image reference, resolved digest, platform, publisher, and update window", "build manifest, registry metadata, digest resolution, and approved source policy", "the tested base image is pinned and attributable without relying on a mutable tag", "digest pinning and provenance-field coverage"),
            s("build-inputs", "container build-input provenance", "a build-input manifest review", "build context, recipe version, dependency locks, builder identity, and external inputs", "version-controlled recipe, lockfiles, build arguments, and approved build record", "the manifest captures material inputs and unexplained network-fetched inputs are flagged", "input traceability and undeclared-input count"),
            s("context-secret", "container build-context secret exposure", "a build-context exclusion report", "included paths, ignored files, secret patterns, build layers, and diagnostic output", "test-only sample context, ignore rules, build metadata, and secret-scanning result", "test credentials and sensitive files are excluded from the context and layers", "sensitive-file match count and exclusion-test coverage"),
            s("sbom-subject", "container SBOM subject binding", "an SBOM-to-image binding record", "SBOM document identity, subject digest, platform manifest, and package scope", "SBOM metadata, image digest, manifest list, and reproducible package inventory", "the SBOM subject matches the exact image digest and platform under review", "subject-match rate and unaccounted package count"),
            s("attestation-binding", "container attestation subject binding", "an attestation verification worksheet", "attestation issuer, predicate type, subject digest, signer identity, and verification policy", "attestation metadata, signature result, trust-root version, and artifact digest", "the statement verifies against the exact artifact and expected policy, without treating signature presence alone as trust", "verified-subject coverage and policy-exception count"),
            s("platform-parity", "multi-platform image parity", "a platform manifest comparison", "architecture-specific digests, package sets, entrypoints, and runtime behavior", "manifest list, platform builds, package inventories, and isolated smoke-test results", "each declared platform resolves to the intended artifact and differences are explained", "platform coverage and unexplained-difference count"),
            s("registry-immutability", "container registry tag and retention controls", "a registry mutation-risk review", "tag mutability, digest retention, deletion permissions, and promotion history", "read-only registry policy, tag history, retention configuration, and access roles", "critical releases remain retrievable by digest and write authority is clearly bounded", "mutable-release-tag count and retention-policy coverage"),
            s("runtime-capability", "container runtime capability drift", "a runtime privilege comparison", "effective user, capabilities, namespaces, mounts, seccomp, and read-only paths", "approved runtime manifest, observed test configuration, and policy baseline", "the test runtime does not exceed approved privileges and deviations are owner-routed", "privilege-delta count and baseline coverage"),
            s("sandbox-egress", "container sandbox network egress", "a sandbox egress evidence sheet", "allowed destinations, DNS behavior, proxy path, secret injection, and denied requests", "isolated test environment, egress policy snapshot, and sanitized network observations", "only declared destinations are reachable in the test and credentials do not leak through denied paths", "unexpected-egress count and policy-test coverage"),
            s("promotion-chain", "container artifact promotion and rollback", "an image-promotion chain record", "source digest, environment promotion, approval state, deployed digest, and rollback reference", "signed build record, promotion metadata, deployment inventory, and recovery plan", "each environment references the approved immutable digest and rollback remains a reviewed proposal", "digest continuity and recovery-reference completeness"),
        ],
    },
    37: {
        "prefix": "ml-data-ops", "label": "tabular machine-learning data and experiment quality",
        "guard": "Use approved, minimized, or synthetic data and preserve the original source snapshot. Treat model metrics as evidence about a declared sample, not a guarantee or decision rule. Do not make high-impact eligibility, medical, employment, credit, or other individual determinations. Record split, feature, and evaluation versions; route threshold and deployment decisions to accountable reviewers.",
        "sources": [("Data analytics and machine-learning catalog", "https://github.com/jpcain/data-analytics-machine-learning"), ("Typesafe AI skills", "https://github.com/typesafe-ai/skills"), ("Scientific agent skills", "https://github.com/K-Dense-AI/scientific-agent-skills")],
        "streams": [
            s("snapshot-lineage", "tabular dataset snapshot lineage", "a dataset-to-run lineage card", "source system, extraction window, snapshot identity, schema version, and permitted use", "approved extract manifest, checksum, schema, and access record", "the analysis points to a reproducible snapshot and unapproved fields are excluded", "snapshot reproducibility and schema-drift coverage"),
            s("target-quality", "target-label definition quality", "a target-label specification", "label meaning, observation window, censoring, missingness, and adjudication rule", "approved data dictionary, sampling notes, and representative de-identified rows", "the target can be assigned consistently and ambiguous cases remain unresolved", "label agreement and missing-target rate"),
            s("split-leakage", "train-validation-test split integrity", "a split-integrity audit", "entity grouping, time boundary, duplicate records, leakage paths, and split seed", "split code/configuration, entity keys, time fields, and duplicate-check output", "no prohibited entity or future information crosses the declared evaluation boundary", "overlap rate and temporal-leakage check coverage"),
            s("feature-parity", "feature transformation parity", "a feature-pipeline parity report", "training and inference transforms, null behavior, category handling, and units", "versioned transform definitions, fixtures, schema, and local inference output", "the same approved fixture produces equivalent features across intended paths", "feature-parity rate and unknown-category count"),
            s("baseline-comparison", "model baseline comparison", "a baseline comparison table", "target, split, metric, uncertainty, naive baseline, and model family", "frozen evaluation set, baseline definition, metric code, and run metadata", "the model is compared to an appropriate baseline on the same data and metric", "baseline lift interval and run-to-run reproducibility"),
            s("metric-uncertainty", "model metric uncertainty reporting", "a metric uncertainty worksheet", "sampling unit, metric denominator, confidence method, and subgroup size", "evaluation predictions, label version, metric implementation, and sampling assumptions", "uncertainty and small-sample limits accompany every reported point estimate", "interval coverage and denominator traceability"),
            s("subgroup-coverage", "subgroup evaluation coverage", "a subgroup coverage matrix", "approved subgroup dimensions, missingness, sample support, and privacy thresholds", "review-approved subgroup definitions, aggregate test results, and minimum-cell policy", "unsupported or too-small groups are marked unknown rather than inferred", "dimension coverage and suppressed-cell count"),
            s("calibration-review", "prediction calibration review", "a calibration evidence brief", "score range, calibration set, time period, reliability bins, and threshold owner", "held-out predictions, calibration method, source version, and calibration plot values", "calibration claims are bounded to the evaluation sample and no threshold is auto-applied", "calibration error and sample-support coverage"),
            s("drift-monitoring", "tabular model input-drift monitoring", "a drift-monitor definition", "feature reference window, current window, missingness, schema change, and alert owner", "approved aggregate feature summaries, reference snapshot, and monitoring policy", "alerts distinguish data-contract breaks from population movement and have an owner", "feature coverage and alert-review latency"),
            s("experiment-reproduction", "model experiment reproduction", "an experiment reproduction packet", "code revision, environment, data snapshot, seed, metric implementation, and run state", "versioned configuration, dependency lock, approved data reference, and output manifest", "the run can be reproduced within declared tolerance or every variance is recorded", "reproduction tolerance and metadata completeness"),
        ],
    },
    38: {
        "prefix": "growth-evidence", "label": "marketing evidence and customer-growth measurement",
        "guard": "Keep customer data minimized and follow consent, opt-out, brand, and jurisdictional rules. Do not publish copy, launch campaigns, alter budgets, contact customers, or change live site behavior without explicit approval. Separate observed customer evidence from hypotheses; substantiate measurable claims and avoid manipulative, discriminatory, or misleading targeting.",
        "sources": [("Marketing skills catalog", "https://github.com/coreyhaines31/marketingskills"), ("Awesome agent skills catalog", "https://github.com/VoltAgent/awesome-agent-skills"), ("Agentic skills catalog", "https://github.com/sickn33/agentic-awesome-skills")],
        "streams": [
            s("problem-evidence", "customer problem evidence", "a problem-evidence map", "customer segment, observed friction, evidence channel, recency, and counterexample", "consented interview notes, support themes, survey definitions, and public product feedback", "each problem statement traces to multiple evidence types or is labeled as a hypothesis", "claim traceability and recency coverage"),
            s("positioning-claims", "marketing positioning and claim substantiation", "a positioning claim matrix", "audience, differentiator, proof point, limitation, and intended channel", "approved product facts, current customer permission, and dated competitive references", "each external claim has current evidence and unsupported comparisons are removed from draft", "claim-to-source coverage and expired-proof count"),
            s("campaign-experiment", "campaign experiment economics", "a campaign test design", "assignment unit, exposure, outcome window, cost boundary, and stopping rule", "approved audience definition, baseline period, event schema, and experiment owner", "primary outcome and guardrails are defined before launch and no campaign is activated", "metric completeness and assignment integrity"),
            s("landing-measurement", "landing-page measurement design", "a landing-page event map", "page variants, entry source, conversion event, consent state, and bot filtering", "approved page brief, analytics schema, tag inventory, and test events", "events distinguish actual user actions from page loads and consent state is respected", "event-definition coverage and test-event parity"),
            s("seo-decay", "search-content decay diagnosis", "a content-decay evidence brief", "query cohort, landing page, dated performance window, intent, and content change history", "approved search analytics export, canonical URL map, and revision log", "declines are compared across equivalent windows and causes are presented as hypotheses", "query/page coverage and freshness of evidence"),
            s("lifecycle-segmentation", "lifecycle campaign segmentation rules", "a lifecycle segment specification", "entry criteria, exclusion, consent, suppression, exit, and frequency cap", "approved event definitions, consent source, suppression policy, and test profiles", "test records enter or exit for explainable reasons and no message is sent", "rule-case coverage and suppressed-test count"),
            s("attribution-window", "marketing attribution window integrity", "an attribution-window sensitivity table", "touchpoint identity, conversion window, duplicate handling, channel cost, and attribution limits", "versioned event data, approved attribution definition, and comparable spend period", "results are reproducible under the declared model and are not presented as causal proof", "unattributed share and window sensitivity"),
            s("referral-source", "referral and partner-source quality", "a referral-source reconciliation", "partner identity, landing tag, duplicate lead, consent, and downstream outcome", "approved partner register, tracking taxonomy, and minimized CRM extract", "source assignments reconcile to the taxonomy and missing values remain visible", "source completeness and duplicate-attribution rate"),
            s("brand-asset-approval", "brand asset approval evidence", "a brand asset review packet", "asset version, placement, audience, rights, required disclosure, and approval owner", "approved brand guide, usage permission, product claim sources, and target-channel specification", "the proposed asset has rights and factual sign-off before any publication step", "approval coverage and unresolved-rights count"),
            s("incrementality-readout", "campaign incrementality readout", "an incrementality evidence brief", "holdout design, exposure contamination, conversion window, seasonality, and cost basis", "predeclared experiment, privacy-approved aggregate outcomes, and matching spend records", "causal language matches the design and limitations are explicit", "holdout separation and cost-per-incremental-outcome interval"),
        ],
    },
    39: {
        "prefix": "omics-data", "label": "omics data quality and reproducibility",
        "guard": "Support research data stewardship and reproducibility, not clinical interpretation or patient care. Use approved coded datasets, preserve consent and data-use limits, and avoid exposing direct identifiers. Keep observed measurements separate from biological inference; do not call a sample, variant, pathway, or model clinically actionable. Verify reference assemblies, software versions, and deposition terms with the study owner.",
        "sources": [("BioSkills topic catalog", "https://github.com/GPTomics/bioSkills"), ("Awesome bio-agent skills", "https://github.com/BioTender-max/awesome-bio-agent-skills"), ("Medical research skills catalog", "https://github.com/aipoch/medical-research-skills"), ("Scientific agent skills catalog", "https://github.com/K-Dense-AI/scientific-agent-skills")],
        "streams": [
            s("sample-sheet", "omics sample-sheet integrity", "a sample-sheet reconciliation", "coded sample identity, assay batch, condition, replicate, and inclusion status", "approved sample manifest, instrument export, consent scope, and de-identified metadata", "each analyzed file maps to one approved coded sample and conflicts are not guessed", "sample-to-file match rate and unresolved identifier count"),
            s("reference-provenance", "genome and transcript reference provenance", "a reference-build provenance card", "assembly, annotation release, transcript set, coordinate convention, and retrieval date", "reference accession, checksums, pipeline configuration, and local cache identity", "all downstream coordinates identify the exact reference and annotation versions", "reference-field completeness and checksum match"),
            s("contrast-design", "RNA-sequencing contrast design", "a contrast and covariate review", "experimental unit, contrast direction, batch covariate, repeated measures, and confounding", "approved study design, coded sample sheet, model matrix, and analysis question", "the contrast is estimable under the recorded design or the limitation is explicit", "design-matrix rank and covariate-conflict count"),
            s("single-cell-qc", "single-cell assay QC provenance", "a single-cell QC parameter ledger", "filter definitions, ambient signal, doublet method, batch, and retained-cell rationale", "versioned count matrix, method versions, thresholds, and blinded sample metadata", "every exclusion rule is reproducible and no threshold is presented as universal", "parameter traceability and retained-cell reconciliation"),
            s("multiomics-join", "multi-omics sample-link validation", "a cross-assay join audit", "coded subject key, assay timepoint, biological replicate, missing modality, and duplicate mapping", "approved crosswalk, assay manifests, and de-identified timepoint records", "joins preserve the intended experimental unit and ambiguous matches remain unjoined", "cross-assay match coverage and ambiguous-link count"),
            s("proteomics-search-space", "proteomics search-space provenance", "a search-space configuration record", "protein database release, contaminant set, decoy strategy, enzyme rule, and mass tolerance", "database checksums, analysis configuration, instrument method, and software version", "the search can be reproduced against the exact database and parameter set", "search-parameter completeness and database checksum match"),
            s("metagenomic-controls", "metagenomic negative-control interpretation", "a control-aware contamination review", "blank controls, batch co-occurrence, reagent background, and classification confidence", "coded sample/control manifest, pipeline version, negative-control results, and taxonomy release", "candidate contamination is reported with evidence and uncertainty, not silently removed", "control coverage and unreviewed candidate count"),
            s("enrichment-universe", "functional enrichment universe selection", "an enrichment-universe audit", "tested-gene universe, identifier mapping, multiple testing, and background selection", "analysis code, annotation version, input list, tested universe, and correction method", "the background matches the actual assay universe and every filter is documented", "identifier mapping rate and universe traceability"),
            s("batch-effect", "omics batch-effect identifiability", "a batch-confounding diagnostic", "batch, condition, site, operator, and run-order overlap in the study design", "coded sample matrix, run logs, covariate table, and planned comparison", "confounded effects are reported as non-identifiable rather than corrected by assumption", "design overlap and estimable-contrast coverage"),
            s("deposit-package", "omics public-deposition package readiness", "a deposition completeness manifest", "accession fields, controlled metadata, file checksums, consent restrictions, and embargo state", "repository instructions, data dictionary, approved coded metadata, and export checksums", "required files and metadata reconcile without disclosing restricted information", "submission-field coverage and checksum match rate"),
        ],
    },
    40: {
        "prefix": "pcb-design", "label": "PCB design evidence and fabrication readiness",
        "guard": "Treat outputs as engineering review support, not electrical safety certification or manufacturing approval. Work from the controlled schematic, board revision, fabrication rules, and vendor capability documents. Do not release files to a fabricator, order components, energize hardware, or override design-rule warnings without an authorized engineer's review. Keep assumptions, units, stackup, and revision identity explicit.",
        "sources": [("KiCad Happy design workflow catalog", "https://github.com/aklofas/kicad-happy"), ("SKiDL skill catalog", "https://github.com/nickkraakman/skidl-skills"), ("PCB design skill catalog", "https://github.com/daishuge/pcb-skill"), ("JLCPCB skill MCP", "https://github.com/hulryung/jlcpcb-skill-mcp"), ("PCB Agent Teams topic catalog", "https://github.com/Zane456/PCB-Agent-Teams")],
        "streams": [
            s("netlist-intent", "schematic and netlist intent", "a netlist-to-intent comparison", "signal identity, power nets, connector pinout, hierarchy, and revision", "controlled schematic export, netlist, connector definitions, and review comments", "critical nets and pins match the approved design intent or remain flagged", "net-to-intent coverage and unexplained connectivity count"),
            s("footprint-geometry", "PCB footprint geometry review", "a footprint geometry check sheet", "pad numbering, courtyard, pitch, polarity, pin-one marker, and package drawing revision", "library footprint, datasheet mechanical drawing, and manufacturing land-pattern constraints", "footprint identity and geometry are traceable to the chosen component package", "pad-number match and unverified-package count"),
            s("library-symbol-map", "component symbol and footprint mapping", "a library mapping manifest", "symbol pins, package pins, units, hidden power pins, and alternate device variants", "versioned symbol, footprint, part datasheet, and exported netlist", "the mapping is consistent across symbol, package, and schematic netlist", "pin-mapping coverage and unmatched-pin count"),
            s("stackup-constraint", "PCB stackup and impedance constraint provenance", "a stackup constraint register", "layer order, dielectric data, copper weight, controlled nets, and fabrication revision", "fabricator stackup offer, approved impedance targets, board constraints, and material notes", "every controlled constraint has a source and current board revision", "constraint-source coverage and unresolved stackup count"),
            s("placement-keepout", "PCB placement and keepout review", "a placement constraint map", "mechanical envelope, connector access, assembly clearance, thermal zones, and keepouts", "board outline, enclosure drawing, component datasheets, and placement constraints", "each exception is measured against the controlling drawing and left for engineer disposition", "constraint coverage and clearance-exception count"),
            s("return-path", "PCB return-path continuity review", "a return-path review ledger", "reference plane, plane splits, high-speed transition, via return, and connector boundary", "stackup, net classes, layout snapshots, and approved interface constraints", "review notes identify evidence-backed discontinuities without asserting unmeasured signal integrity", "critical-transition coverage and unresolved return-path exceptions"),
            s("rule-exception", "PCB design-rule exception governance", "a rule-exception disposition list", "rule identifier, affected nets, board region, waiver rationale, and expiration", "versioned DRC/ERC output, rule set, schematic revision, and owner approval record", "each exception is tied to the current revision and no warning is suppressed without approval", "exception-owner coverage and expired-waiver count"),
            s("fabrication-export", "PCB fabrication export verification", "a fabrication-output manifest", "Gerber or ODB layer map, drill file, board outline, units, and revision label", "controlled board export, layer map, viewer inspection, and fabrication checklist", "each output opens in a read-only viewer and matches the declared revision and layer purpose", "output-file coverage and layer-map mismatch count"),
            s("bom-alternate", "PCB bill-of-material alternate review", "a component substitution comparison", "manufacturer part number, package, electrical limits, lifecycle, stock source, and approval state", "controlled BOM, authorized datasheet, lifecycle notice, and approved sourcing source", "candidate alternates are compared against explicit requirements and remain unapproved proposals", "required-attribute coverage and unsupported-alternate count"),
            s("assembly-test", "PCB assembly and test readiness", "an assembly and test handoff packet", "assembly drawing, polarity markings, test points, programming interface, and bring-up boundary", "released-intent draft, assembly outputs, test plan, and authorized low-voltage lab controls", "the handoff identifies unresolved safety and test dependencies before any energization", "handoff-field coverage and unresolved safety dependency count"),
        ],
    },
    41: {
        "prefix": "edge-fleet", "label": "connected-device and edge-fleet lifecycle operations",
        "guard": "Use lab, staged, or read-only fleet evidence and follow device-owner safety and privacy requirements. Do not provision credentials, push firmware, change device configuration, disable controls, or remotely actuate equipment without explicit authorization and a tested recovery path. Minimize telemetry and location data, validate hardware revision, and keep field changes with qualified operators.",
        "sources": [("EasyAIoT device and edge workflow catalog", "https://gitee.com/volara/easyaiot"), ("BouffaloLab agent skills", "https://github.com/bouffalolab/bouffalolab-skills"), ("TinyLab Linux Lab", "https://gitee.com/tinylab/linux-lab")],
        "streams": [
            s("identity-onboarding", "edge-device identity onboarding", "a device identity enrollment checklist", "hardware identity, ownership, site assignment, credential class, and onboarding approval", "approved device inventory, attestation result, non-production test identity, and owner roster", "each enrolled device maps to an owner and least-privilege identity without exposing secrets", "inventory match rate and orphan-identity count"),
            s("firmware-cohort", "firmware cohort planning", "a firmware cohort evidence plan", "hardware revision, firmware version, compatibility, canary size, and rollback condition", "vendor release notes, device matrix, staged test logs, and owner-approved rollout criteria", "the proposed cohort excludes incompatible hardware and remains a plan until approved", "compatibility coverage and rollback-readiness status"),
            s("telemetry-minimization", "edge telemetry minimization", "a telemetry field and retention map", "sensor fields, location detail, sampling frequency, purpose, access group, and retention", "data dictionary, privacy policy, representative minimized payload, and storage settings", "each field has a documented purpose and unnecessary precision or retention is removed from draft", "purpose coverage and unneeded-field count"),
            s("offline-replay", "intermittent-connectivity replay integrity", "an offline replay test record", "local queue order, event identity, expiry, reconnect duplication, and conflict behavior", "synthetic edge events, queue policy, sync logs, and isolated test server", "reconnect replay preserves event identity and surfaces conflicts instead of silently overwriting", "duplicate-event rate and unresolved-conflict count"),
            s("ota-recovery", "edge update recovery readiness", "an update recovery drill record", "signed package identity, interrupted transfer, power loss, fallback image, and recovery owner", "test package digest, lab device, update state log, and approved recovery procedure", "the staged device returns to a known test state without contacting live fleet endpoints", "recovery success rate and untested-state count"),
            s("sensor-calibration", "edge sensor calibration provenance", "a sensor calibration lineage record", "sensor model, calibration date, environmental range, coefficient version, and field replacement", "calibration certificate, device metadata, sample readings, and approved tolerance", "a reading can be tied to sensor and calibration state or is marked unsuitable for comparison", "calibration metadata coverage and expired-certificate count"),
            s("gateway-translation", "edge gateway protocol translation", "a protocol mapping contract", "source field, destination field, units, timestamp basis, quality flag, and error path", "versioned mapping, synthetic messages, protocol specification, and gateway logs", "representative messages preserve value meaning and conversion exceptions are visible", "field mapping coverage and round-trip mismatch count"),
            s("fleet-alerts", "edge fleet alert aggregation", "a fleet alert quality review", "device cohort, alert key, duplicate burst, severity source, and operator escalation", "sanitized event summaries, current alert rule, fleet inventory, and escalation roster", "repeated symptoms group without hiding distinct device failures and an operator owns each escalation", "duplicate-alert reduction and unassigned-alert rate"),
            s("low-power-regression", "edge low-power behavior regression", "a low-power behavior test matrix", "sleep state, wake source, expected duty cycle, battery assumption, and firmware revision", "lab measurement, approved test fixture, current firmware build, and documented wake behavior", "tests compare equivalent conditions and do not change deployed power controls", "test-condition coverage and unexplained wake count"),
            s("decommissioning", "edge-device decommissioning evidence", "a device retirement checklist", "ownership transfer, credential revocation, data disposition, asset status, and remote-access removal", "approved retirement request, asset record, access review, and retention policy", "retired status is not claimed until access, data, and custody evidence reconcile", "retirement-step coverage and unresolved access count"),
        ],
    },
    42: {
        "prefix": "blender-production", "label": "Blender asset and scene production workflows",
        "guard": "Treat the workflow as a production-review aid; do not modify or publish a project without the owner's approval. Preserve source assets and version identity, and verify Blender, renderer, add-on, and color-management versions before applying version-sensitive steps. Respect model, texture, font, and reference-image licenses; do not infer rights from a public download link. Report visual uncertainty rather than hiding artifacts.",
        "sources": [("Blender skills by Arjun988", "https://github.com/arjun988/blender-skills"), ("Blender skills by Kevin Badi", "https://github.com/kevinbadi/blender-skills"), ("Blender skills by RobLe3", "https://github.com/roble3/cc-blender-skill"), ("Blender MCP project", "https://projects.blender.org/lab/blender_mcp"), ("Blender 3D skill listing", "https://smithery.ai/skills/pacphi/blender-3d")],
        "streams": [
            s("asset-requirements", "Blender asset requirements", "an asset acceptance card", "intended use, scale, units, polygon budget, output formats, and downstream consumers", "approved brief, target engine or renderer constraints, and reference asset list", "every acceptance criterion has a measurable check or named visual reviewer", "requirement coverage and unresolved-target count"),
            s("mesh-integrity", "mesh topology and geometry integrity", "a mesh integrity report", "nonmanifold regions, normals, duplicate geometry, scale, and intended deformation", "project revision, read-only mesh diagnostics, and target-use constraints", "geometry exceptions are localized and no repair is silently applied to the source", "issue count by severity and reviewed-object coverage"),
            s("material-provenance", "material and texture provenance", "a material-to-source register", "shader inputs, image paths, color-space tags, license, and texture resolution", "project links, source licenses, image metadata, and renderer requirements", "each external asset has a source and rights status and all paths resolve in the test copy", "asset provenance coverage and broken-path count"),
            s("rig-continuity", "rigging and animation continuity", "a rig-and-motion review sheet", "control hierarchy, deformation zones, frame range, interpolation, and contact constraints", "approved rig version, test pose set, animation range, and evaluation frames", "named poses and motion checkpoints meet the brief or remain flagged for an animator", "pose coverage and unexplained deformation count"),
            s("camera-coverage", "camera and composition coverage", "a shot-coverage board", "camera identity, lens, framing, screen direction, focal target, and shot transition", "approved storyboard, camera markers, sequence frames, and delivery aspect ratios", "required beats are covered and major framing changes are reviewable", "beat coverage and aspect-ratio exceptions"),
            s("lighting-color", "Blender lighting and color pipeline", "a lighting and display transform record", "scene exposure, light contribution, view transform, output encoding, and target display", "versioned scene settings, reference chart, render sample, and delivery color specification", "test renders are comparable under the declared transform and assumptions are recorded", "settings completeness and reference-sample deviation"),
            s("simulation-cache", "simulation cache determinism", "a simulation cache validation record", "simulation settings, frame range, cache location, dependency version, and repeat-run behavior", "duplicate test project, cache manifest, seed values, and two isolated render samples", "the declared frames reproduce within the approved tolerance without overwriting the source cache", "frame-match rate and cache dependency coverage"),
            s("node-dependencies", "geometry-node dependency integrity", "a node-group dependency manifest", "node groups, linked libraries, external assets, version requirements, and fallback state", "project dependency graph, linked file metadata, and target Blender version", "required dependencies resolve in a clean test copy and version limits are explicit", "dependency resolution rate and unknown-version count"),
            s("render-budget", "Blender render budget and output sampling", "a render-budget comparison", "resolution, sample settings, denoising, memory use, renderer, and deadline", "approved target settings, representative scenes, timing samples, and machine constraints", "quality and time trade-offs are stated and no production render is launched automatically", "render-time range and sample-frame coverage"),
            s("project-handoff", "Blender project handoff and reopenability", "a project handoff manifest", "blend file revision, linked libraries, packed assets, fonts, add-ons, and render outputs", "project copy, dependency scan, owner-approved package list, and reopen test", "a clean environment can reopen the handoff copy with required assets resolved", "dependency coverage and clean-reopen pass rate"),
        ],
    },
    43: {
        "prefix": "premiere-production", "label": "Adobe Premiere Pro project and postproduction operations",
        "guard": "Treat all steps as project QA and handoff support; do not overwrite source media, alter a shared production, publish a cut, or change delivery destinations without authorization. Confirm Premiere Pro, plug-in, codec, and operating-system versions for version-sensitive behavior. Preserve media rights, client confidentiality, and exact project/sequence identity; do not claim a rendered file is correct until its technical and editorial checks pass.",
        "sources": [("Premiere AI skills catalog", "https://github.com/stefanwebb/premiere-ai-skills"), ("Premiere AI workflows", "https://github.com/stefanwebb/premiere-ai"), ("Premiere CLI topic catalog", "https://github.com/stefanwebb/premiere-cli"), ("Premiere Pro MCP catalog", "https://github.com/hetpatel-11/Adobe_Premiere_Pro_MCP")],
        "streams": [
            s("media-ingest", "Premiere media ingest integrity", "a media-ingest manifest", "source identity, checksum, frame rate, audio channels, duration, and copy destination", "approved media list, file metadata, checksums, and ingest folder snapshot", "every listed source has a verified copy and metadata matches the intended project", "checksum coverage and unmatched-source count"),
            s("proxy-pairing", "proxy and original-media pairing", "a proxy-to-original mapping", "source clip identity, proxy codec, frame dimensions, timecode, audio layout, and relink state", "project metadata, proxy filenames, clip properties, and test relink in a copy", "each proxy resolves to the intended original and no source media is replaced", "pairing coverage and ambiguous-match count"),
            s("relink-recovery", "Premiere media relink recovery", "a media-path recovery plan", "missing media path, volume change, filename collision, folder map, and relink boundary", "read-only project inventory, storage migration map, and duplicate-name report", "every proposed match has a unique identity signal and ambiguous paths are left unresolved", "relink candidate precision and unresolved-path count"),
            s("sequence-contract", "Premiere sequence technical contract", "a sequence-property comparison", "frame rate, frame size, pixel aspect, field order, audio rate, and intended delivery", "approved delivery brief, sequence settings, source properties, and export target", "sequence properties match the intended timeline and deviations are documented", "property coverage and unexplained-mismatch count"),
            s("multicam-mapping", "Premiere multicamera source mapping", "a multicamera angle map", "camera identity, angle label, source timecode, audio reference, and synchronization basis", "approved camera log, clip metadata, multicamera sequence copy, and sync reference", "each angle maps to the correct source and the reference basis is explicit", "angle coverage and unlabeled-source count"),
            s("dynamic-link", "Premiere Dynamic Link round-trip integrity", "a linked-composition round-trip record", "source project identity, composition revision, linked clip state, frame range, and render fallback", "project copies, composition metadata, version matrix, and representative frame comparison", "the round trip preserves the intended frame range or the known difference is escalated", "linked-composition coverage and frame-difference count"),
            s("caption-package", "Premiere caption package readiness", "a caption track and sidecar manifest", "caption language, track identity, timing basis, speaker labels, and delivery format", "approved transcript version, sequence timebase, export settings, and sample frame review", "caption assets align to the declared sequence and unverified wording remains flagged", "caption-timing sample coverage and language-label completeness"),
            s("collaboration-state", "Premiere collaboration and project ownership", "a shared-project state ledger", "project owner, active editor, lock state, shared storage, and conflict recovery copy", "approved collaboration roster, project metadata, storage status, and change log", "concurrent edits have a traceable owner and conflicts are preserved for review", "owner assignment and unresolved-lock count"),
            s("package-completeness", "Premiere project package completeness", "a project dependency inventory", "project file, linked audio/video, graphics, fonts, plug-ins, LUTs, and licensing notes", "project copy, dependency scan, asset permission records, and target workstation profile", "required dependencies resolve in a clean test package or are listed as a handoff limitation", "dependency coverage and missing-file count"),
            s("archive-restore", "Premiere archive and restore validation", "an archive restore checklist", "archive scope, project revision, media paths, checksums, sidecars, and retention class", "approved archive package, file manifest, storage record, and restore-copy test", "the restored copy opens with dependencies accounted for and the source archive remains unchanged", "restore-pass rate and checksum reconciliation"),
        ],
    },
    44: {
        "prefix": "stem-lab", "label": "systems-on-chip and digital-systems education labs",
        "guard": "Support educators and learners; do not grade high-stakes work automatically or expose individual learner records. Follow the institution's lab safety process and use approved low-voltage equipment, simulation, or instructor-supervised exercises. Validate instructions against the exact toolchain and board revision. Keep instructional outputs separate from sign-off for real product hardware or safety-critical designs.",
        "sources": [("Arm Advanced SoC Design Education Kit", "https://github.com/arm-education/Advanced-System-on-Chip-Design-Education-Kit"), ("Open-source chip design introduction", "https://github.com/os-chip-design/chip-design-intro"), ("Open-source SoC design course", "https://github.com/os-chip-design/soc-chip-2025"), ("Quantum AI learning topic reference", "https://gitee.com/xpeter/Quantum-AI-learning"), ("AI Engineering from Scratch", "https://github.com/rohitg00/ai-engineering-from-scratch")],
        "streams": [
            s("prerequisite-map", "digital-systems prerequisite mapping", "a prerequisite-to-lab map", "learner entry knowledge, notation, tool familiarity, lab objective, and support route", "course outcomes, prior-unit map, tool prerequisite list, and educator review", "every lab has a reachable prerequisite path or an explicitly named preparation activity", "outcome coverage and unresolved-prerequisite count"),
            s("lab-objective", "hardware lab objective design", "a measurable lab objective card", "conceptual goal, observable student artifact, time budget, and instructor check", "course learning outcomes, lab constraints, and representative student work", "each objective maps to an observable artifact without requiring unapproved hardware changes", "objective-to-evidence coverage and time-fit estimate"),
            s("toolchain-reproducibility", "classroom hardware toolchain reproducibility", "a toolchain setup verification sheet", "software versions, license access, board revision, sample project, and clean-start state", "approved installation instructions, course image, sample hashes, and institution support path", "a fresh student environment reproduces the starter result or records a clear blocker", "setup-pass rate and unresolved-version count"),
            s("simulation-exercise", "digital logic simulation exercise design", "a simulation exercise and check set", "design input, expected waveform, reset behavior, edge cases, and student explanation", "approved RTL example, simulator version, expected traces, and instructor key", "the expected behavior is independently checked and student evidence targets the stated concept", "test-case coverage and expected-trace agreement"),
            s("waveform-literacy", "waveform interpretation instruction", "a waveform annotation guide", "clock domains, reset state, signal naming, timing window, and common interpretation error", "approved teaching waveform, design context, annotation conventions, and educator review", "the annotations explain observable relationships without implying hidden implementation facts", "signal-label coverage and learner-question completeness"),
            s("bench-safety", "supervised low-voltage lab readiness", "a lab-safety preflight", "equipment boundary, approved voltage/current limit, connection order, supervision, and stop procedure", "institution-approved safety sheet, equipment manual, instructor assignment, and board revision", "all safety responsibilities are assigned and live energization remains instructor-controlled", "safety-field coverage and unassigned-supervision count"),
            s("visual-accessibility", "circuit-diagram and waveform accessibility", "an accessible lab-visual checklist", "contrast, color redundancy, labels, reading order, zoom, and alternative text", "course diagrams, waveform captures, accessibility requirements, and learner feedback channel", "critical meaning does not depend on color alone and equivalent text descriptions are available", "visual-item coverage and unresolved-accessibility issue count"),
            s("assessment-rubric", "digital-design formative assessment rubric", "a formative rubric and calibration sample", "criteria, evidence, partial credit, feedback prompt, and human review boundary", "approved learning outcomes, sample anonymized artifacts, and educator scoring notes", "criteria are observable and calibration differences are discussed rather than auto-resolved", "criterion coverage and reviewer agreement"),
            s("team-capstone", "systems-design team capstone evidence", "a team capstone evidence board", "team roles, design revision, verification artifact, peer handoff, and individual reflection", "approved capstone brief, version-control expectations, team agreement, and review calendar", "technical claims map to a saved artifact and individual contributions are not inferred from activity counts", "deliverable coverage and unresolved ownership count"),
            s("lab-access", "SoC lab tool and station access readiness", "a lab station access map", "class section, license seat, tool image revision, board allocation, approved credential route, and offline fallback", "institutional license terms, station inventory, toolchain checklist, and instructor roster", "each learner group has an approved station and access route without sharing credentials", "seat coverage and blocked-group count"),
        ],
    },
}


def main() -> int:
    core.BATCHES.update(BATCHES)
    return core.main()


if __name__ == "__main__":
    raise SystemExit(main())
