#!/usr/bin/env python3
"""Define and build new 100-skill industry batches 24–33 (2,300 to 3,300)."""
from __future__ import annotations

import build_1000_skills_batches14_23 as core

# Read-only public catalogs are topic-discovery references only. The new skills
# are original procedures; no upstream skill text, prompts, examples, or code is
# copied. Batch-level source and scope notes are also recorded in references/.
BATCHES = {
    24: {
        "prefix": "agri-ops", "label": "agriculture, farm production, and land stewardship",
        "guard": "Use locally valid agronomic evidence and distinguish measured observations from assumptions. Do not set pesticide or fertilizer application rates, prescribe veterinary treatment, control irrigation equipment, or commit farm sales without qualified owner approval. Verify local weather, water rights, food-safety, and certification rules before relying on them.",
        "sources": [("Agriculture and land-stewardship skills catalog", "https://github.com/human-avatar/skills-for-agriculture"), ("Cross-profession agriculture topic catalog", "https://github.com/aniruddhaadak80/skills"), ("Scientific agent-skills catalog", "https://github.com/K-Dense-AI/scientific-agent-skills")],
        "streams": [
            ("soil", "soil health and land stewardship", "soil assessment note", "soil sampling, land history, erosion, organic matter, and field variability", "dated soil tests, sample locations, field history, and the current local interpretation guide", "sample locations and method are recorded, results are not generalized beyond their support, and follow-up is assigned", "sample coverage, unresolved field zones, and source date"),
            ("crop-plan", "crop rotation and planting plans", "crop rotation plan", "crop sequence, field suitability, planting windows, seed lots, and rotation constraints", "field map, prior crop records, seed documentation, and current regional calendar", "each proposed sequence is linked to a field, season, and stated constraint; uncertain dates remain provisional", "field coverage and planting-window confidence"),
            ("water", "farm water and irrigation planning", "irrigation planning brief", "water availability, soil moisture observations, crop stage, delivery limits, and weather uncertainty", "approved water allocation, meter or sensor record, crop stage, and current forecast", "every water assumption is sourced and no control setting is changed automatically", "water-balance completeness and forecast age"),
            ("scouting", "crop scouting and pest observations", "field scouting record", "observed symptoms, pest counts, beneficial organisms, location, and threshold source", "dated field observations, crop stage, geotag or field block, and locally approved threshold reference", "observations are separated from diagnosis and any treatment decision is escalated to the responsible agronomist", "scouting coverage and unresolved observations"),
            ("propagation", "seed and propagation operations", "propagation batch record", "seed identity, germination checks, nursery conditions, lot separation, and transplant readiness", "seed labels, germination results, nursery log, and current production target", "each batch retains a traceable identity and uncertain quality status is not promoted to pass", "lot traceability and readiness exceptions"),
            ("livestock", "livestock and grazing operations", "livestock movement ledger", "herd identifiers, pasture condition, movement dates, water access, and handling constraints", "approved herd register, pasture map, dated observations, and qualified animal-health guidance", "every movement is traceable to the responsible handler and health concerns are escalated without diagnosis", "record completeness and unresolved welfare observations"),
            ("aquaculture", "aquaculture and pond operations", "pond condition record", "water readings, stock counts, feed records, mortalities, and system alarms", "calibrated sensor log, sampling time, stocking record, feed record, and site biosecurity plan", "out-of-range observations are preserved and routed to a qualified operator; no treatment is inferred", "sensor completeness and time-to-escalation"),
            ("forestry", "forestry and agroforestry planning", "land-use stewardship plan", "species mix, stand condition, habitat constraints, access, and harvest horizon", "parcel boundary, dated field survey, local ecological references, and owner-approved objectives", "every proposed activity maps to a parcel and unresolved ecological constraints are flagged for expert review", "parcel coverage and constraint status"),
            ("postharvest", "harvest and post-harvest handling", "harvest readiness record", "maturity observations, equipment readiness, storage capacity, moisture readings, and lot identity", "dated field sample, calibrated instrument record, storage plan, and product specification", "readiness evidence is tied to the correct lot and safety or grade determinations stay with qualified staff", "sample coverage and storage-capacity margin"),
            ("farm-market", "farm enterprise and market administration", "farm enterprise evidence brief", "seasonal costs, buyer requirements, market channel, certification evidence, and succession records", "owner-approved budgets, dated buyer specifications, current certification record, and source documents", "commercial assumptions are labeled, buyer commitments are not implied, and financial or legal decisions are escalated", "source coverage and unresolved commitment count"),
        ],
    },
    25: {
        "prefix": "energy-ops", "label": "energy procurement, utilities, and distributed-energy operations",
        "guard": "Treat outputs as planning and evidence artifacts, not instructions to operate a grid, protection system, plant, or market position. Never change a tariff enrollment, hedge, contract, inverter, battery dispatch, protection setting, or utility control without the authorized operator and required engineering review. Verify jurisdiction, market, and effective date.",
        "sources": [("Energy procurement skill topic reference", "https://github.com/affaan-m/ECC/blob/main/skills/energy-procurement/SKILL.md"), ("Scientific energy-skills topic catalog", "https://github.com/K-Dense-AI/scientific-agent-skills")],
        "streams": [
            ("utility-bill", "utility bill and tariff analysis", "utility-bill variance worksheet", "meter identifiers, billing periods, rate components, demand peaks, and contract terms", "original bills, interval data, tariff version, meter map, and billing calendar", "units and periods reconcile to source documents and proposed tariff changes remain review-only", "unreconciled charges and source freshness"),
            ("procurement", "energy supply procurement", "energy request-for-proposal comparison", "load shape, contract term, product structure, risk tolerance, and supplier assumptions", "approved facility list, interval load, supplier quotes, contract dates, and procurement policy", "offers are normalized to comparable terms and no bid is accepted or negotiated by the agent", "bid completeness and cost-scope comparability"),
            ("demand-response", "demand response readiness", "demand-response readiness checklist", "site eligibility, event notification, operational constraints, measurement baseline, and settlement evidence", "program rules, site meter data, equipment constraints, and operator-approved response plan", "all assumed controllable load has an owner and a safe non-participation path", "eligible-load evidence and notification coverage"),
            ("renewable-contract", "renewable power-purchase agreement review", "renewable contract comparison brief", "contract shape, settlement point, attributes, basis exposure, term, and credit requirements", "current offer, public market inputs, load match, attribute registry rules, and counsel-reviewed terms", "every modeled case states source dates and contract or legal conclusions are left to qualified reviewers", "assumption coverage and unresolved term count"),
            ("onsite-generation", "onsite generation and interconnection planning", "onsite generation readiness packet", "site constraints, interconnection status, production estimates, metering, and approvals", "site boundary, utility correspondence, equipment proposal, and current interconnection process", "each dependency has a named owner and no connection or commissioning approval is inferred", "dependency completion and source freshness"),
            ("storage", "energy storage project evaluation", "storage scenario worksheet", "usable capacity, degradation, duty cycle, tariff, interconnection, and safety dependencies", "vendor data sheet, meter profile, utility tariff, site constraints, and current safety review", "performance assumptions remain within cited evidence and live dispatch is outside scope", "input completeness and scenario sensitivity"),
            ("efficiency", "facility energy-efficiency project tracking", "efficiency measure register", "baseline, proposed measure, measurement boundary, operating schedule, and persistence", "dated bills or interval data, facility schedule, engineering estimate, and measurement plan", "savings claims are tied to a defined baseline and uncertainty is reported", "baseline coverage and verification status"),
            ("load-forecast", "facility energy load forecasting", "load forecast review packet", "weather, operating calendar, planned outages, production changes, and meter history", "versioned interval reads, facility calendar, approved production assumptions, and weather source", "forecast drivers are explicit and a scenario is not presented as a guaranteed demand level", "backtest error and missing-interval rate"),
            ("utility-reliability", "utility reliability and outage coordination", "outage coordination status sheet", "planned outage windows, critical loads, notification chain, site dependencies, and restoration assumptions", "utility notices, facility continuity plan, equipment dependencies, and contact roster", "unverified restoration times are labeled and only the utility or site operator confirms operational status", "contact coverage and unresolved dependency count"),
            ("energy-reporting", "energy and emissions reporting evidence", "energy reporting evidence ledger", "meter boundary, energy units, conversion factors, reporting period, and assurance trail", "meter exports, factor source and version, boundary statement, and reporting instructions", "each reported value traces to a source, period, unit, and factor version", "meter coverage and unverified-factor count"),
        ],
    },
    26: {
        "prefix": "mfg-ops", "label": "industrial manufacturing and quality-engineering operations",
        "guard": "Keep engineering and quality authorities responsible for safety, product release, and process changes. Do not change machine controls, release a lot, close a nonconformance, approve a supplier, or certify compliance automatically. Preserve revision identity, evidence, and customer-specific requirements; verify the applicable standard edition with the quality owner.",
        "sources": [("Quality engineering skills and deterministic-tooling catalog", "https://github.com/Siddardth7/quality-engineering-skills"), ("Manufacturing quality-engineering skills catalog", "https://github.com/RBraga01/Quality-Engineering-Skills"), ("Cross-profession manufacturing topic catalog", "https://github.com/aniruddhaadak80/skills")],
        "streams": [
            ("qms-audit", "quality-management-system audit readiness", "QMS audit evidence map", "process scope, requirement edition, objective evidence, finding status, and owner", "controlled procedure, internal audit plan, training record, and current revision log", "each finding cites a controlled requirement and remains open until an authorized owner verifies closure", "requirement coverage and overdue finding count"),
            ("process-risk", "manufacturing process-risk analysis", "process risk worksheet", "process step, failure mode, cause, effect, controls, and review authority", "approved process flow, current customer requirements, defect history, and cross-functional inputs", "risk assumptions are explicit and severity or action-priority decisions are left to the approved team", "step coverage and unresolved high-risk items"),
            ("spc", "statistical process-control review", "SPC signal review packet", "measurement definition, subgroup design, control limits, rule signals, and reaction plan", "time-stamped measurements, sampling plan, process context, and approved control chart method", "calculation inputs and rule version are reproducible and no process adjustment is applied automatically", "data completeness and signal-to-investigation time"),
            ("measurement", "measurement-system and calibration administration", "measurement-system evidence register", "instrument identity, calibration status, uncertainty, method, and traceability", "asset register, calibration certificate, method revision, and study data", "out-of-tolerance instruments are quarantined for owner review and their affected interval is traceable", "calibration coverage and unresolved instrument impact"),
            ("capa", "nonconformance and corrective-action administration", "corrective-action evidence packet", "containment, affected lots, cause evidence, corrective action, and effectiveness criteria", "nonconformance record, lot genealogy, inspection evidence, and approved CAPA procedure", "containment and cause hypotheses are distinguished; final disposition and closure require quality authority", "affected-lot traceability and effectiveness evidence"),
            ("supplier-quality", "supplier-quality and PPAP package review", "supplier submission completeness matrix", "part revision, submission level, capability evidence, change status, and customer approval", "current drawing, purchase specification, supplier documents, and approved submission checklist", "every required element maps to the correct revision and incomplete submissions are not marked approved", "element coverage and revision mismatch count"),
            ("process-change", "manufacturing process-change control", "process-change impact register", "equipment, material, method, software, layout, validation, and customer-notification dependencies", "approved baseline, proposed change package, validation protocol, and authority matrix", "affected controls and approvals are traceable before implementation; no change is released by the agent", "dependency coverage and unapproved change count"),
            ("maintenance", "manufacturing maintenance planning", "maintenance backlog priority brief", "asset criticality, failure history, spare parts, planned window, and safety permit needs", "CMMS history, manufacturer documentation, site-approved criticality, and current work orders", "priority logic is visible and safety permits or live work instructions are assigned to qualified staff", "overdue critical tasks and evidence completeness"),
            ("traceability", "production traceability and genealogy", "lot genealogy reconciliation", "work order, material lot, process route, equipment record, inspection, and release state", "MES or traveler export, material issue record, route revision, and authorized release record", "each sampled unit traces to the approved inputs and unresolved links stay visible", "genealogy coverage and unmatched unit count"),
            ("yield", "manufacturing yield and scrap analysis", "yield-loss evidence brief", "defined denominator, product mix, defect code, rework, scrap, and shift context", "versioned production counts, disposition codes, process context, and metric definition", "reported loss categories reconcile to source counts and causal claims are labeled by evidence strength", "count reconciliation and unknown-cause share"),
        ],
    },
    27: {
        "prefix": "health-admin", "label": "healthcare administration, revenue-cycle, and access operations",
        "guard": "This pack supports administration and workflow analysis, not diagnosis, treatment, medical necessity decisions, patient eligibility determinations, or clinical triage. Minimize protected health information, use approved systems, follow local privacy rules, and keep clinical, coverage, quality, and compliance decisions with qualified authorized professionals.",
        "sources": [("Healthcare administration agent catalog", "https://github.com/ajhcs/healthcare-agents"), ("Healthcare workflow analysis skill", "https://github.com/Skharbi/Clinical-workflow-analysis")],
        "streams": [
            ("revenue-cycle", "healthcare revenue-cycle administration", "revenue-cycle variance packet", "claim status, denial categories, coding handoff, payer response, and service period", "authorized de-identified or minimum-necessary billing extract, remittance codes, and approved work queues", "counts reconcile to the source window and coding or appeal judgments are routed to authorized staff", "denial-rate denominator and unresolved queue age"),
            ("patient-access", "patient access and referral administration", "access backlog handoff", "referral source, appointment constraints, status, language access, and follow-up ownership", "approved scheduling worklist, referral record, access policy, and staff roster", "each case has an accurate administrative status and clinical urgency is not inferred", "unassigned referrals and wait-time source freshness"),
            ("payer-contract", "payer contract and underpayment review", "payer variance evidence brief", "contract version, service category, expected payment basis, remittance, and dispute deadline", "executed contract location, approved fee schedule, authorized claim sample, and remittance evidence", "each variance is a reproducible comparison and contract interpretation is escalated to authorized counsel or contracting staff", "sample coverage and time-to-review"),
            ("prior-auth", "prior-authorization workflow administration", "authorization status tracker", "request completeness, payer channel, response deadline, status, and clinician handoff", "approved minimum-necessary record, payer rule source, request receipt, and clinical owner roster", "missing items and status are traceable; clinical necessity and appeal decisions remain with clinicians", "deadline coverage and pending-case age"),
            ("care-coordination", "care-coordination handoff administration", "care handoff checklist", "responsible team, stated service need, transfer status, follow-up date, and consent boundary", "authorized handoff record, approved workflow, and assigned care-team role", "administrative ownership is explicit without generating clinical advice or adding unstated facts", "handoff completeness and unresolved owner count"),
            ("quality-readiness", "healthcare quality and accreditation readiness", "quality evidence matrix", "measure definition, reporting window, evidence owner, control, and review cycle", "current approved measure specification, de-identified output, and internal policy reference", "each metric has a matching definition and limitations; accreditation conclusions stay with the designated owner", "measure coverage and evidence freshness"),
            ("provider-credentialing", "provider credentialing and payer enrollment administration", "provider credentialing status register", "license verification source, specialty, payer enrollment, privilege-file status, expiration, and site association", "provider-submitted documents, dated official license lookup, payer enrollment status, committee record, and renewal calendar", "each status has a dated source, expired or unknown records are escalated, and privilege decisions remain with credentialing authorities", "source-verification coverage and expired-document count"),
            ("capacity", "healthcare capacity and resource planning", "capacity constraint brief", "staffed capacity, rooms, equipment, scheduled demand, service hours, and uncertainty", "approved aggregate schedule, staffing roster, asset state, and planning horizon", "capacity assumptions are labeled and no operational assignment or patient prioritization is issued", "coverage gap and forecast interval"),
            ("health-it", "health-information technology incident administration", "health IT incident handoff", "system, interface, scope, user impact, downtime status, and support owner", "approved incident log, interface monitor, change record, and minimum-necessary test sample", "observed technical evidence is separated from clinical impact assumptions and the incident owner confirms closure", "affected-interface coverage and unresolved duration"),
            ("pharmacy-admin", "pharmacy program and inventory administration", "pharmacy operations exception list", "inventory record, contract, formulary version, supplier status, and authorized pharmacist handoff", "approved inventory export, current policy version, purchasing record, and supervisor assignment", "administrative discrepancies are traceable and no therapeutic, dosing, or substitution recommendation is made", "inventory reconciliation and pharmacist-review backlog"),
        ],
    },
    28: {
        "prefix": "trial-ops", "label": "clinical research operations and health-data coordination",
        "guard": "These workflows support research administration and data operations only. Do not determine eligibility, provide medical advice, decide whether consent is valid, assess causality, or replace an investigator, IRB, privacy officer, statistician, or regulator. Use approved study systems, protect participant identity, and verify the current protocol and jurisdictional requirements.",
        "sources": [("Healthcare research and clinical-administration agent catalog", "https://github.com/ajhcs/healthcare-agents"), ("Evidence-first healthcare workflow analysis skill", "https://github.com/Skharbi/Clinical-workflow-analysis"), ("Scientific agent-skills catalog", "https://github.com/K-Dense-AI/scientific-agent-skills")],
        "streams": [
            ("site-startup", "clinical-trial site startup coordination", "site startup tracker", "site contacts, required documents, system access, training, and activation dependencies", "approved startup checklist, document version register, training evidence, and sponsor or institution contacts", "each prerequisite has an owner and dated evidence; activation remains an authorized investigator or sponsor decision", "prerequisite coverage and overdue item count"),
            ("ethics-submission", "research ethics submission administration", "ethics submission completeness map", "submission version, attachments, response dates, amendment history, and responsible office", "current protocol package, institutional checklist, correspondence log, and submission receipt", "every package item maps to a controlled version and ethics approval is never inferred from submission status", "document completeness and response deadline coverage"),
            ("visit-operations", "research visit and schedule coordination", "visit schedule exception queue", "protocol visit window, site calendar, participant contact preference, and operational blocker", "approved visit schedule, site calendar, consented contact preference, and study coordinator record", "the schedule does not disclose unnecessary health details and missed windows are routed to the study team", "visit-window coverage and exception age"),
            ("edc-change", "electronic data-capture change control", "EDC change-impact checklist", "form version, field logic, validation rules, migration, training, and audit-trail impact", "approved change request, test evidence, release note, and system audit trail", "each change has a controlled version and test evidence before a system owner releases it", "test coverage and unresolved migration risks"),
            ("query-management", "research data-query administration", "data query aging report", "query origin, field reference, response owner, due date, and resolution state", "authorized EDC query export, data dictionary, and approved query convention", "query status is evidence-backed and no value is changed without the authorized source record", "query aging and reopen rate"),
            ("deviation-log", "protocol-deviation documentation", "protocol deviation evidence log", "event date, protocol version, affected activity, notification route, and investigator review status", "dated source record, current protocol, deviation SOP, and responsible study contact", "events are described without assigning seriousness or causality unless the qualified investigator recorded it", "required-field coverage and unreviewed event age"),
            ("sample-custody", "research specimen chain-of-custody administration", "specimen custody reconciliation", "sample identifier, collection time, container, storage location, transfer, and receipt state", "approved coded sample manifest, temperature log, shipment record, and receiving confirmation", "coded identities reconcile across handoffs and missing custody evidence is escalated without reconstructing a gap", "custody-link coverage and unresolved transfer count"),
            ("monitoring", "research monitoring and inspection readiness", "monitoring evidence index", "source-document request, version, access role, findings, and response owner", "approved monitoring plan, authorized document index, access log, and current finding tracker", "every finding links to the controlled evidence and participant identifiers are minimized in shared outputs", "evidence request coverage and overdue response count"),
            ("safety-intake", "research safety-event intake administration", "safety-event routing packet", "receipt time, minimum event metadata, reporting deadline, confidentiality, and investigator route", "authorized intake record, current reporting procedure, and designated safety contact", "events are routed on time without severity, causality, or treatment conclusions being generated", "routing completeness and deadline coverage"),
            ("study-closeout", "clinical research closeout and archive", "study closeout evidence matrix", "final data status, open queries, essential records, access removal, retention, and repository handoff", "approved closeout checklist, data freeze evidence, essential-document index, and retention schedule", "only verified closeout evidence is marked complete and retention or destruction decisions remain with the record owner", "closeout requirement coverage and unresolved record count"),
        ],
    },
    29: {
        "prefix": "geo-ops", "label": "GIS, geospatial data engineering, and remote-sensing delivery",
        "guard": "Treat coordinates and derived maps as decision-support data, not authoritative boundaries or survey certification. Preserve coordinate reference systems, resolution, time, provenance, and source licensing; do not publish personal, sensitive, restricted, or safety-critical locations without the data owner’s review. Check current platform behavior and data terms.",
        "sources": [("GIS-native agent-skills catalog", "https://github.com/danmaps/gis-agent-skills"), ("Geospatial data engineering skills catalog", "https://github.com/isaaccorley/geospatial-skills"), ("Geospatial science topic reference", "https://github.com/K-Dense-AI/scientific-agent-skills/blob/main/skills/geomaster/SKILL.md")],
        "streams": [
            ("vector-topology", "vector schema and topology quality", "vector dataset QA report", "geometry validity, required attributes, topology constraints, and feature identifiers", "source schema, geometry samples, dataset CRS metadata, and published topology rules", "invalid geometry and rule exceptions are quantified and no source geometry is silently repaired", "valid-feature rate and unresolved topology count"),
            ("raster-delivery", "raster tile and cloud-optimized delivery", "raster delivery manifest", "pixel type, nodata, tiling, overviews, compression, and spatial extent", "source raster metadata, expected grid, delivery specification, and validation output", "output metadata and sampled pixels match the declared transform and delivery settings", "metadata completeness and pixel sample parity"),
            ("stac-search", "STAC catalog search and asset selection", "STAC asset selection log", "collection, item time, spatial footprint, asset role, cloud metadata, and license", "current catalog responses, collection descriptions, item IDs, and source-use terms", "selection criteria and rejected candidates are recorded and no asset is represented as current beyond its timestamp", "query coverage and selected-item provenance"),
            ("imagery-quality", "satellite imagery quality and mask review", "imagery QA evidence packet", "scene identity, cloud and no-data mask, georegistration evidence, and acquisition time", "scene metadata, mask layers, quality flags, and independent visual or numeric samples", "mask behavior is validated on sampled areas and remaining artifacts are explicitly disclosed", "mask coverage and unexplained-pixel share"),
            ("overlay-analysis", "spatial overlay and join result validation", "spatial operation reconciliation", "input feature counts, predicate, boundary behavior, duplicates, and unmatched output", "versioned inputs, CRS metadata, documented predicate, and independent sample pairs", "output counts and sampled relationships match the stated predicate and edge cases are recorded", "count reconciliation and sample agreement"),
            ("field-schema", "field-survey schema and collection quality", "field collection schema review", "required fields, coded values, location precision, timestamps, and offline sync behavior", "approved form schema, collection instructions, sample records, and data minimization rules", "records contain the needed fields without collecting unnecessary personal or sensitive data", "required-field coverage and sync exception rate"),
            ("geoparquet", "GeoParquet packaging and partition review", "geospatial package validation report", "geometry encoding, CRS metadata, partition strategy, compression, and reader compatibility", "source table contract, target reader requirements, file metadata, and sample query results", "package metadata and representative spatial queries are reproducible in the declared target environment", "metadata conformance and query sample parity"),
            ("map-export", "cartographic map export and accessibility review", "map export QA checklist", "legend, scale, labels, color, accessibility, print layout, and attribution", "approved map brief, data timestamps, style rules, export profile, and accessibility checks", "map elements communicate units, date, source, uncertainty, and access needs without implying unwarranted precision", "required-element coverage and export consistency"),
            ("hosted-layer", "hosted-layer publication preflight", "hosted layer release checklist", "schema, item metadata, permissions, sharing scope, service limits, and rollback path", "target platform documentation, source layer, owner approval, and publication setting snapshot", "the draft is read-only until an owner confirms sharing scope and every public field passes review", "preflight completion and permission exceptions"),
            ("pipeline-repro", "geospatial pipeline reproducibility and output checks", "geospatial pipeline run record", "source version, parameters, environment, processing order, output extent, and logs", "input checksums, versioned configuration, tool versions, and previous known-good output", "the result can be reproduced from the recorded inputs and declared differences are reviewed", "run metadata coverage and output-difference count"),
        ],
    },
    30: {
        "prefix": "people-ops", "label": "human-resources, workforce, and talent operations",
        "guard": "Protect candidate and employee confidentiality and follow jurisdiction-specific employment, privacy, accessibility, and labor requirements. Do not rank or reject candidates, make hiring or promotion decisions, set pay, infer protected traits, investigate misconduct, or recommend discipline. Keep decisions with qualified, authorized people and use fair, job-related, reviewable criteria.",
        "sources": [("Human-resources and talent skills catalog", "https://github.com/tuanductran/hr-skills"), ("Recruiting workflow skills catalog", "https://github.com/zubair-trabzada/ai-recruiter-claude"), ("Microsoft employee-onboarding agent workflow reference", "https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/architecture/solution-ideas/onboarding-agent.md")],
        "streams": [
            ("role-intake", "role architecture and job intake", "role intake brief", "business need, essential duties, approved level, location, and review owner", "approved workforce request, current job architecture, and applicable local job-posting requirements", "requirements are job-related and approved; unsupported education or experience gates are flagged", "required-field coverage and unresolved approval count"),
            ("recruiting", "recruiting process coordination", "recruiting process status sheet", "requisition state, interview stages, accessibility requests, panel readiness, and candidate communication owner", "authorized ATS export, approved process map, current interview rubric, and contact preference", "status is traceable and no candidate score or hiring recommendation is generated", "stage completeness and overdue handoff count"),
            ("offer-admin", "employment offer administration and approval tracking", "offer approval status packet", "approved compensation band, level, document version, approval chain, contingent steps, expiry, and acceptance state", "approved requisition and pay band, draft offer, authority matrix, and current local template version", "only approved terms appear in the draft, versions and signatures are traceable, and no offer is issued without authorized sign-off", "approval coverage, stale-template count, and unresolved condition count"),
            ("onboarding", "new-hire onboarding coordination", "onboarding milestone plan", "start-date dependencies, required forms, equipment, training, team introductions, and owner assignment", "approved onboarding checklist, role profile, employee preferences, and current policy sources", "each milestone has an owner and blocker route; sensitive documents remain in authorized HR systems", "milestone coverage and blocked-item age"),
            ("offboarding", "employee offboarding administration", "offboarding access and records checklist", "approved separation date, return items, access tasks, final-record routing, and handoff", "authorized HR event, access control checklist, asset log, and retention policy", "tasks are assigned to responsible owners and no access is revoked or employment decision is made automatically", "task completion and unverified access status"),
            ("learning", "workforce learning and credential tracking", "learning requirement matrix", "role requirement, course version, completion evidence, renewal date, and accommodation route", "approved training catalog, assignment policy, employee record scope, and learning system export", "completion status maps to the current requirement and exceptions are not treated as misconduct", "assignment coverage and renewal horizon"),
            ("workforce-plan", "workforce planning and headcount reconciliation", "workforce plan assumptions register", "approved positions, vacancies, budget window, capacity assumptions, and scenario range", "authorized aggregate HRIS snapshot, approved budget, and dated business assumptions", "aggregate counts reconcile and scenarios do not label individual employees as attrition risks", "headcount reconciliation and assumption freshness"),
            ("benefits-admin", "benefits and payroll administration", "benefits administration exception list", "plan version, eligibility data source, payroll cutoff, employee query, and specialist route", "current plan documents, authorized payroll export, local official guidance, and benefits administrator contact", "no individual eligibility or tax conclusion is made without the authorized administrator", "case completeness and cutoff coverage"),
            ("leave-access", "leave and workplace-accessibility administration", "confidential leave handoff checklist", "request status, required process steps, privacy boundary, interactive-process owner, and due date", "employee-authorized request, current policy, minimal necessary records, and designated HR contact", "medical details are not copied into general artifacts and accommodation decisions remain human-led", "process-step coverage and overdue follow-up"),
            ("employee-relations", "employee-relations intake and routing", "confidential employee-relations intake log", "reported concern, immediate safety route, impartial owner, preservation needs, and confidentiality", "minimum-necessary employee report, current escalation policy, and designated investigator roster", "allegations are recorded neutrally, no credibility or guilt judgment is generated, and urgent safety concerns are escalated", "routing completeness and time-to-owner"),
        ],
    },
    31: {
        "prefix": "retail-ops", "label": "retail, e-commerce, and marketplace operations",
        "guard": "Do not change live prices, publish listings, place purchase orders, issue refunds, message customers, or modify store policy without explicit authorization. Minimize personal and payment data, respect marketplace rules and intellectual-property constraints, and verify current platform capabilities and regional consumer requirements.",
        "sources": [("Shopify store-operations skills catalog", "https://github.com/40rty-ai/shopify-admin-skills"), ("Cross-border e-commerce workflow skills", "https://github.com/noique/cross-border-ecommerce-skills"), ("E-commerce skills and prompts catalog", "https://github.com/Ecom-Agent-Tools/Ecom-Agent-Tools")],
        "streams": [
            ("catalog", "product catalog and listing quality", "catalog quality exception report", "product identity, variant attributes, media, claims, taxonomy, and channel requirements", "authorized product export, supplier specification, current marketplace schema, and claim approval record", "every proposed correction maps to an evidence source and no listing is published automatically", "required-attribute coverage and unresolved claim count"),
            ("merchandising", "assortment and merchandising review", "assortment decision evidence brief", "category role, lifecycle, stock position, margin inputs, and customer-search evidence", "approved catalog, dated sales view, current range plan, and owner priorities", "comparisons use consistent periods and no SKU is added or removed without merchandising approval", "assortment coverage and data freshness"),
            ("pricing", "pricing and promotion setup review", "promotion QA worksheet", "base price, discount rule, eligibility, channel scope, dates, and stacking behavior", "approved price list, promotion request, platform rule, and test cart result", "all rules match the approved brief and changes stay in draft pending authorized publication", "scenario coverage and rule conflict count"),
            ("inventory", "retail inventory and replenishment planning", "replenishment exception queue", "on-hand, reserved, in-transit, lead time, seasonality, and stockout threshold", "authorized inventory snapshot, open orders, supplier lead-time evidence, and planning policy", "quantities reconcile by location and no purchase order or transfer is placed", "stock coverage and unconfirmed lead-time share"),
            ("fulfillment", "order and fulfillment exception management", "fulfillment exception handoff", "order status, carrier event, promised window, inventory allocation, and customer-impact route", "authorized order-status export, carrier scan, fulfillment policy, and support owner roster", "each exception has a source timestamp and an owner; no shipment or customer message is initiated", "exception age and source freshness"),
            ("returns", "returns and refund operations analysis", "returns disposition evidence brief", "return reason, item condition, policy version, restock state, refund status, and abuse signal", "authorized de-identified return data, current published policy, inspection record, and approved reason taxonomy", "trends are aggregated, individual refund or fraud decisions remain human-reviewed, and counts reconcile", "reason-code completeness and open-case aging"),
            ("marketplace", "marketplace policy and listing compliance", "marketplace requirement map", "channel rule, product category, required disclosure, prohibited claim, and effective date", "current official marketplace policy, product source file, region, and last-checked date", "each requirement links to the applicable channel and region; uncertain enforcement is escalated", "policy-source coverage and stale-rule count"),
            ("store-ops", "store operations and labor readiness", "store readiness handoff", "opening tasks, staffing coverage, local inventory, safety notes, and escalation owner", "approved store checklist, published hours, roster coverage, and facilities issue log", "readiness gaps are assigned without changing schedules or making employment decisions", "checklist coverage and unresolved critical issue count"),
            ("loyalty", "retail loyalty-program operations", "loyalty program reconciliation brief", "member cohort definition, earn and redeem events, tier rules, expiration, liability inputs, and promotion exclusions", "published program terms, authorized aggregate rewards ledger, approved finance policy, and current promotion brief", "member and reward counts reconcile, personal data is minimized, and rule changes remain approval-gated", "event reconciliation and unverified reward-rule count"),
            ("fraud-review", "retail transaction anomaly review", "transaction review queue", "rule trigger, transaction state, uncertainty, false-positive risk, and reviewer route", "approved aggregate or tokenized transaction data, current fraud rule, and investigator guidance", "signals are presented as review leads rather than proof and no transaction is blocked automatically", "review coverage and false-positive feedback"),
        ],
    },
    32: {
        "prefix": "insure-ops", "label": "insurance administration, claims evidence, and actuarial operations",
        "guard": "This is administrative and analytical support, not coverage advice, underwriting authority, actuarial certification, fraud determination, legal advice, or a claim decision. Keep protected financial and health details in approved systems. Do not bind, deny, settle, reserve, price, or communicate a coverage decision; route judgment to the licensed or authorized professional.",
        "sources": [("Finance and insurance skills catalog", "https://github.com/GAJETOso/financeskills"), ("Insurance-claims workflow topic reference", "https://github.com/CALLE-AI/awesome-phone-call-agents/pull/564"), ("Insurance claims-processing project overview", "https://github.com/erolegerkan/claims-processing-hackd-ms-hackathon/blob/main/challenge-2/README.md")],
        "streams": [
            ("submission", "insurance submission intake", "submission completeness checklist", "insured identity, requested line, exposure schedule, loss history, broker source, and authority route", "authorized submission documents, field dictionary, current appetite statement, and receipt timestamp", "missing fields and source conflicts are listed without recommending acceptance or rejection", "field completeness and submission age"),
            ("risk-survey", "risk-survey evidence administration", "risk-survey evidence map", "site, asset, control observation, survey date, evidence quality, and specialist follow-up", "approved survey record, photo metadata, site schedule, and current engineering guidance", "observations are attributed and no hazard rating or coverage recommendation is generated", "evidence coverage and open safety follow-up count"),
            ("policy-admin", "policy administration and renewal data quality", "policy change reconciliation", "policy version, named insured, effective dates, endorsements, premium fields, and renewal owner", "authorized policy record, approved change request, billing export, and version history", "administrative values reconcile and all coverage interpretation remains with the authorized professional", "version alignment and unresolved field count"),
            ("claim-intake", "insurance claim intake and evidence reconciliation", "claim intake evidence packet", "loss date, location, reported event, documents, adjuster assignment, and response deadline", "authorized claim intake, source file list, time-stamped correspondence, and claim-handling procedure", "the record preserves reported facts and missing evidence without determining coverage or liability", "evidence completeness and response deadline coverage"),
            ("reserve-data", "actuarial reserving data preparation", "reserving data quality report", "claim cohort, valuation date, paid/incurred fields, exposure basis, and development triangle inputs", "approved actuarial extract, data dictionary, cutoff memo, and prior-period reconciliation", "inputs reconcile to the declared valuation basis and no actuarial estimate is certified", "unmatched claim count and cutoff coverage"),
            ("reinsurance", "reinsurance treaty and bordereaux reconciliation", "bordereaux exception register", "treaty identifier, risk layer, attachment point, period, currency, and ceded transaction", "executed treaty reference, authorized bordereaux, ledger extract, and approved mapping table", "all variances are quantified and contractual interpretation is referred to reinsurance counsel or owner", "transaction reconciliation and unresolved mapping count"),
            ("cat-exposure", "catastrophe exposure aggregation support", "catastrophe exposure data packet", "location quality, insured values, peril, occupancy, geocode uncertainty, and accumulation scope", "authorized schedule, source geocoding, approved exposure definition, and model/version metadata", "aggregation limitations and missing locations are visible; no loss estimate is represented as a guarantee", "location completeness and geocode confidence"),
            ("premium-audit", "premium audit evidence administration", "premium audit variance ledger", "reported exposure basis, policy term, payroll or sales class, supporting document, and auditor status", "authorized exposure report, policy schedule, source ledger, and current audit checklist", "every variance traces to a period and record and any premium adjustment requires authorized review", "support coverage and unresolved variance count"),
            ("producer-comp", "producer compensation reconciliation", "commission reconciliation packet", "producer code, policy transaction, rate schedule, statement period, and adjustment reason", "approved producer agreement reference, policy transaction export, and commission statement", "amounts reconcile by transaction and contractual or payroll decisions are escalated", "transaction match rate and unexplained adjustment total"),
            ("regulatory-evidence", "insurance regulatory reporting evidence", "regulatory filing evidence index", "entity, jurisdiction, period, report version, source schedule, and sign-off owner", "current regulator instructions, approved workpaper, entity register, and filing receipt", "each reported amount traces to an approved schedule and filing or certification remains with the authorized officer", "schedule coverage and sign-off completeness"),
        ],
    },
    33: {
        "prefix": "climate-ops", "label": "climate, sustainability, and environmental reporting operations",
        "guard": "Treat outputs as traceable evidence and planning artifacts, not environmental certification, legal advice, investment advice, or proof of impact. State organizational and reporting boundaries, factor versions, uncertainty, and data gaps. Do not publish environmental claims or submit regulatory disclosures without qualified review and current authoritative sources.",
        "sources": [("Green software and sustainability skills topic catalog", "https://github.com/green-code-initiative/ai-green-skills"), ("Environmental and climate research skills catalog", "https://github.com/K-Dense-AI/scientific-agent-skills"), ("Environmental reporting and compliance topic index", "https://github.com/lawve-ai/awesome-legal-skills")],
        "streams": [
            ("ghg-boundary", "greenhouse-gas inventory boundary administration", "GHG boundary evidence register", "entity scope, operational boundary, reporting period, source category, and consolidation rule", "approved reporting policy, entity map, meter or activity source, and factor methodology", "every included or excluded source has a reason and unresolved boundary decisions are escalated", "source coverage and unassigned boundary count"),
            ("factor-lineage", "emissions-factor provenance and version control", "factor provenance ledger", "factor source, geography, year, unit, gas basis, version, and substitution rule", "published factor table, retrieval date, original unit, and approved conversion method", "each calculated input points to a versioned source and conversions are reproducible", "factor freshness and unit-conversion completeness"),
            ("disclosure", "sustainability disclosure evidence administration", "disclosure evidence map", "disclosure requirement, reporting boundary, metric, evidence owner, and approval path", "current official reporting text, internal metric register, source document, and review log", "each disclosure statement links to evidence and legal or assurance conclusions are left to qualified reviewers", "requirement coverage and evidence approval status"),
            ("climate-risk", "climate scenario evidence review", "climate scenario assumptions register", "scenario name, time horizon, hazard variable, geography, exposure, and model limitation", "current scenario dataset, asset boundary, source documentation, and model version", "scenario assumptions are not confused with forecasts and spatial or temporal limitations are explicit", "asset coverage and assumption traceability"),
            ("adaptation", "climate adaptation project readiness", "adaptation project dependency map", "hazard rationale, proposed measure, community or ecosystem dependencies, funding stage, and monitoring", "approved project scope, source hazard evidence, stakeholder record, and current permit or funding checklist", "each benefit claim has a measure and uncertainty note; implementation remains with the authorized owner", "dependency coverage and unverified benefit count"),
            ("biodiversity", "biodiversity and ecosystem evidence administration", "biodiversity evidence register", "site boundary, habitat class, observation date, source method, and survey qualification", "authorized survey, current classification reference, location metadata, and data-use constraints", "observations remain distinguishable from inference and no ecological certification is claimed", "site coverage and method completeness"),
            ("water", "water withdrawal and stewardship reporting", "water accounting reconciliation", "withdrawal source, meter, basin, period, reuse, discharge boundary, and unit", "meter records, source definitions, basin mapping, factor version, and approved reporting protocol", "volumes reconcile across sources and boundary or basin uncertainty is surfaced", "meter coverage and unit reconciliation"),
            ("materials-waste", "materials, waste, and circularity evidence", "materials flow ledger", "material category, mass unit, supplier, reuse route, waste stream, and reporting period", "weighbridge or purchase records, waste vendor receipt, material dictionary, and conversion basis", "reported flows balance or explain the known gap and no recycling claim is made without evidence", "mass-balance variance and receipt coverage"),
            ("supplier-claims", "supplier sustainability-claim substantiation", "supplier claim evidence matrix", "claim wording, scope, boundary, supporting method, validity period, and reviewer", "supplier declaration, certificate scope, primary data, factor version, and current claim policy", "each external claim is traceable to evidence and unverified marketing language is blocked for human review", "claim coverage and expired evidence count"),
            ("carbon-instruments", "carbon-credit and environmental-instrument record review", "environmental instrument due-diligence checklist", "project identity, registry record, serial range, vintage, status, retirement, and claim boundary", "registry record, transaction document, public methodology, and approved claims policy", "identity and status are independently checked and no offset or neutrality claim is published automatically", "registry-field completeness and unresolved claim count"),
        ],
    },
}


def main() -> int:
    core.BATCHES.update(BATCHES)
    return core.main()


if __name__ == "__main__":
    raise SystemExit(main())
