#!/usr/bin/env python3
"""Create the twelfth quality-checked 100-skill batch on Kubernetes operations."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from skill_categories import category_for_skill
from skill_taxonomy import relative_skill_path, skill_path

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "skills"
README = ROOT / "README.md"
INDEX = ROOT / "INDEX.md"
README_MARKER = "| Skill | Use it for |"
INDEX_MARKER = "| If the task is about… | Load |"

SOURCES = {
    "production": ("Kubernetes production environment guidance", "https://kubernetes.io/docs/setup/production-environment/"),
    "etcd": ("Kubernetes etcd operations guidance", "https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/"),
    "upgrade": ("Kubernetes kubeadm upgrade guidance", "https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/"),
    "deprecation": ("Kubernetes deprecated API migration guide", "https://kubernetes.io/docs/reference/using-api/deprecation-guide/"),
    "certificates": ("Kubernetes PKI certificates and requirements", "https://kubernetes.io/docs/setup/best-practices/certificates/"),
    "resources": ("Kubernetes resource management guidance", "https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/"),
    "scheduler": ("Kubernetes scheduler guidance", "https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/"),
    "priority": ("Kubernetes pod priority and preemption guidance", "https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/"),
    "topology": ("Kubernetes pod topology spread constraints", "https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/"),
    "taints": ("Kubernetes taints and tolerations guidance", "https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/"),
    "drain": ("Kubernetes safely drain a node", "https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/"),
    "pdb": ("Kubernetes PodDisruptionBudget guidance", "https://kubernetes.io/docs/tasks/run-application/configure-pdb/"),
    "deployment": ("Kubernetes Deployment guidance", "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/"),
    "probes": ("Kubernetes container probe guidance", "https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/"),
    "lifecycle": ("Kubernetes Pod lifecycle guidance", "https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/"),
    "statefulset": ("Kubernetes StatefulSet guidance", "https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/"),
    "jobs": ("Kubernetes Job guidance", "https://kubernetes.io/docs/concepts/workloads/controllers/job/"),
    "cronjobs": ("Kubernetes CronJob guidance", "https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/"),
    "storage": ("Kubernetes persistent volume guidance", "https://kubernetes.io/docs/concepts/storage/persistent-volumes/"),
    "snapshots": ("Kubernetes volume snapshot guidance", "https://kubernetes.io/docs/concepts/storage/volume-snapshots/"),
    "quotas": ("Kubernetes resource quota guidance", "https://kubernetes.io/docs/concepts/policy/resource-quotas/"),
    "security": ("Kubernetes security checklist", "https://kubernetes.io/docs/concepts/security/security-checklist/"),
    "rbac": ("Kubernetes RBAC good practices", "https://kubernetes.io/docs/concepts/security/rbac-good-practices/"),
    "serviceaccounts": ("Kubernetes service account guidance", "https://kubernetes.io/docs/concepts/security/service-accounts/"),
    "secrets": ("Kubernetes Secret security guidance", "https://kubernetes.io/docs/concepts/configuration/secret/"),
    "podsecurity": ("Kubernetes Pod Security Admission guidance", "https://kubernetes.io/docs/concepts/security/pod-security-admission/"),
    "admission": ("Kubernetes admission controller guidance", "https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/"),
    "network": ("Kubernetes NetworkPolicy guidance", "https://kubernetes.io/docs/concepts/services-networking/network-policies/"),
    "service": ("Kubernetes Service guidance", "https://kubernetes.io/docs/concepts/services-networking/service/"),
    "ingress": ("Kubernetes Ingress controller guidance", "https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/"),
    "gateway": ("Kubernetes Gateway API overview", "https://kubernetes.io/docs/concepts/services-networking/gateway/"),
    "hpa": ("Kubernetes Horizontal Pod Autoscaler guidance", "https://kubernetes.io/docs/concepts/workloads/autoscaling/horizontal-pod-autoscale/"),
    "vpa": ("Kubernetes Vertical Pod Autoscaler guidance", "https://kubernetes.io/docs/concepts/workloads/autoscaling/vertical-pod-autoscale/"),
    "images": ("Kubernetes container image guidance", "https://kubernetes.io/docs/concepts/containers/images/"),
    "runtimeclass": ("Kubernetes RuntimeClass guidance", "https://kubernetes.io/docs/concepts/containers/runtime-class/"),
    "coredns": ("Kubernetes DNS debugging guidance", "https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/"),
    "configmaps": ("Kubernetes ConfigMap guidance", "https://kubernetes.io/docs/concepts/configuration/configmap/"),
    "observability": ("Kubernetes observability guidance", "https://kubernetes.io/docs/concepts/cluster-administration/observability/"),
    "audit": ("Kubernetes auditing guidance", "https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/"),
}

# slug | title | focus | method | evidence checks | domain guardrail | source key
RAW = r"""kubernetes-control-plane-ha-failure-domain-review|Kubernetes Control Plane HA Failure-Domain Review|reviewing whether control-plane replicas and dependencies survive a defined zone or host failure|Map API-server instances, etcd members, endpoints, load balancers, DNS, certificates, and provider-managed components to their failure domains. Evaluate a bounded single-domain-loss scenario against recovery objectives and document unmanaged dependencies.|Check quorum, endpoint health, placement constraints, management-plane dependencies, and what remains reachable during the scenario.|Do not change production topology or etcd membership without an approved backup, maintenance plan, and cluster-owner authorization.|production
kubernetes-apiserver-load-balancer-failover-test|Kubernetes API Server Load-Balancer Failover Test|testing API-server endpoint continuity when one control-plane backend becomes unavailable|Record the configured endpoint and health-check behavior, then test backend removal and restoration in a task-owned staging environment. Observe authenticated read and harmless discovery requests through the same client path used by operators.|Check DNS caching, health-check timing, certificate name coverage, reconnect behavior, and whether writes resume after recovery.|Do not disable production API-server backends or send test mutations without an approved change window.|production
kubernetes-etcd-snapshot-restore-rehearsal|Kubernetes etcd Snapshot Restore Rehearsal|rehearsing recovery of Kubernetes control-plane state from an authorized etcd snapshot|Verify snapshot provenance, etcd version, encryption, and access controls; restore only into a disposable isolated environment and compare selected synthetic objects with a baseline inventory.|Check restore-tool compatibility, member configuration, data consistency, secret exposure, and a measured recovery time.|Never restore over a live cluster or export sensitive snapshots without explicit owner approval.|etcd
kubernetes-etcd-quorum-maintenance-window-plan|Kubernetes etcd Quorum Maintenance-Window Plan|planning a maintenance sequence that preserves etcd quorum and control-plane write availability|Inventory member count, health, failure domains, version skew, and maintenance dependencies. Simulate one member unavailable at a time and define stop conditions before scheduling sequential work.|Check quorum margin, snapshot freshness, disk and network health, leadership changes, and whether the control plane can still accept writes.|Do not parallelize member restarts or change etcd membership based on a generic replica-count rule.|etcd
kubernetes-minor-upgrade-version-skew-preflight|Kubernetes Minor Upgrade Version-Skew Preflight|checking whether a proposed Kubernetes minor upgrade follows supported component-version sequencing|Record control-plane, kubelet, kubeadm, kubectl, etcd, and add-on versions against the current version-skew policy. Build a node-by-node sequence that does not skip unsupported minor releases.|Check release notes, package source, deprecated APIs, control-plane ordering, backup readiness, and workload disruption budgets.|Do not apply an upgrade or skip a minor release based on an unverified compatibility assumption.|upgrade
kubernetes-addon-version-compatibility-matrix|Kubernetes Add-on Version Compatibility Matrix|mapping add-on compatibility before a Kubernetes cluster upgrade|Inventory CNI, CSI, CoreDNS, metrics, ingress, admission, and policy components with installed versions, supported server range, API dependencies, and upgrade owner. Compare each against current project and provider release guidance.|Check CRDs, webhooks, rollback support, feature gates, node images, and documented upgrade order.|Do not upgrade a cluster-wide add-on or infer support from an unmaintained compatibility table.|production
kubernetes-deprecated-api-manifest-inventory|Kubernetes Deprecated API Manifest Inventory|finding deprecated or removed API versions in manifests and deployment tooling|Scan the approved source tree and rendered configuration using version-aware discovery, then map each finding to the cluster release where the API is removed. Keep source files and generated output distinguishable.|Check Helm or Kustomize output, operator-generated objects, API clients, CRDs, and whether a warning reflects served versus stored objects.|Do not rewrite manifests automatically without reviewing schema changes and the owning application tests.|deprecation
kubernetes-cluster-certificate-expiry-inventory|Kubernetes Cluster Certificate Expiry Inventory|creating an expiry and ownership inventory for Kubernetes control-plane and node certificates|Use approved read-only metadata to identify certificate purpose, issuer, subject, SANs, expiration, rotation mechanism, owner, and dependency. Store no private key material in the inventory.|Check API-server, etcd, kubelet, front-proxy, client, and external-CA cases; verify clock accuracy and alert lead time.|Do not export private keys, replace certificates, or disclose sensitive certificate files during inventory work.|certificates
kubernetes-control-plane-certificate-rotation-readiness|Kubernetes Control Plane Certificate Rotation Readiness|assessing prerequisites for a planned Kubernetes control-plane certificate rotation|Map each certificate consumer, trust bundle, expiry, renewal path, and restart dependency. Test the proposed order against a staging control plane and retain a documented recovery point.|Check SAN and issuer continuity, API-server-to-etcd and API-server-to-kubelet paths, external CAs, and managed-cluster constraints.|Do not rotate live certificate authorities or private keys without the credential owner and provider approving the sequence.|certificates
kubernetes-cluster-decommission-resource-reconciliation|Kubernetes Cluster Decommission Resource Reconciliation|preparing a cluster retirement inventory before any infrastructure is removed|Reconcile namespaces, workloads, operators, persistent volumes, snapshots, load balancers, DNS, identity bindings, monitoring, and external integrations to named owners. Separate retained evidence from resources proposed for retirement.|Check orphaned cloud resources, backup restore evidence, data retention obligations, credentials, and consumer cutover completion.|Do not delete cluster resources, disks, snapshots, or identities; present a reviewed retirement plan for owner approval.|production
kubernetes-node-pool-capacity-headroom-review|Kubernetes Node-Pool Capacity Headroom Review|checking whether node pools can absorb expected workload growth and a planned node loss|Compare allocatable CPU, memory, ephemeral storage, extended resources, and current requests with workload demand and the declared failure scenario. Model capacity per pool and zone rather than relying on cluster-wide totals.|Check system reservations, DaemonSet overhead, scheduling constraints, autoscaler limits, and workload burst patterns.|Do not resize a production node pool or overcommit an availability target without capacity-owner approval.|resources
kubernetes-kubelet-system-reserved-budget-audit|Kubernetes Kubelet System-Reserved Budget Audit|reviewing whether node reservations leave realistic capacity for operating-system and Kubernetes daemons|Compare kubelet reservations, allocatable capacity, observed system use, eviction thresholds, and workload requests across representative node classes. Record whether configuration is inherited from the provider or locally managed.|Check CPU, memory, ephemeral storage, system-reserved and kube-reserved settings, and the effect on scheduling.|Do not edit node-level kubelet configuration outside an approved node-image or cluster-management process.|resources
kubernetes-node-pressure-eviction-evidence-triage|Kubernetes Node-Pressure Eviction Evidence Triage|classifying pod evictions caused by node memory, disk, or inode pressure|Correlate Pod events, node conditions, kubelet signals, container requests, QoS class, and time-series evidence around a bounded incident window. Identify whether the cause is capacity, noisy-neighbor use, or an incorrect request.|Check eviction thresholds, image and log growth, ephemeral volumes, system daemons, and workload replacement behavior.|Do not delete diagnostic evidence or raise thresholds to suppress alerts without an approved risk assessment.|resources
kubernetes-pod-topology-spread-failure-domain-review|Kubernetes Pod Topology-Spread Failure-Domain Review|reviewing how workload replicas are distributed across zones or other topology domains|Map the Pod selector, topology labels, eligible domains, max skew, min domains, and unsatisfiable behavior. Test placement with the actual replica and node-pool counts in a non-production cluster.|Check missing topology labels, taints, autoscaling, rollout surge, small replica counts, and whether strict spreading can strand Pods.|Do not claim zone resilience from a spread constraint unless the cluster actually has independent eligible domains.|topology
kubernetes-zone-failure-pod-placement-resilience-test|Kubernetes Zone-Failure Pod-Placement Resilience Test|testing whether critical workloads can be rescheduled after one availability zone is unavailable|Define the failure scenario and target workloads, then model schedulable capacity and storage reachability outside the affected zone. Use a controlled staging fault or a read-only simulation before any real disruption.|Check replicas, topology spread, anti-affinity, local storage, load-balancer health, and provider control-plane behavior.|Do not cordon or remove production zone capacity without explicit incident or maintenance authorization.|production
kubernetes-pod-antiaffinity-capacity-cost-assessment|Kubernetes Pod Anti-Affinity Capacity-Cost Assessment|evaluating whether hard or preferred pod anti-affinity matches an availability goal|Trace selectors, topology keys, required and preferred rules, current node count, and expected scale. Compare feasible placements and unused capacity under normal and degraded scenarios.|Check selector breadth, zone exhaustion, scheduling latency, autoscaler response, and interaction with topology spread.|Do not make a hard placement rule the default without testing capacity loss and owner acceptance.|scheduler
kubernetes-taint-toleration-scope-audit|Kubernetes Taint and Toleration Scope Audit|checking whether workload tolerations unintentionally admit Pods to restricted or drained nodes|Inventory node taints and Pod tolerations by namespace, workload owner, key, effect, operator, and duration. Trace broad empty-key or wildcard tolerations to the workloads that actually require them.|Check NoSchedule versus NoExecute behavior, DaemonSets, node-name bypasses, and maintenance-taint exceptions.|Do not remove an operational toleration or add a broad one without testing system and workload placement.|taints
kubernetes-priorityclass-preemption-policy-review|Kubernetes PriorityClass Preemption-Policy Review|reviewing whether workload priority can evict lower-priority workloads or starve peers|Map PriorityClass values, preemption policy, namespace permissions, quota controls, and the service criticality that justifies each class. Simulate scheduling pressure using synthetic workloads.|Check highest-priority access, non-preempting options, preemption victims, and fairness across teams.|Do not grant high priority or preemption rights as a shortcut around capacity shortages.|priority
kubernetes-unschedulable-pod-event-root-cause-triage|Kubernetes Unschedulable Pod Event Root-Cause Triage|diagnosing why a pending Pod has no feasible node|Capture the Pod request, node allocatable state, scheduler events, affinity, topology, taints, volumes, and extended-resource requirements. Separate filter failures from scoring preferences before proposing a change.|Check quota admission, PVC topology, node selectors, priority, image pulls, and scheduler version or profile.|Do not lower resource or security constraints merely to force placement without confirming the workload requirement.|scheduler
kubernetes-node-drain-capacity-preflight|Kubernetes Node-Drain Capacity Preflight|checking whether workloads can fit elsewhere before an authorized node drain|List workloads and DaemonSets on the target node, calculate replacement requests against healthy eligible nodes, and identify PDB or local-storage constraints. Record the exact drain scope and recovery steps.|Check replacement schedulability, autoscaler delay, disruption budgets, unmanaged Pods, and post-maintenance uncordon ownership.|Do not drain or power off a production node until the cluster owner approves the window and capacity evidence.|drain
kubernetes-daemonset-node-coverage-reconciliation|Kubernetes DaemonSet Node-Coverage Reconciliation|checking that required node-level agents run on every eligible node and only intended nodes|Compare DaemonSet selectors, tolerations, node affinity, desired/current/ready counts, and the fleet inventory. Distinguish intentionally excluded node classes from scheduling failures.|Check control-plane taints, newly added pools, architecture labels, rollout status, and resource pressure.|Do not broaden privileged node-agent coverage or change tolerations without security and platform-owner review.|production
kubernetes-pdb-drain-deadlock-diagnosis|Kubernetes PDB Drain-Deadlock Diagnosis|diagnosing a node drain blocked by a PodDisruptionBudget or unhealthy selected Pods|Map the PDB selector to live Pods and owning controllers, then compare desired replicas, healthy replicas, disruption allowance, and concurrent maintenance. Identify whether a stale or overly strict budget is the actual blocker.|Check empty selectors, percentage rounding, unhealthy eviction policy, overlapping maintenance, and single-replica workloads.|Do not delete or weaken a production PDB merely to make a drain finish; obtain service-owner approval and a recovery plan.|pdb
kubernetes-deployment-rollout-surge-budget-review|Kubernetes Deployment Rollout-Surge Budget Review|setting Deployment surge and unavailable limits against capacity and service availability|Calculate peak old-plus-new Pod demand for the chosen maxSurge and maxUnavailable settings. Compare readiness time, node headroom, replicas, traffic capacity, and failure-domain spread.|Check integer versus percentage rounding, quota, anti-affinity, slow image pulls, and autoscaler reaction time.|Do not promise zero downtime from rolling-update settings alone; verify application and load-balancer behavior.|deployment
kubernetes-stalled-rollout-condition-triage|Kubernetes Stalled Deployment Rollout Condition Triage|finding the blocking condition in a Deployment that is not progressing|Inspect Deployment conditions, ReplicaSets, Pod events, readiness, image state, quota, and scheduler outcomes. Build a causal sequence from the first failed transition rather than treating the final timeout as the root cause.|Check progress deadlines, admission rejection, probe configuration, surge capacity, and template changes during rollout.|Do not force a rollout or delete old replicas until the service owner approves the recovery action.|deployment
kubernetes-canary-promotion-evidence-gate|Kubernetes Canary Promotion Evidence Gate|deciding whether a staged Kubernetes canary has enough evidence for promotion|Define cohort, traffic split mechanism, success metrics, minimum observation period, abort threshold, and comparison baseline. Collect version-tagged telemetry and verify the canary receives the intended traffic.|Check sample size, skewed traffic, error budgets, dependency changes, and whether rollback returns traffic as well as Pods.|Do not promote or shift production traffic without explicit release-owner approval.|service
kubernetes-blue-green-service-selector-cutover-test|Kubernetes Blue-Green Service-Selector Cutover Test|testing whether a Service selector change routes traffic to exactly the intended blue or green Pods|Resolve selectors to EndpointSlices before and after a staging cutover, then exercise health checks, persistent connections, and rollback. Keep manifests and endpoint evidence tied to one release identifier.|Check stale labels, mixed revisions, readiness gates, session affinity, and service-port mapping.|Do not point a production Service at a new color without an approved cutover and rollback window.|service
kubernetes-deployment-rollback-state-reconciliation|Kubernetes Deployment Rollback-State Reconciliation|checking whether a Deployment rollback restores a coherent application configuration|Compare prior and current Pod templates, image digests, ConfigMaps, Secrets references, database compatibility, and external dependencies. Define what state remains changed after a controller revision rollback.|Check mutable image tags, config outside the template, irreversible schema changes, and revision-history retention.|Do not execute rollback against production or imply it reverses external data changes without owner approval.|deployment
kubernetes-readiness-probe-traffic-gating-audit|Kubernetes Readiness-Probe Traffic-Gating Audit|checking whether readiness signals correctly control traffic eligibility for a workload|Map the readiness condition to the Service endpoint path and test startup, dependency failure, recovery, and shutdown in a representative environment. Confirm a not-ready Pod is removed from normal service routing.|Check probe path and port, startup sequencing, readiness gates, success thresholds, and external load-balancer health checks.|Do not use readiness as a substitute for application-level SLO monitoring or hide real failures by weakening the probe.|probes
kubernetes-liveness-probe-false-positive-risk-check|Kubernetes Liveness-Probe False-Positive Risk Check|reviewing whether a liveness probe might restart a slow or overloaded but recoverable container|Compare probe timeout and failure thresholds with observed startup, scheduling pauses, dependency waits, and CPU throttling. Use a controlled failure test to distinguish a deadlock from transient latency.|Check probe load, shared health endpoints, synchronized restarts, and whether restarting loses important work.|Do not increase thresholds or disable liveness on a live service without evidence and service-owner approval.|probes
kubernetes-startup-probe-warmup-budget-validation|Kubernetes Startup-Probe Warmup Budget Validation|validating whether a startup probe budget covers realistic application initialization|Measure cold-start phases across representative images, node conditions, and data volume. Compare the measured distribution with the configured probe period, timeout, and failure threshold.|Check image pull time, init containers, cache warm-up, resource throttling, and restart behavior after a failed startup probe.|Do not stretch startup budgets to mask a reproducible initialization failure or an unhealthy dependency.|probes
kubernetes-termination-grace-period-sequence-test|Kubernetes Termination Grace-Period Sequence Test|testing whether a workload finishes requests and releases resources before Pod termination|Exercise graceful shutdown in a disposable deployment while recording termination signals, endpoint removal, in-flight work, and process exit. Compare measured shutdown duration with the configured grace period.|Check preStop time consumption, connection draining, child processes, forced kill timing, and disruption during rollout or drain.|Do not reduce a production grace period until data-loss and request-abort consequences are reviewed.|lifecycle
kubernetes-prestop-hook-idempotency-review|Kubernetes PreStop Hook Idempotency Review|reviewing whether a Pod preStop action is safe across retries, delayed shutdown, and partial failure|Trace hook side effects and termination ordering, then run the hook repeatedly against a disposable fixture with interrupted execution. Record what happens if the application exits before or during the hook.|Check external API writes, credential use, timeout behavior, duplicate cleanup, and interaction with the termination grace period.|Do not make a lifecycle hook perform irreversible external changes without idempotency and owner review.|lifecycle
kubernetes-statefulset-quorum-rollout-readiness|Kubernetes StatefulSet Quorum Rollout Readiness|checking whether a stateful application can preserve its own quorum during a StatefulSet update|Document ordinal identity, application quorum, readiness meaning, update strategy, minReadySeconds, storage claims, and recovery behavior. Test one replica transition at a time using a representative non-production cluster.|Check ordered termination, application leader election, readiness false positives, persistent volume attachment, and PDB interaction.|Do not infer application quorum safety from Kubernetes replica count or advance a production rollout without the application owner.|statefulset
kubernetes-statefulset-partitioned-canary-plan|Kubernetes StatefulSet Partitioned Canary Plan|planning a staged StatefulSet update using ordinal partitions and explicit observation gates|Choose the canary ordinal, expected version, health evidence, promotion threshold, and rollback path. Validate controller behavior with the current cluster version and a disposable StatefulSet before relying on a partition.|Check ordinal ordering, update revision, pod deletion behavior, storage identity, and whether lower ordinals remain on the prior template.|Do not lower the partition or delete stateful Pods in production without an approved change plan.|statefulset
kubernetes-job-backoff-retry-budget-review|Kubernetes Job Backoff and Retry-Budget Review|setting retry behavior for a Kubernetes Job whose task can fail transiently or permanently|Classify failure modes, idempotency, run cost, and expected duration. Compare backoffLimit, restartPolicy, parallelism, and completion goals with a synthetic failure test.|Check duplicate side effects, active deadlines, failed Pod retention, dependency outage amplification, and partial results.|Do not increase retries for a non-idempotent job until duplicate execution is safe and bounded.|jobs
kubernetes-cronjob-overlap-concurrency-policy|Kubernetes CronJob Overlap and Concurrency-Policy Review|choosing how scheduled Jobs behave when a prior run is still active or missed|Compare schedule cadence, worst-case duration, idempotency, catch-up tolerance, starting deadline, and Allow, Forbid, or Replace behavior. Simulate delayed and overlapping executions in a test namespace.|Check missed schedules, controller reconciliation delay, multiple CronJobs, suspend/resume, and job cleanup history.|Do not choose Replace or replay missed runs without confirming that cancellation and duplicate effects are safe.|cronjobs
kubernetes-job-deadline-partial-output-test|Kubernetes Job Deadline and Partial-Output Test|testing what a Kubernetes Job leaves behind when it reaches a deadline or completes only some work|Use synthetic records and bounded parallelism to force a timeout or worker failure. Determine which outputs are committed, how completion is reported, and how a rerun resumes or deduplicates.|Check activeDeadlineSeconds, backoff, completion mode, temporary files, side effects, and consumers that may treat partial output as complete.|Do not publish or consume partial production output as a successful result without explicit completeness metadata.|jobs
kubernetes-workload-selector-ownership-collision-check|Kubernetes Workload Selector Ownership-Collision Check|detecting overlapping selectors that can cause controllers to adopt or compete over Pods|Inventory workload selectors and Pod labels within the relevant namespace, then identify intersections across Deployments, ReplicaSets, StatefulSets, Services, and PDBs.|Check generated labels, immutable selectors, shared template labels, migration overlap, and tests against rendered manifests.|Do not edit an immutable or production selector until ownership and replacement behavior are understood.|deployment
kubernetes-pvc-pending-binding-root-cause-triage|Kubernetes PVC Pending-Binding Root-Cause Triage|diagnosing a PersistentVolumeClaim that remains unbound or prevents a Pod from scheduling|Compare the claim request, access mode, StorageClass, provisioner health, topology, capacity, and matching PV state. Correlate claim events with the consuming Pod's scheduling events.|Check default-class assumptions, WaitForFirstConsumer behavior, quota, CSI controller availability, and node affinity.|Do not delete and recreate a production claim or bound volume as a speculative repair.|storage
kubernetes-storageclass-default-change-impact-review|Kubernetes StorageClass Default-Change Impact Review|assessing workloads affected by changing or removing a default StorageClass|Inventory PVCs with explicit and implicit classes, dynamic provisioners, reclaim policies, and namespace owners. Model new-claim behavior separately from already-bound volumes.|Check multiple default classes, provider-specific parameters, volume binding mode, expansion support, and fallback behavior.|Do not replace a production default class until affected owners and stateful services approve the migration.|storage
kubernetes-pv-reclaim-policy-data-retention-check|Kubernetes PersistentVolume Reclaim-Policy Data-Retention Check|verifying what happens to backing storage when a claim or workload is removed|Trace each PV's claim, provisioner, reclaim policy, snapshot/backup reference, and data owner. Use a disposable claim to demonstrate the observed lifecycle where safe.|Check Delete versus Retain semantics, finalizers, manual reclamation steps, and provider-side retention controls.|Do not delete a PVC, PV, or storage asset to test retention on real data.|storage
kubernetes-pvc-expansion-failure-recovery-plan|Kubernetes PVC Expansion Failure Recovery Plan|planning a safe response when a supported persistent-volume claim expansion stalls or fails|Record the requested size, StorageClass capability, CSI events, filesystem state, and application write load. Determine whether the backend, controller, node-side filesystem, or workload restart blocks expansion.|Check online expansion support, filesystem type, requested capacity, provider limits, and retry or recovery guidance.|Do not shrink a claim or detach a live production volume as an exploratory step.|storage
kubernetes-volume-snapshot-application-consistency-validation|Kubernetes Volume-Snapshot Application-Consistency Validation|checking whether a storage snapshot captures a usable application recovery point|Map snapshot-controller and CSI-driver support, application write activity, quiesce or checkpoint mechanism, and consistency expectations. Restore the snapshot in isolation and run application-level integrity checks.|Check snapshot readiness, multi-volume coordination, topology, deletion policy, and whether the data layer needs its own backup process.|Do not call a crash-consistent storage snapshot application-consistent without successful restore evidence.|snapshots
kubernetes-pvc-restore-integrity-rehearsal|Kubernetes PVC Restore Integrity Rehearsal|rehearsing restoration of a persistent-volume claim from an approved snapshot or backup|Restore into an isolated claim with a separate name and namespace, verify expected object identity, and run integrity checks against synthetic or approved data. Measure recovery time and document dependencies.|Check CSI support, storage topology, access modes, restored ownership, application startup, and rollback isolation.|Do not overwrite the source claim or expose restored sensitive data to an unapproved workload.|snapshots
kubernetes-stateful-volume-zone-placement-review|Kubernetes Stateful Volume Zone-Placement Review|checking whether stateful Pods can be scheduled where their bound storage is accessible|Compare PV node affinity, StorageClass binding mode, allowed topologies, Pod placement rules, and eligible node capacity. Simulate scale, reschedule, and zone-loss cases without detaching production storage.|Check delayed binding, cross-zone replication assumptions, scheduler events, CSI topology labels, and restore options.|Do not move or rebind a production volume to satisfy a placement test without provider and data-owner approval.|storage
kubernetes-volume-multiattach-contention-diagnosis|Kubernetes Volume Multi-Attach Contention Diagnosis|diagnosing a Pod blocked because a volume is already attached or mounted elsewhere|Trace the claim, PV, access mode, prior and current Pod UIDs, node assignment, CSI attachment objects, and detach events. Separate a legitimate single-writer constraint from stale attachment state.|Check StatefulSet identity, node failure, forced detach policy, storage-driver events, and application write consistency.|Do not force-detach a production volume or start a second writer without storage-owner approval.|storage
kubernetes-csi-driver-version-compatibility-audit|Kubernetes CSI Driver Version-Compatibility Audit|checking whether an installed CSI driver and sidecars support the cluster and storage features in use|Inventory driver and sidecar images, supported Kubernetes range, CRDs, feature gates, node plugins, and provisioned StorageClasses. Compare with the driver's current official compatibility documentation.|Check controller/node component parity, snapshotter support, expansion, topology, security fixes, and rollback limitations.|Do not upgrade a storage driver or assume snapshot and expansion capabilities from the CSI standard alone.|storage
kubernetes-ephemeral-storage-eviction-budget-review|Kubernetes Ephemeral-Storage Eviction-Budget Review|reviewing local ephemeral storage requests, limits, and eviction exposure for a workload|Measure writable layers, logs, emptyDir use, and temporary files across a representative peak. Compare requests and limits with node allocatable capacity and expected retention.|Check inode exhaustion, log rotation, image garbage collection, emptyDir size limits, and node pressure signals.|Do not delete application files or raise node thresholds without the owner and data-retention review.|resources
kubernetes-rbac-wildcard-permission-reduction|Kubernetes RBAC Wildcard-Permission Reduction|identifying Kubernetes RBAC wildcard grants that create unnecessary current or future access|Export role rules and bindings through an approved read-only path, resolve subjects and namespaces, and compare every granted verb and resource with the task each principal must perform.|Check API groups, subresources, future CRDs, secret read/list/watch access, impersonation, and cluster-admin bindings.|Do not remove permissions or alter break-glass access without an owner-approved test and recovery path.|rbac
kubernetes-namespace-rolebinding-expiry-review|Kubernetes Namespace RoleBinding Review-Date and Expiry Governance|reviewing namespace-scoped access grants for current ownership, least privilege, and human-enforced review dates|Map each RoleBinding subject to a current owner, purpose, scope, review date, and removal process. Treat expiration as an external governance control rather than a built-in RoleBinding feature. Compare bindings with group membership and workload service accounts using authorized metadata only.|Check stale human identities, cross-namespace subjects, aggregated roles, wildcard rules, and the effective permissions of built-in roles.|Do not revoke access or infer identity status from display names alone; route changes to the access owner.|rbac
kubernetes-serviceaccount-automount-scope-review|Kubernetes ServiceAccount Automount-Scope Review|checking whether Pods receive API credentials they do not need|Inventory service-account assignments and automount settings, then trace each workload's actual Kubernetes API calls and token mounts. Test a synthetic workload with token mounting disabled where it is expected to be unnecessary.|Check namespace defaults, controller-created Pods, projected volumes, image-pull credentials, and external identity use.|Do not remove a token from a controller or application that depends on it until its owner validates behavior.|serviceaccounts
kubernetes-projected-token-audience-expiry-validation|Kubernetes Projected ServiceAccount Token Audience and Expiry Validation|checking that projected workload identity tokens are scoped and expire as intended|Record token audience, requested lifetime, projected-volume path, relying-party trust, and rotation behavior without printing token contents. Test acceptance and rejection with a non-production identity provider.|Check audience mismatch, token refresh, legacy long-lived secrets, clock skew, and whether downstream verifiers validate issuer and expiration.|Never copy a live bearer token into logs, tickets, prompts, or external tools.|serviceaccounts
kubernetes-workload-identity-trust-boundary-audit|Kubernetes Workload Identity Trust-Boundary Audit|reviewing how a Kubernetes workload identity is trusted by an external service|Map the Kubernetes namespace and service account, issuer, subject, audience, external trust rule, and permitted cloud actions. Verify the trust chain with a synthetic principal and least-privilege policy.|Check namespace reuse, wildcard subjects, token projection, provider metadata access, credential fallback, and revocation behavior.|Do not request, print, or use real cloud credentials outside the approved identity test.|serviceaccounts
kubernetes-pod-security-admission-staged-enforcement|Kubernetes Pod Security Admission Staged-Enforcement Plan|planning a namespace rollout from warning or audit mode to Pod Security enforcement|Inventory workload templates and current violations, select a version-pinned policy level, and stage warn/audit observation before enforcing in a representative namespace. Record exception owner and expiry.|Check direct Pods and controller templates, system namespaces, exemptions, admission metrics, and the target Kubernetes version.|Do not enforce a new policy cluster-wide before affected owners and platform operators review the impact.|podsecurity
kubernetes-securitycontext-capability-minimization|Kubernetes SecurityContext Capability-Minimization Review|reducing Linux privileges and capabilities requested by a container|Inspect Pod and container security contexts, image entrypoints, required filesystem writes, UID/GID behavior, and the smallest capability set needed. Verify proposed restrictions with functional tests in an isolated namespace.|Check privileged mode, host namespaces, privilege escalation, read-only root filesystem, seccomp, and init or ephemeral containers.|Do not remove a required capability from production based only on static manifest appearance.|podsecurity
kubernetes-privileged-workload-exception-register|Kubernetes Privileged-Workload Exception Register|recording and governing workloads that need a privileged or host-level exception|For each exception, record workload owner, namespace, host access, business need, nodes, compensating isolation, approval, validation evidence, and review/expiry date. Compare the running Pod with the reviewed template.|Check DaemonSets, hostPath, hostNetwork, hostPID, added capabilities, admission exemptions, and drift from the approved scope.|Do not create a new privileged workload or treat an exception record as authorization to deploy it.|security
kubernetes-secret-at-rest-encryption-verification|Kubernetes Secret-at-Rest Encryption Verification|verifying encryption-at-rest configuration for Kubernetes Secret objects|Review the provider or API-server configuration and encryption-provider status using approved metadata. Test expected behavior only in a disposable cluster with synthetic values; do not retrieve production secret contents.|Check active key ordering, encryption provider identity, migration status, backup encryption, and access to etcd snapshots.|Do not expose keys or secret values and do not rewrite production storage to test encryption without approval.|secrets
kubernetes-external-secret-provider-access-boundary|Kubernetes External Secret-Provider Access-Boundary Review|checking which workloads can retrieve secrets through an external provider integration|Map service account identity, provider role, namespace, secret path selectors, mount or sync mode, and rotation behavior. Use synthetic secret entries to test allowed and denied access.|Check broad provider scopes, namespace labels, node identity fallback, sync-to-Secret permissions, and secret material in logs or environment variables.|Do not query real secret values or change provider policy without the credential owner.|secrets
kubernetes-apiserver-public-exposure-review|Kubernetes API-Server Public-Exposure Review|assessing whether a Kubernetes API endpoint is reachable from unintended network locations|Use approved network inventory and provider configuration to map endpoint exposure, authorized CIDRs, identity controls, private paths, and emergency access. Validate with non-invasive connection metadata from approved test points.|Check load balancer rules, DNS records, bastion paths, client certificate or identity policy, and public IPv4/IPv6 exposure.|Do not probe public endpoints outside the approved scope or alter production firewall rules during assessment.|security
kubernetes-kubelet-api-authentication-reachability-check|Kubernetes Kubelet API Authentication and Reachability Check|checking whether kubelet endpoints are restricted to authenticated and authorized callers|Map node addresses, listener exposure, authentication and authorization settings, firewall paths, and control-plane access. Use provider configuration or a harmless authorized health check rather than requesting workload data.|Check anonymous access, read-only ports, proxy paths, Node authorizer use, and node-local network reachability.|Do not access container logs, exec, or node files unless separately authorized for that exact target.|security
kubernetes-cloud-metadata-egress-isolation-test|Kubernetes Cloud-Metadata Egress-Isolation Test|testing whether Pods can reach a cloud metadata endpoint they should not use|Define a task-owned test Pod and approved network path, then verify expected allow/deny outcomes without requesting credentials or metadata values. Review workload identity as the intended alternative.|Check CNI NetworkPolicy enforcement, host networking, node exceptions, IPv4/IPv6 paths, and provider-specific metadata protections.|Do not retrieve tokens, instance credentials, or sensitive metadata as part of a reachability test.|network
kubernetes-default-deny-networkpolicy-coverage-audit|Kubernetes Default-Deny NetworkPolicy Coverage Audit|checking whether namespaces and workloads are covered by intended ingress and egress isolation|Inventory NetworkPolicies, selectors, policy types, namespace labels, and CNI enforcement support. Compare each protected workload with an allowlist of required peers and test expected traffic in staging.|Check uncovered Pods, additive rule union, node traffic exceptions, DNS dependencies, and gaps caused by unsupported CNI behavior.|Do not apply a default-deny policy to production without validating required traffic and approving a rollback plan.|network
kubernetes-dns-egress-allowlist-impact-test|Kubernetes DNS-Egress Allowlist Impact Test|testing whether restrictive egress rules preserve required cluster DNS resolution|Map the cluster DNS service, namespace policy, UDP/TCP behavior, search suffixes, and workload resolver path. In staging, test service names, external names, large responses, and retry behavior under the proposed allowlist.|Check CoreDNS endpoints, node-local DNS, IPv4/IPv6, TCP fallback, namespace selectors, and custom resolver configuration.|Do not block production DNS traffic or collect query payloads beyond the authorized test evidence.|network
kubernetes-admission-webhook-failure-policy-resilience-review|Kubernetes Admission-Webhook Failure-Policy Resilience Review|assessing how API writes behave when an admission webhook is slow or unavailable|Inventory webhook match scope, timeout, failure policy, service endpoints, certificates, network dependencies, and criticality. Simulate timeout and backend outage in an isolated cluster and record which requests fail open or closed.|Check namespace selectors, API-server request impact, webhook recursion, readiness, and emergency recovery ownership.|Do not change a production webhook to fail open or disable validation without explicit security and platform approval.|admission
kubernetes-validating-admission-policy-scope-regression-test|Kubernetes ValidatingAdmissionPolicy Scope Regression Test|testing whether an admission policy accepts intended objects and rejects prohibited ones|Translate the policy intent into positive, negative, boundary, and versioned fixture cases. Run them with server-side dry-run or an isolated API server and preserve the admitted/rejected object evidence.|Check namespace and object selectors, match conditions, failure behavior, exemptions, and interactions with other admission stages.|Do not weaken a production policy or apply an untested policy bundle to shared namespaces.|admission
kubernetes-image-digest-release-reproducibility-check|Kubernetes Image-Digest Release Reproducibility Check|confirming that a workload rollout uses the intended immutable container image content|Resolve each image reference to a digest in the approved release record and compare rendered templates, running Pod specs, and rollout revisions. Tie the evidence to the source commit and build artifact identity.|Check mutable tags, init and sidecar images, admission mutation, architecture-specific manifests, and rollback image availability.|Do not promote an image or claim artifact provenance from a tag name alone.|images
kubernetes-image-pull-credential-namespace-scope-audit|Kubernetes Image-Pull Credential Namespace-Scope Audit|reviewing which Pods and namespaces can use credentials to pull private images|Inventory imagePullSecrets, service-account references, registry hosts, and namespace distribution without decoding credential data. Trace which principals can create Pods that reference each credential.|Check copied secrets, default service accounts, cross-namespace assumptions, rotation ownership, and accidental credential exposure in manifests.|Do not reveal, decode, or rotate registry credentials during this audit.|secrets
kubernetes-hostnamespace-hostpath-policy-enforcement-test|Kubernetes Host-Namespace and HostPath Policy-Enforcement Test|testing whether admission policy blocks unauthorized host-level container access|Build synthetic Pod fixtures covering hostPath, hostNetwork, hostPID, hostIPC, host ports, privileged mode, and allowed exceptions. Verify the enforcement level and rejection evidence in an isolated namespace.|Check Pod Security level, webhook or policy bypasses, ephemeral containers, namespace labels, and provider-specific behavior.|Do not deploy a privileged test Pod on a production node or use host access to inspect unrelated workloads.|podsecurity
kubernetes-service-endpoint-readiness-mismatch-triage|Kubernetes Service Endpoint Readiness-Mismatch Triage|diagnosing a Service that routes to too few, stale, or unexpected backend endpoints|Compare Service selectors and ports with Pod labels, readiness, EndpointSlices, and client observations. Reproduce a harmless request from an approved test client and correlate it with endpoint state.|Check publishNotReadyAddresses, selectorless Services, named target ports, terminating endpoints, and controller lag.|Do not edit production selectors or send traffic to a backend that has not passed its readiness contract.|service
kubernetes-ingressclass-controller-ownership-audit|Kubernetes IngressClass Controller-Ownership Audit|identifying which controller reconciles each IngressClass and its attached routes|Inventory IngressClass controller identifiers, default-class annotations, installed controllers, namespace references, and ownership. Compare desired routing policy with each controller's actual configuration source.|Check multiple controllers, unclassified resources, provider annotations, class migration, and frozen Ingress API status.|Do not repoint a production class or controller without coordinating all route owners.|ingress
kubernetes-ingress-tls-secret-rotation-readiness|Kubernetes Ingress TLS Secret-Rotation Readiness|checking how an ingress controller observes and serves a rotated TLS Secret|Trace certificate and key ownership, Secret namespace, ingress references, controller reload behavior, and expiry monitoring. Validate the new certificate chain and hostname in a staging route before rotation.|Check controller cache behavior, secret read permissions, multiple hosts, rollback artifact, and whether rotation causes connection interruption.|Do not upload private keys to tickets or change a public certificate without the service owner.|ingress
kubernetes-gateway-api-migration-compatibility-map|Kubernetes Gateway API Migration Compatibility Map|mapping an Ingress or controller-specific route migration to supported Gateway API capabilities|Inventory current routes, annotations, controllers, GatewayClass ownership, cross-namespace references, TLS, and traffic policies. Map each behavior to a stable or implementation-specific Gateway API feature and a conformance test.|Check controller support matrix, route attachment permissions, fallback behavior, status conditions, and rollback compatibility.|Do not remove the existing production route until the new implementation passes functional and security tests.|gateway
kubernetes-externaltrafficpolicy-client-ip-behavior-test|Kubernetes ExternalTrafficPolicy Client-IP Behavior Test|testing how Service external traffic policy affects source IP preservation and node-level routing|Record Service type, externalTrafficPolicy, node-local endpoints, health-check path, load balancer, and client address expectation. Test approved requests through each relevant entry point.|Check Local versus Cluster behavior, source NAT, uneven endpoint distribution, health checks, and topology effects.|Do not change a public production Service policy without approval from networking and application owners.|service
kubernetes-coredns-failure-hotspot-investigation|Kubernetes CoreDNS Failure and Hotspot Investigation|diagnosing elevated DNS latency, SERVFAIL responses, or uneven CoreDNS load|Correlate DNS query outcomes, CoreDNS Pod health, request rates, node and zone placement, upstream latency, and client retry patterns. Use bounded synthetic queries and redacted metrics rather than capturing user query payloads.|Check Corefile changes, cache behavior, conntrack, node-local DNS, resource throttling, and IPv4/IPv6 paths.|Do not restart all production DNS replicas or expose internal query names in external reports without approval.|coredns
kubernetes-loadbalancer-external-exposure-review|Kubernetes LoadBalancer External-Exposure Review|checking whether Service load balancers expose only approved ports and addresses|Inventory external IPs, Service type, ports, source ranges, controller-specific annotations, DNS names, and business owner. Compare the observed exposure with the approved ingress design.|Check dual-stack addresses, stale services, health-check ports, default provider behavior, and unintended NodePort reachability.|Do not remove or create public load balancers without an approved traffic and rollback plan.|security
kubernetes-hpa-metric-suitability-denominator-review|Kubernetes HPA Metric-Suitability and Denominator Review|checking whether an HPA metric and target represent the workload's actual scaling pressure|Document metric source, selector, target type, resource requests, aggregation window, and expected replica response. Compare the signal with load-test or historical demand evidence.|Check missing requests, per-Pod versus object metrics, metric lag, denominator changes, stabilization policy, and minimum/maximum replicas.|Do not tune replica targets from a single noisy sample or use CPU percentage without verifying its request denominator.|hpa
kubernetes-hpa-missing-metric-request-diagnosis|Kubernetes HPA Missing-Metric and Request Diagnosis|diagnosing an HPA that reports unknown utilization or does not scale as expected|Trace target selector, Pod readiness, metric API availability, per-container resource requests, and HPA conditions. Reproduce the metric query through an approved test and compare it with the autoscaler's view.|Check sidecar requests, metrics-server health, custom metrics adapters, stale samples, and API-version compatibility.|Do not set arbitrary requests or force replica counts in production to conceal missing telemetry.|hpa
kubernetes-hpa-stabilization-window-flap-analysis|Kubernetes HPA Stabilization-Window Flap Analysis|reducing replica oscillation caused by noisy or delayed HPA signals|Align metric samples, scaling events, replica changes, workload latency, and stabilization policies. Test one policy change against a representative traffic replay or staging load.|Check scale-up and scale-down behavior separately, missing metrics, min/max caps, startup delays, and multiple autoscalers targeting one workload.|Do not damp scaling so aggressively that capacity cannot meet the service's recovery objective.|hpa
kubernetes-custom-metric-freshness-scaling-test|Kubernetes Custom-Metric Freshness Scaling Test|testing that a custom or external metric is fresh and correctly scoped before it drives scaling|Trace metric producer, adapter, resource selector, timestamp, aggregation, and HPA target. Inject known synthetic metric values in staging and verify the expected replica calculation and stale-data behavior.|Check missing series, cardinality, label collisions, adapter errors, cached values, and metric API permissions.|Do not let an unvalidated external metric trigger a production scale event.|hpa
kubernetes-vpa-recommendation-only-rollout-plan|Kubernetes VPA Recommendation-Only Rollout Plan|using VPA recommendations as evidence before automatically changing workload requests|Confirm VPA installation and target selector, collect recommendation bounds across representative load cycles, and compare them with requests, limits, quotas, and service objectives. Keep update mode recommendation-only while owners review proposed values.|Check metrics coverage, historical duration, OOM events, seasonal peaks, sidecars, and resource policy bounds.|Do not enable automatic eviction or apply a recommendation without capacity and service-owner review.|vpa
kubernetes-vpa-eviction-mode-disruption-risk-review|Kubernetes VPA Eviction-Mode Disruption-Risk Review|assessing Pod disruption before enabling a VPA update mode that recreates workloads|Map the VPA update mode and thresholds to replica count, PDB, readiness duration, startup cost, and node capacity. Test behavior on a staging workload and record which Pods may be evicted.|Check controller support, in-place capability, recommendation jumps, PDB interactions, and autoscaler response.|Do not enable an evicting VPA mode for a production workload without an approved maintenance and rollback plan.|vpa
kubernetes-resourcequota-object-count-admission-test|Kubernetes ResourceQuota Object-Count Admission Test|testing whether namespace object quotas block expected deployments or emergency recovery|Inventory hard and scoped quotas, current usage, workload rollout surge, and recovery objects. In a test namespace, submit representative creates and updates that exercise quota boundaries.|Check Pod, PVC, Service, Secret, and extended-resource counts; quota updates do not retroactively evict existing objects.|Do not raise or remove a production quota without capacity-owner approval and an updated fairness rationale.|quotas
kubernetes-limitrange-default-injection-impact-review|Kubernetes LimitRange Default-Injection Impact Review|checking how LimitRange defaults and bounds change newly admitted Pods or claims|Compare effective Pod resources before and after the proposed LimitRange in a disposable namespace. Render representative application templates and examine the admitted values rather than only the submitted manifests.|Check multiple LimitRanges, request-to-limit ratios, defaulted sidecars, PVC bounds, and interactions with ResourceQuota.|Do not treat namespace defaults as harmless; review their effect on scheduling and throttling before rollout.|resources
kubernetes-qos-class-eviction-outcome-analysis|Kubernetes QoS-Class Eviction-Outcome Analysis|evaluating how request and limit configuration affects Pod QoS and likely node-pressure eviction|Calculate the effective Pod requests and limits across all containers, then compare the resulting QoS class with observed usage and the declared service criticality.|Check sidecars, init-container resource accounting, memory overage, eviction evidence, and whether Guaranteed status is actually required.|Do not raise every request or limit to obtain a preferred class without modeling capacity impact.|resources
kubernetes-extended-resource-quota-fairness-audit|Kubernetes Extended-Resource Quota-Fairness Audit|reviewing namespace allocation and quotas for GPUs or other non-overcommittable resources|Map device-plugin resource names, allocatable counts, namespace quotas, workload requests, and allocation owner. Compare reserved, active, and unused capacity across teams using inventory metadata.|Check integer scheduling constraints, device health, topology, quota admission, and stale reservations.|Do not move or preempt a live accelerator workload without its owner and hardware operator approving the change.|quotas
kubernetes-api-audit-policy-coverage-map|Kubernetes API Audit-Policy Coverage Map|checking whether audit rules record security-relevant Kubernetes API actions at an appropriate level|Map threat questions to users, verbs, resources, subresources, namespaces, stages, audit levels, and backend retention. Use synthetic events to confirm representative allowed and denied actions are visible.|Check first-match rule ordering, request-body sensitivity, webhook or file backend health, API-server overhead, and protected resources.|Do not enable request-body capture for sensitive resources without a privacy, storage, and security review.|audit
kubernetes-apiserver-429-throttling-correlation|Kubernetes API-Server 429 Throttling Correlation|diagnosing API requests rejected or delayed by rate limiting or priority-and-fairness controls|Correlate client request rates, API-server metrics, FlowSchema/PriorityLevelConfiguration state, retry behavior, and control-plane load for a bounded interval. Separate client-side throttling from server responses.|Check watch bursts, controller retries, request priority, latency percentiles, and shared-cluster noisy neighbors.|Do not raise API-server limits or disable fairness controls without platform-owner approval and load evidence.|observability
kubernetes-control-plane-slo-signal-definition|Kubernetes Control-Plane SLO Signal Definition|defining measurable availability and latency signals for a Kubernetes control plane|Choose user-visible API operations, request classes, measurement source, evaluation window, and failure budget. Distinguish endpoint reachability from successful authorized reads and writes.|Check sampling gaps, control-plane component metrics, managed-provider boundaries, maintenance exclusions, and alert actionability.|Do not claim cluster availability from an API ping alone or set an SLO without service-owner agreement.|observability
kubernetes-cluster-metrics-cardinality-budget-review|Kubernetes Cluster-Metrics Cardinality-Budget Review|controlling metrics growth caused by high-cardinality labels from workloads and add-ons|Inventory top metric series by label set, identify churn sources, and estimate ingestion impact before changing scrape or relabel policy. Preserve the dimensions needed for diagnosis and service ownership.|Check pod UID labels, unbounded user identifiers, histogram buckets, control-plane coverage, and dropped-series effects.|Do not remove labels or sampling needed for incident response without monitoring-owner review.|observability
kubernetes-container-log-identity-redaction-retention|Kubernetes Container-Log Identity, Redaction, and Retention Review|checking whether aggregated workload logs retain enough attribution while minimizing sensitive content|Trace logs from container stream through node agent, parser, labels, backend, access groups, and retention. Use synthetic or redacted records to verify namespace, Pod, container, and workload identity.|Check multiline handling, restart boundaries, secrets and personal data, node log rotation, tenant filters, and deletion behavior.|Do not collect application payloads or lengthen retention without data-owner and privacy approval.|observability
kubernetes-event-correlation-evidence-pack|Kubernetes Event-Correlation Evidence Pack|building a time-bounded evidence record from Kubernetes events and object transitions|Select one incident window and resource set, preserve timestamps, involved object UIDs, reasons, reporters, and related status changes. Correlate events with logs and metrics while marking missing or expired evidence.|Check event TTL, clock skew, repeated aggregation, namespace scope, and whether a warning preceded the visible failure.|Do not treat an absent event as proof that a controller action did not occur.|observability
kubernetes-operator-reconcile-health-diagnostic|Kubernetes Operator Reconcile-Health Diagnostic|diagnosing an operator that is slow, stuck, or repeatedly reconciling the same custom resource|Map the custom resource generation, status conditions, controller logs, queue behavior, external dependencies, and owned objects for one bounded example. Compare desired versus observed state across reconcile attempts.|Check retry loops, idempotency, leader election, API conflicts, rate limits, and sensitive fields in controller logs.|Do not restart a shared operator or patch its managed resources before identifying the controller owner and recovery strategy.|observability
kubernetes-crd-schema-conversion-upgrade-test|Kubernetes CRD Schema-Conversion Upgrade Test|testing custom-resource schema and conversion behavior across an operator upgrade|Capture installed CRD versions, served and storage versions, conversion webhook, sample objects, and upgrade order. Exercise read, write, conversion, and rollback using synthetic resources in a disposable cluster.|Check stored-version migration, defaulting, pruning, webhook availability, and old controller compatibility.|Do not replace a production CRD or delete stored versions without a tested backup and owner-approved migration plan.|deprecation
kubernetes-crd-validation-defaulting-contract-check|Kubernetes CRD Validation and Defaulting Contract Check|verifying that a custom-resource schema rejects invalid inputs and preserves intended defaults|Create positive, negative, omitted-field, boundary, and unknown-field fixtures from the public CRD contract. Compare submitted and persisted objects using server-side dry-run or an isolated cluster.|Check structural schema, nullable fields, pruning, CEL rules, defaulting order, and compatibility with existing objects.|Do not tighten a shared CRD schema until existing custom resources and controller expectations have been evaluated.|admission
kubernetes-stuck-finalizer-resource-recovery-plan|Kubernetes Stuck-Finalizer Resource Recovery Plan|planning recovery when a custom or core resource remains terminating because a finalizer is not cleared|Identify the finalizer owner, controller state, external cleanup action, resource UID, and effect of finalizer removal. Reproduce with synthetic resources and specify a safe manual handoff if the controller is unavailable.|Check dependent infrastructure, repeated delete requests, controller logs, owner references, and orphan risk.|Do not strip finalizers from production objects as a shortcut; require the responsible controller and data owner to approve recovery.|observability
kubernetes-namespace-termination-finalizer-triage|Kubernetes Namespace-Termination Finalizer Triage|diagnosing a namespace that remains in Terminating state|Inspect namespace conditions, remaining namespaced resources, unavailable API services, discovery failures, and finalizers using approved read-only requests. Identify which controller or extension owns each blocker.|Check aggregated API health, custom-resource cleanup, terminating Pods, and resources hidden by failed discovery.|Do not force-finalize a namespace or remove its contents without a recovery plan and namespace-owner approval.|observability
kubernetes-orphan-ownerreference-inventory|Kubernetes Orphan OwnerReference Inventory|identifying objects whose owner references no longer resolve to a live controlling resource|Collect object kind, namespace, UID, owner UID, controller flag, and garbage-collection state. Classify likely intentional retention separately from true orphaning and map each candidate to an owner.|Check cross-namespace references, UID reuse, API discovery gaps, finalizers, and resources managed outside Kubernetes.|Do not delete orphan candidates automatically; produce an owner-reviewed reconciliation list.|observability
kubernetes-configmap-projection-reload-behavior-test|Kubernetes ConfigMap Projection Reload-Behavior Test|testing whether a workload observes ConfigMap updates through mounted files or environment values|Use a synthetic ConfigMap and disposable Pod to compare projected-volume refresh, application reload, and restart behavior. Tie the observed delay and stale-value window to the application contract.|Check subPath mounts, environment-variable snapshots, atomic-writer behavior, controller rollout triggers, and secret-like data mistakenly stored in ConfigMaps.|Do not edit production configuration or place confidential values in a ConfigMap during the test.|configmaps
kubernetes-image-registry-outage-cold-start-readiness|Kubernetes Image-Registry Outage Cold-Start Readiness|assessing whether workloads can start or recover when an image registry is unavailable|Inventory image references, cache state, pull policy, node replacement assumptions, registry dependencies, and recovery objectives. In a test environment, simulate unavailable registry access without changing production pull configuration.|Check digest pinning, image pre-pull policy, node churn, private registry authentication, rate limits, and cold-start capacity.|Do not bypass registry authentication or rely on cached images as a durable production recovery plan.|images
kubernetes-runtimeclass-node-compatibility-review|Kubernetes RuntimeClass and Node-Compatibility Review|checking whether a workload's RuntimeClass is available and appropriate on every eligible node|Map RuntimeClass handlers, scheduling constraints, node runtime support, overhead, and workload security requirements. Validate placement and a harmless startup test on each supported node class.|Check missing handlers, taints, architecture, overhead accounting, Pod Security policy, and runtime-specific limitations.|Do not switch runtime handlers for a production workload without validating isolation properties and recovery behavior.|runtimeclass
"""


def parse_specs() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for line_number, line in enumerate(RAW.splitlines(), 1):
        if not line.strip():
            continue
        fields = line.split("|")
        if len(fields) != 7:
            raise ValueError(f"spec line {line_number}: expected 7 fields, got {len(fields)}")
        slug, title, focus, method, checks, guardrail, source = (item.strip() for item in fields)
        rows.append({"slug": slug, "title": title, "focus": focus, "method": method,
                     "checks": checks, "guardrail": guardrail, "source": source})
    return rows


def content_for(spec: dict[str, str]) -> tuple[str, str]:
    description = (
        f"Use when a task involves {spec['focus']}. Record Kubernetes server and client versions, cluster "
        "distribution and provider, API versions, namespace and workload owner, data sensitivity, evidence "
        "requirements, and maintenance window. Check current Kubernetes and provider documentation, begin with "
        "read-only evidence, and validate changes in an approved environment. Do not modify production resources, "
        "credentials, or persistent data without explicit owner approval."
    )
    source_name, source_url = SOURCES[spec["source"]]
    body = f'''# {spec['title']}

## When to Use
Use this skill when {spec['focus']}. It is an operational checklist for an authorized Kubernetes cluster, repository, or staging environment; it does not itself authorize cluster access, changes, or incident response.

## Inputs and Boundaries
Record cluster identity, server and client versions, distribution/provider, API versions, namespace, resource owner, intended outcome, maintenance window, data sensitivity, and stop condition. Separate read-only investigation from an applied change. Prefer synthetic data and disposable namespaces for tests.

## Workflow
1. **Set the boundary.** Name the target resources, accountable owner, allowed read/write scope, success condition, rollback path, and actions that require separate approval.
2. **Establish evidence.** Preserve the smallest useful manifest, status, event, metric, or provider-configuration snapshot. Redact tokens, secret values, user data, and internal addresses before sharing.
3. **Apply the focused method.** {spec['method']}
4. **Verify a bounded result.** {spec['checks']} Compare against a known baseline or independent observation when practical; record uncertainty and untested cases.
5. **Hand off safely.** Summarize the result, versions, evidence, limitations, remaining tests, and decision owner. Keep proposed changes distinct from changes actually applied.

## Kubernetes Checks
- Verify the exact server/client versions, distribution, feature gates, API versions, and provider-managed boundaries relevant to the finding.
- Distinguish desired API objects, controller status, node/runtime behavior, and provider-side infrastructure evidence.
- Preserve object UIDs and timestamps when correlating events; treat manifests, logs, snapshots, and traces as potentially sensitive.
- Recheck current Kubernetes and provider documentation before using version-sensitive fields, defaults, or recovery procedures.

## Guardrails
{spec['guardrail']}
- Never print or export bearer tokens, Secret data, private keys, cloud credentials, or sensitive workload payloads.
- Do not mutate shared or production clusters, evict workloads, rotate credentials, delete storage, or alter network exposure without explicit authorization from the responsible owner.
- Do not bypass admission, Pod Security, RBAC, NetworkPolicy, TLS, or provider safeguards to make a test pass.
- Stop when resource ownership, data retention, failure impact, provider responsibility, or recovery authority is unclear.

## Acceptance
The result answers the stated operational question, identifies cluster and component versions, includes reproducible evidence and limitations, and names required owner approvals. It makes no unsupported claim of availability, security, durability, or provider compatibility.

## Topic Provenance
This workflow is independently authored for this repository using public Kubernetes documentation for topic discovery and technical reference. No upstream skill prose, code, scripts, commands, examples, prompts, or assets were copied. Kubernetes behavior and feature support vary by version and distribution; verify the effective behavior of the target cluster. This document does not grant authority to operate a cluster.

Technical reference: [{source_name}]({source_url})
'''
    return description, body


def tokens(value: str) -> set[str]:
    words = set(re.findall(r"[a-z0-9]+", value.casefold()))
    stop = {
        "and", "for", "with", "from", "into", "review", "audit", "analysis", "planning", "plan",
        "design", "assessment", "verification", "validation", "check", "checking", "workflow", "data",
        "model", "system", "systems", "skill", "use", "when", "task", "in", "of", "to", "the",
        "a", "an", "by", "on", "at", "as", "or", "against", "result", "reviewing", "kubernetes",
        "cluster", "pod", "pods", "workload", "workloads", "node", "nodes", "service", "services",
        "resource", "resources", "network", "policy", "policies", "storage", "volume", "api", "server",
        "control", "plane", "check", "test", "plan", "review", "audit", "risk", "readiness", "state",
        "evidence", "compatibility", "security", "scope", "owner", "system", "configuration", "lifecycle",
        "triage", "root", "cause", "failure", "behavior", "boundary", "application", "container", "containers",
        "deployment", "rollout", "version", "current", "status", "resource", "access", "read", "write",
    }
    return words - stop


def overlap_pairs(specs: list[dict[str, str]], names: list[str]) -> list[tuple[float, str, str]]:
    result: list[tuple[float, str, str]] = []
    candidate_tokens = [(s["slug"], tokens(s["slug"].replace("-", " ") + " " + s["focus"])) for s in specs]
    for i, (left, lt) in enumerate(candidate_tokens):
        for right, rt in candidate_tokens[i + 1:]:
            union = lt | rt
            score = len(lt & rt) / len(union) if union else 0.0
            if score >= 0.38:
                result.append((score, left, right))
        for old in names:
            ot = tokens(old.replace("-", " "))
            union = lt | ot
            score = len(lt & ot) / len(union) if union else 0.0
            if score >= 0.29:
                result.append((score, left, old))
    return sorted(result, reverse=True)


def preflight(specs: list[dict[str, str]]) -> tuple[str, str, list[str]]:
    if len(specs) != 100:
        raise ValueError(f"expected exactly 100 skills, got {len(specs)}")
    proposed = [item["slug"] for item in specs]
    if len(proposed) != len(set(proposed)):
        raise ValueError("duplicate proposed skill names")
    for spec in specs:
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", spec["slug"]):
            raise ValueError(f"invalid skill slug: {spec['slug']}")
        if spec["source"] not in SOURCES:
            raise ValueError(f"unknown source key: {spec['source']}")
    existing = {p.parent.name for p in SKILLS.rglob("SKILL.md")}
    if len(existing) != 1100:
        raise ValueError(f"expected 1100 existing skills before batch 12, found {len(existing)}")
    collisions = sorted(set(proposed) & existing)
    occupied = sorted(name for name in proposed if skill_path(SKILLS, category_for_skill(name), name).exists())
    if collisions or occupied:
        raise FileExistsError(f"refusing to overwrite skills; exact={collisions}, occupied={occupied}")

    readme = README.read_text(encoding="utf-8")
    index = INDEX.read_text(encoding="utf-8")
    if readme.count(README_MARKER) != 1:
        raise ValueError("README catalog marker missing or ambiguous")
    if index.count(INDEX_MARKER) != 1:
        raise ValueError("INDEX router marker missing or ambiguous")
    header_pattern = re.compile(r"(?m)^\*\*Current size:\*\* 1,100 skill directories after batch 11\..*$")
    if len(header_pattern.findall(readme)) != 1:
        raise ValueError("README current-size line missing or unexpected")

    readme_rows: list[str] = []
    index_rows: list[str] = []
    for spec in specs:
        description, body = content_for(spec)
        if len(description) > 1024 or len(description.split()) < 40:
            raise ValueError(f"{spec['slug']}: invalid description length")
        if not (400 <= len(body.encode("utf-8")) <= 60000):
            raise ValueError(f"{spec['slug']}: body size outside repository bounds")
        focus = spec["focus"][0].upper() + spec["focus"][1:]
        readme_rows.append(f"| [{spec['slug']}]({relative_skill_path(category_for_skill(spec['slug'], spec.get('focus', spec.get('trigger', ''))), spec['slug'], spec.get('focus', spec.get('trigger', '')))}) | {focus}. |")
        index_rows.append(f"| {focus} | [{spec['slug']}]({relative_skill_path(category_for_skill(spec['slug'], spec.get('focus', spec.get('trigger', ''))), spec['slug'], spec.get('focus', spec.get('trigger', '')))}) |")
    readme_updated = header_pattern.sub(
        "**Current size:** 1,200 skill directories after batch 12. Coverage includes agent workflows, engineering, science, security operations, medical-imaging AI, Apple-platform engineering, Kubernetes operations and platform engineering, media, and browser automation.",
        readme,
    )
    readme_updated = readme_updated.rstrip() + "\n" + "\n".join(readme_rows) + "\n"
    index_updated = index.rstrip() + "\n" + "\n".join(index_rows) + "\n"
    return readme_updated, index_updated, proposed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="preflight only; do not write files")
    args = parser.parse_args()
    specs = parse_specs()
    readme_updated, index_updated, proposed = preflight(specs)
    existing = {p.parent.name for p in SKILLS.rglob("SKILL.md")}
    pairs = overlap_pairs(specs, sorted(existing))
    print(f"Preflight passed: {len(proposed)} candidates, no exact collisions; README/INDEX markers and total checked before writes.")
    if pairs:
        print("Potential conceptual neighbors for manual review:")
        for score, left, right in pairs[:100]:
            print(f"  {score:.2f}  {left} <> {right}")
    else:
        print("No high-similarity names or within-batch candidate pairs found.")
    if args.check:
        print("Check-only mode: no files changed.")
        return 0

    for spec in specs:
        description, body = content_for(spec)
        content = f"---\nname: {spec['slug']}\ndescription: {json.dumps(description, ensure_ascii=False)}\n---\n\n{body}"
        directory = skill_path(SKILLS, category_for_skill(spec["slug"], spec.get("focus", spec.get("trigger", ""))), spec["slug"], spec.get("focus", spec.get("trigger", "")))
        directory.mkdir(parents=True, exist_ok=False)
        (directory / "SKILL.md").write_text(content, encoding="utf-8")
    README.write_text(readme_updated, encoding="utf-8")
    INDEX.write_text(index_updated, encoding="utf-8")
    print(f"Created {len(specs)} original skills; total now {len(existing) + len(specs)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
