"""Canonical nine-category taxonomy for repository skill folders."""
from __future__ import annotations

import re

CATEGORIES = {
    "ai-agent-systems": "AI & Agent Systems",
    "software-development": "Software & Development",
    "cloud-infrastructure-security": "Cloud, Infrastructure & Security",
    "data-analytics": "Data & Analytics",
    "business-operations": "Business & Operations",
    "science-health-research": "Science, Health & Research",
    "engineering-industry": "Engineering & Industry",
    "creative-media-design": "Creative, Media & Design",
    "education-public-service": "Education & Public Service",
}

CATEGORY_DESCRIPTIONS = {
    "ai-agent-systems": "Agent design, model interaction, prompt/context work, tool use, MCP, memory, and agent evaluation.",
    "software-development": "Programming, APIs, application development, software architecture, testing, and release workflows.",
    "cloud-infrastructure-security": "Cloud platforms, operating systems, containers, networking, DevOps, reliability, and cybersecurity.",
    "data-analytics": "Data engineering, databases, analytics, dashboards, spreadsheets, and geospatial data workflows.",
    "business-operations": "Finance, legal, insurance, workforce, product, marketing, sales, retail, hospitality, and supply operations.",
    "science-health-research": "Healthcare administration, clinical research, life and physical sciences, evidence, and research methods.",
    "engineering-industry": "Agriculture, construction, energy, climate assurance, manufacturing, hardware, robotics, and industrial systems.",
    "creative-media-design": "Visual and interaction design, games, image, audio, video, writing, and media production.",
    "education-public-service": "Education, learning design, civic administration, government, and nonprofit/public-service workflows.",
}

# The recent industry packs are explicitly assigned by their subject, rather
# than by a keyword that may appear in a generated skill's title.
DOMAIN_PREFIXES = {
    "agri-ops": "engineering-industry",
    "built-env": "engineering-industry",
    "climate-ops": "engineering-industry",
    "energy-ops": "engineering-industry",
    "mfg-ops": "engineering-industry",
    "civic-ops": "education-public-service",
    "edu-ops": "education-public-service",
    "data-eng": "data-analytics",
    "geo-ops": "data-analytics",
    "finance-ops": "business-operations",
    "gtm-ops": "business-operations",
    "hospitality-ops": "business-operations",
    "insure-ops": "business-operations",
    "legal-ops": "business-operations",
    "people-ops": "business-operations",
    "product-ops": "business-operations",
    "retail-ops": "business-operations",
    "supply-ops": "business-operations",
    "health-admin": "science-health-research",
    "trial-ops": "science-health-research",
    "medical-imaging": "science-health-research",
    "agent-telemetry": "ai-agent-systems",
    "backend-ops": "software-development",
    "container-assurance": "cloud-infrastructure-security",
    "ml-data-ops": "data-analytics",
    "growth-evidence": "business-operations",
    "omics-data": "science-health-research",
    "pcb-design": "engineering-industry",
    "edge-fleet": "engineering-industry",
    "blender-production": "creative-media-design",
    "premiere-production": "creative-media-design",
    "stem-lab": "education-public-service",
    "aas-agent-quality": "ai-agent-systems",
    "aas-agent-coordination": "ai-agent-systems",
    "aas-devtools": "software-development",
    "aas-mobile": "software-development",
    "aas-game": "creative-media-design",
    "aas-secure-delivery": "cloud-infrastructure-security",
    "aas-data": "data-analytics",
    "aas-docs": "business-operations",
    "aas-saas": "business-operations",
    "aas-visual": "creative-media-design",
    "aas-devrel": "business-operations",
}

# Reviewed one-off cases whose names alone are not enough for a reliable rule.
# Keep these exact slugs explicit so the one-time migration remains auditable.
SKILL_OVERRIDES = {
    "accessible-name-change-regression-check": "software-development",
    "architecture-blueprint-generator": "software-development",
    "architecture-decision-records": "software-development",
    "augmented-reality-development": "software-development",
    "autoresearch": "science-health-research",
    "backtest-information-leakage-audit": "business-operations",
    "batch-files": "software-development",
    "bench-read": "software-development",
    "bibliographic-deduplication": "science-health-research",
    "bioinformatics-sequence-analysis": "science-health-research",
    "bittorrent-client-development": "software-development",
    "blockchain-cryptocurrency-development": "software-development",
    "bom-component-sourcing": "engineering-industry",
    "bot-development": "ai-agent-systems",
    "camera-trap-detection-model-evaluation": "science-health-research",
    "checkpoint-artifact-hash-consistency-validator": "software-development",
    "ci-log-secret-redaction-summary-gate": "cloud-infrastructure-security",
    "citation-fragment-destination-repair": "science-health-research",
    "community-marketing": "business-operations",
    "configuration-default-documentation-drift-check": "software-development",
    "constellation-revisit-performance-analysis": "engineering-industry",
    "contradictory-web-claim-resolution-ledger": "ai-agent-systems",
    "create-llms": "ai-agent-systems",
    "create-specification": "software-development",
    "create-web-form": "software-development",
    "cuda-kernel-correctness-review": "software-development",
    "cuda-memory-transfer-profiling": "software-development",
    "dependabot": "software-development",
    "dialog-focus-return-regression-check": "software-development",
    "docs-version-selector-deep-link-verifier": "software-development",
    "drawio": "creative-media-design",
    "duplicate-record-review-bucket-closure": "data-analytics",
    "earliest-causal-test-error-trace": "software-development",
    "edge-inference-latency-budget": "ai-agent-systems",
    "effective-config-defaults-black-box-check": "software-development",
    "emulator-and-virtual-machine-development": "software-development",
    "error-empty-state-retry-path-verifier": "software-development",
    "faq-answer-source-freshness-rescan": "business-operations",
    "flaky-test-repeatability-classifier": "software-development",
    "generated-artifact-source-parity-hash-check": "software-development",
    "google-slides-presentation-review": "creative-media-design",
    "gpu-model-serving-cost-review": "ai-agent-systems",
    "grover-oracle-correctness-review": "science-health-research",
    "heterogeneity-analysis-planning": "science-health-research",
    "infsh-cli": "ai-agent-systems",
    "instruments-memory-allocation-retention-analysis": "software-development",
    "instruments-network-traffic-privacy-review": "software-development",
    "instruments-time-profiler-hotspot-ranking-audit": "software-development",
    "instruments-trace-capture-scope-plan": "software-development",
    "inverse-problem-identifiability-audit": "science-health-research",
    "issue-body-untrusted-instruction-triage-boundary": "ai-agent-systems",
    "keyboard-focus-order-change-localizer": "software-development",
    "landing-page-design": "creative-media-design",
    "large-text-reflow-overflow-check": "software-development",
    "local-markdown-cross-reference-integrity-loop": "software-development",
    "logic-synthesis-area-timing-analysis": "engineering-industry",
    "low-power-intent-verification": "engineering-industry",
    "macos-app-sandbox-file-access-boundary-test": "software-development",
    "macos-crash-diagnostic-log-redaction": "software-development",
    "macos-crash-report-symbolication-readiness": "software-development",
    "macos-dsym-build-identity-match": "software-development",
    "macos-installer-package-content-inventory": "software-development",
    "macos-keychain-access-group-review": "software-development",
    "macos-login-item-launch-agent-lifecycle-audit": "software-development",
    "macos-notarization-submission-evidence-audit": "software-development",
    "macos-notarization-ticket-stapling-verification": "software-development",
    "macos-privacy-manifest-consistency-check": "software-development",
    "macos-screen-capture-consent-and-attribution-check": "software-development",
    "macos-universal-binary-slice-validation": "software-development",
    "macos-update-feed-integrity-review": "software-development",
    "macos-virtual-machine-guest-host-evidence-check": "software-development",
    "macos-virtual-machine-snapshot-governance": "software-development",
    "markdown-anchor-heading-change-repair": "software-development",
    "memory-safety-patterns": "software-development",
    "microsoft-foundry-agent-observability": "ai-agent-systems",
    "minimal-test-reproducer-sculptor": "software-development",
    "mqtt-session-and-delivery-semantics-review": "engineering-industry",
    "multi-camera-time-synchronization-review": "engineering-industry",
    "multi-chunk-fetch-completeness-ledger": "ai-agent-systems",
    "multi-session-project-blueprinting": "ai-agent-systems",
    "neural-network-development": "ai-agent-systems",
    "nonlinear-dynamical-stability-analysis": "science-health-research",
    "nvidia-cuda-performance-workflow": "software-development",
    "ode-stiffness-and-solver-selection": "science-health-research",
    "omniverse-scene-integration-review": "creative-media-design",
    "orbital-element-propagation-check": "engineering-industry",
    "paper-trading-sandbox-readiness-review": "business-operations",
    "parallel-findall": "ai-agent-systems",
    "parallel-worker-artifact-manifest-reconciliation": "ai-agent-systems",
    "payload-accommodation-interface-review": "engineering-industry",
    "pde-boundary-condition-consistency-review": "science-health-research",
    "per-iteration-tool-budget-before-dispatch": "ai-agent-systems",
    "performance-benchmarking-and-regression-detection": "software-development",
    "physical-law-dimensional-analysis": "science-health-research",
    "planetscale-schema-recommendations-agent-loop": "ai-agent-systems",
    "post-layout-parasitic-impact-audit": "engineering-industry",
    "qaoa-problem-encoding-review": "science-health-research",
    "qemu-kernel-lab-experiment-design": "software-development",
    "read-only-to-write-capability-escalation-review": "ai-agent-systems",
    "readme-command-instruction-replay-check": "software-development",
    "real-world-evidence-study-design": "science-health-research",
    "redirected-source-canonical-url-audit": "ai-agent-systems",
    "reduced-motion-interaction-parity-test": "creative-media-design",
    "remote-mac-build-agent-isolation-review": "cloud-infrastructure-security",
    "requirement-row-to-test-identifier-coverage-audit": "software-development",
    "requirements-interview-and-specification": "software-development",
    "reset-domain-crossing-verification-plan": "engineering-industry",
    "responsive-image-crop-outlier-reproduction": "creative-media-design",
    "responsive-overflow-breakpoint-localizer": "software-development",
    "resume-session-permission-revalidation": "ai-agent-systems",
    "rtl-lint-triage": "engineering-industry",
    "runbook-mock-state-procedure-rehearsal": "cloud-infrastructure-security",
    "runtime-log-error-burst-deduplicator": "cloud-infrastructure-security",
    "safe-output-count-and-target-policy-check": "ai-agent-systems",
    "same-error-fingerprint-stop-rule-enforcer": "ai-agent-systems",
    "scan-test-dft-architecture-planning": "engineering-industry",
    "schema-change-consumer-impact-walkthrough": "data-analytics",
    "seo-audit": "business-operations",
    "shared-agent-memory-acl-boundary-review": "ai-agent-systems",
    "side-effect-idempotency-key-replay-proof": "ai-agent-systems",
    "skeleton-to-content-layout-shift-capture": "software-development",
    "task-decomposition-and-planning": "ai-agent-systems",
    "template-engine-development": "software-development",
    "timestamp-timezone-normalization-edge-audit": "data-analytics",
    "uncategorized-system-building": "software-development",
    "uv-workflow": "creative-media-design",
    "verification-and-stopping": "ai-agent-systems",
    "versioned-library-documentation-research": "software-development",
    "voxel-engine-development": "software-development",
    "vqe-convergence-and-ansatz-diagnostic": "science-health-research",
    "write-read-consistency-staleness-window-probe": "software-development",
    "xcodebuild-destination-pinning-review": "software-development",
    "xctrace-target-process-identity-validation": "software-development",
}

# Ordered, root-of-slug prefixes for the remaining catalog. Longer/specialized
# prefixes are listed before broad roots (for example, ai-image before ai).
PREFIX_RULES = (
    ("creative-media-design", (
        "ad-creative", "ai-content", "ai-image", "ai-video", "3d-renderer",
        "animate", "blender", "copy-editing", "copywriting", "digital-audio",
        "figma", "game", "image", "music", "podcast", "premiere",
        "product-photography", "video", "visual", "voice-interface",
        "web-design", "storyboard", "media",
    )),
    ("ai-agent-systems", (
        "agent", "agentic", "agentspace", "ai-agent", "ai-", "azure-ai", "copilot",
        "gh-aw", "llm", "mcp", "multi-agent", "prompt", "rag", "skill",
        "tool-argument", "tool-execution", "tool-response", "tool-timeout",
        "tool-unavailable", "context-engineering", "continuous-learning",
        "source-grounded", "web-claim", "web-query", "web-quotation",
        "web-search", "parallel-web", "evidence-certainty", "evidence-coverage",
        "human-approval", "human-escalation", "subagent", "success-signal",
        "untrusted-input", "external-write", "failure-recovery", "attempt-diff",
        "partial-completion", "loop-finalization", "progress-ledger",
        "state-and-handoff", "memory-index", "codebase-memory", "agent-memory",
    )),
    ("education-public-service", (
        "civic", "edu", "education", "government", "municipal", "nonprofit",
        "public-sector", "school", "social-service", "student", "teacher",
        "teaching", "university", "library",
    )),
    ("science-health-research", (
        "admet", "astronomy", "bio", "bioacoustic", "biomedical", "case-control", "causal",
        "clinical", "conservation", "diagnostic", "drug", "epidemiological",
        "evidence", "experimental", "forest-plot", "genomic", "health",
        "laboratory", "literature", "medical", "meta-analysis", "molecular",
        "observational-study", "pharma", "physics", "publication-bias", "quantum",
        "randomized-trial", "research", "rna-seq", "sample-size", "science",
        "scientific", "single-cell", "species", "study", "survival-analysis",
        "systematic-review", "theoretical-result", "wildlife", "biomarker",
        "preprint", "mass-spectrometry", "proteomics", "metabolic-modeling",
        "computational-chemistry", "chemical", "astronomy", "climate-science",
    )),
    ("engineering-industry", (
        "adc", "agri", "analog", "built", "cfd", "circuit", "clock-domain",
        "clock-tree", "cubesat", "digital-twin", "embedded", "emc-",
        "finite-difference", "finite-element", "finite-volume", "fpga",
        "hardware", "iot", "kicad", "lithography", "materials-science",
        "measurement-instrument", "mixed-signal", "nvidia-physical-ai",
        "pcb", "physical-ai", "robotics", "semiconductor", "silicon",
        "spacecraft", "spice", "static-timing", "transistor", "wafer",
        "sensor", "edge-site", "edge-model", "energy", "manufacturing",
        "agriculture", "built-env", "climate-ops", "mfg-ops", "mechanical",
        "electronics", "control-system", "industrial", "automotive",
    )),
    ("cloud-infrastructure-security", (
        "application-security", "azure", "cloud", "container", "docker",
        "devops", "firewall", "infrastructure", "kali-linux", "kubernetes",
        "linux", "network", "nvidia-container", "operating-system", "pentest",
        "security", "vulnerability", "vulnerability-remediation", "azure-sre",
        "incident-response", "malware", "forensic", "backup", "identity",
        "seccomp", "ebpf", "cgroup", "server", "sre", "macos-security",
    )),
    ("data-analytics", (
        "adobe-analytics", "adobe-cja", "analytics", "arize", "chart", "csv",
        "dashboard", "data", "database", "dataverse", "earth-observation",
        "geospatial", "geo-", "google-sheets", "graph-rag", "knowledge-graph",
        "market-data", "metric", "remote-sensing", "spreadsheet", "sql",
        "stac", "etl", "data-export", "data-quality", "data-pipeline",
    )),
    ("business-operations", (
        "ad-", "billing", "broker", "business", "calendar", "commerce",
        "contract", "customer", "finance", "gmail", "google-admin",
        "google-calendar", "google-chat", "google-docs", "google-drive",
        "google-forms", "google-workspace", "gtm", "hospitality", "insurance",
        "insure", "legal", "loops", "market", "marketing", "people", "portfolio",
        "pricing", "product", "procurement", "revenue", "retail", "sales",
        "supply", "trading", "workforce", "hr-", "payroll", "hospital-ops",
        "financial", "liquidity", "transaction-cost", "strategy", "onboarding",
        "fundraising", "tax-", "customer-support", "service-operations",
    )),
    ("software-development", (
        "accessibility", "api", "app", "apple", "angular", "browser", "build",
        "code", "command-line", "create-github", "dependency", "developer",
        "fastapi", "frontend", "git", "github", "gitlab", "golang", "ios-",
        "java", "mobile", "programming", "pull-request", "pydantic", "react",
        "release", "repository", "rust", "swift", "swiftui", "typescript",
        "web", "xcode", "app-store", "application", "codeql", "test", "testing",
        "software", "framework", "cli-", "shell-", "javascript", "backend",
        "database-engine", "api-", "codebase", "environment-parity", "regex-engine",
        "git-implementation", "code-review", "gitlab-", "github-", "release-",
    )),
)

# Keyword-only rescue rules use the INDEX task description for ambiguous slugs.
DESCRIPTION_RULES = (
    ("ai-agent-systems", re.compile(r"\b(agent|agentic|copilot|LLM|MCP|prompt engineering|RAG|retrieval-augmented|tool-calling|AI assistant)\b", re.I)),
    ("science-health-research", re.compile(r"\b(clinical|medical|healthcare|scientific|research study|laboratory|biology|biomedical|epidemiology|systematic review|quantum|physics)\b", re.I)),
    ("engineering-industry", re.compile(r"\b(manufacturing|engineering|hardware|embedded|semiconductor|agriculture|construction|utilities|industrial|robotics|circuit|energy system)\b", re.I)),
    ("cloud-infrastructure-security", re.compile(r"\b(cloud|cybersecurity|Kubernetes|Linux|Docker|DevOps|SRE|network security|vulnerability|incident response)\b", re.I)),
    ("data-analytics", re.compile(r"\b(data engineering|analytics|database|geospatial|GIS|spreadsheet|dashboard|business intelligence|data pipeline|SQL)\b", re.I)),
    ("business-operations", re.compile(r"\b(finance|insurance|legal|retail|hospitality|supply chain|human resources|sales|customer success|business operations|procurement)\b", re.I)),
    ("creative-media-design", re.compile(r"\b(design|creative|visual|image|video|audio|game|storyboard|photography|copywriting)\b", re.I)),
    ("education-public-service", re.compile(r"\b(education|school|classroom|government|public sector|civic|nonprofit|student|teacher)\b", re.I)),
    ("software-development", re.compile(r"\b(software|programming|developer|API|application|browser|codebase|framework|testing|repository)\b", re.I)),
)


def _has_prefix(slug: str, prefix: str) -> bool:
    return slug == prefix or slug.startswith(prefix + "-")


def classification_for_skill(slug: str, description: str = "") -> tuple[str, str]:
    """Return a category and the rule that assigned it, for auditability."""
    if slug in SKILL_OVERRIDES:
        return SKILL_OVERRIDES[slug], "reviewed exact-slug override"
    for prefix, category in sorted(DOMAIN_PREFIXES.items(), key=lambda item: len(item[0]), reverse=True):
        if _has_prefix(slug, prefix):
            return category, f"domain prefix: {prefix}"
    for category, prefixes in PREFIX_RULES:
        for prefix in prefixes:
            if _has_prefix(slug, prefix.rstrip("-")) or (prefix.endswith("-") and slug.startswith(prefix)):
                return category, f"slug prefix: {prefix}"
    for category, pattern in DESCRIPTION_RULES:
        if pattern.search(description):
            return category, f"INDEX description: {pattern.pattern}"
    # The residual general-purpose repository workflows are grouped with software
    # and developer operations; the dry-run report exposes this fallback for QA.
    return "software-development", "general workflow fallback"


def category_for_skill(slug: str, description: str = "") -> str:
    """Return one of the nine categories using explicit domains then skill topic."""
    return classification_for_skill(slug, description)[0]
